### ISSUE TITLE
ABM not available in plugin feeds

### ISSUE THREAD

**Issue by p17blo** [oe-alliance/oe-alliance-core#119]
ABM is not available withing plugin feeds

OPKG update
OPKG upgrade 
both run and Autobouquetsmaker is not available within the feed - As I understand this is the file that controls that source?

**Comment by AbuBaniaz** [comment]
Have you tried speaking to the image team of your receiver?

**Comment by AbuBaniaz** [comment]
See here.

https://github.com/oe-alliance/oe-alliance-core/commit/25a07c6c6123ea4cd8ed5f2d2cc4c05e080b91db
