### ISSUE TITLE
Update version of IPTV Player in feed

### ISSUE THREAD

**Issue by p17blo** [oe-alliance/oe-alliance-core#120]
How do I go about getting the version of IPTV player updated that in the plugin feed on OpenATV?  The version currently in the feed is about v90.02.00.00 - This contains some errors that cause a loop when installing - The latest version is v114.02.00.00
I'm not sure if you need this but the gitlab link is https://gitlab.com/iptvplayer-for-e2/iptvplayer-for-e2

If this is not the correct place to request this, could you please give some advice of where this should be requested?

**Comment by arn354** [comment]
iptv-player ipk is located in 3rd party ipk's https://github.com/oe-alliance/3rdparty-plugins
we do not have a bitbake receipe for it, we simply added the final ipk.
Do you have a working ipk?
