### ISSUE TITLE
et8500 line is in error

### ISSUE THREAD

**Issue by TwolDE2** [oe-alliance/oe-alliance-core#126]
double ipk in et8500 line

**Comment by TwolDE2** [comment]
sorry should have said  meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-3rdparty-plugins.bb

**Comment by RobvanderDoes** [comment]
Oops, sorry, fixed.

**Comment by AbuBaniaz** [comment]
Closed with 
https://github.com/oe-alliance/oe-alliance-core/commit/d7f7e4ac462e184fff1025172dd067c3f007068e
