### ISSUE TITLE
Update gstreamer to 1.11.2.1 master git

### ISSUE THREAD

**Issue by tuxdell** [oe-alliance/oe-alliance-core#178]
The file libgstrawparse.so should be in plugins-bad, no in plugins-base.

**Comment by christophecvr** [comment]
Ho now that is changed it is in plugins base now.

**Comment by christophecvr** [comment]
https://cgit.freedesktop.org/gstreamer/gst-plugins-base/

**Comment by atvcaptain** [comment]
here more info: https://gstreamer.freedesktop.org/documentation/splitup.html

base, good, ugly  bad....
