### ISSUE TITLE
Rytec EPG Source

### ISSUE THREAD

**Issue by CloudItaly** [oe-alliance/oe-alliance-core#188]
Hi, this mirror is down: xmltvepg.nl
Produce a new rytec.sources.xml without this mirror, please. 

https://github.com/oe-alliance/oe-alliance-core/blob/4.0/meta-oe/recipes-oe-alliance/enigma2-plugins/epgimport-rytec.bb

**Comment by AbuBaniaz** [comment]
The mirror is not down.  It is just missing "digiturk.channels.xml.gz". Surely it would be better for whoever is in charge of that site to grab missing file from the other mirror.
