### ISSUE TITLE
Plz update the sabnzbd for oatv 

### ISSUE THREAD

**Issue by heisert** [oe-alliance/oe-alliance-core#204]
The last update was a very long time ago. Atm its not working very well because the unrar version is outdated. Many files cant be extracted while in Version 5 the password form got a change. 
It's not working well on mips/arm box versions. 

I hope we see a update (maybe to 2.1) or only to a newer unrar 5+ version. It would help a lot. 

Thanks

**Comment by atvcaptain** [comment]
done sabnzbd to 1.10 and unrar to 5.5.5

**Comment by heisert** [comment]
Thanks for updating but It's not working with newest sabzbd. Cant start the Service on the network/service

**Comment by atvcaptain** [comment]
please check this
opkg update
opkg install python-multiprocessing

**Comment by heisert** [comment]
Works got only this errors 


WARNING vor 3 Minuten SABYenc module... NOT found! Expecting v3.0.2 - https://sabnzbd.org/sabyenc

WARNING vor 3 Minuten SABnzbd was started with encoding ANSI_X3.4-1968, this should be UTF-8. Expect problems with Unicoded file and directory names in downloads.

Speed up repairs by installing multicore Par2, it is available for many platforms. https://sabnzbd.org/wiki/installation/multicore-par2

**Comment by arn354** [comment]
root@gbquad4k: opkg list |grep python-sabyenc
python-sabyenc - 3.0.2-r0 - sabyenc - yEnc Module for Python modified for SABnzbd
python-sabyenc-dbg - 3.0.2-r0 - sabyenc - yEnc Module for Python modified for SABnzbd - Debugging files
root@gbquad4k:

successfully build the package, i add it - we will see, i do not use SABnzbd

**Comment by heisert** [comment]
Cool but how to install?

**Comment by heisert** [comment]
Could this help for the utf-8 encoding warning? 
https://github.com/sabnzbd/sabnzbd/issues/831

**Comment by heisert** [comment]
opkg install python-sabyenc
Couldn't find anything to satisfy 'python-sabyenc'.
Unknown package 'python-sabyenc'.
Collected errors:
 * opkg_solver_install: Cannot install package python-sabyenc.

**Comment by arn354** [comment]
the bb is not yet pushed to build

**Comment by atvcaptain** [comment]
done

**Comment by heisert** [comment]
Seems its working! Warning is gone. _Thanks_ arn354. 

Only 1 warning left:

WARNING vor 2 Minuten SABnzbd was started with encoding ANSI_X3.4-1968, this should be UTF-8. Expect problems with Unicoded file and directory names in downloads.

**Comment by atvcaptain** [comment]
i dont use this, send info that must be change
