### ISSUE TITLE
Please add support for TP-Link Archer T4U v2 AC1300 USB Wifi Adapter

### ISSUE THREAD

**Issue by tenchi71** [oe-alliance/oe-alliance-core#227]
Hello,

The Realtek 8812au driver package is missing an entry for the TP-Link Archer T4U v2 AC1300 USB 3.0 WiFi stick. The current kernel module available does not load when this device is connected to the STB as it lacks the Device ID needed inorder to detect the device and load the module.

According to wikidev, the Archer T4U v2 uses the Realtek rtl8812au chipset:
https://wikidevi.com/wiki/TP-LINK_Archer_T4U_v2

I have confirmed the Device ID is 2357: 010d via lsusb.
The following line needs to be added to the usb_intf.c file, under the section #ifdef CONFIG_RTL8812A:

{USB_DEVICE(0x2357, 0x010d),.driver_info = RTL8812}, /* TP-Link - Archer T4U AC1300 */

For reference:
This change was was made to the Realtek rtl8812au Linux driver fork found on abperiasamy/rtl8812AU_8821AU_linux: 
https://github.com/abperiasamy/rtl8812AU_8821AU_linux/pull/189

Requesting to have this device id added to the 8812au kernel module for oe-alliance/openatv. 

Many Thanks

**Comment by atvcaptain** [comment]
done: https://github.com/oe-alliance/oe-alliance-core/commit/3e80b6da9b7b60104b7c0bdae693e7f7da6cdace
