### ISSUE TITLE
kernel-module-block2mtd

### ISSUE THREAD

**Issue by ghost** [oe-alliance/oe-alliance-core#229]
hello 

please i try to build my own image for dm800se with omb and this one depend kernel-module-block2mtd
i check the kernel and is enabled on defconfig 

so why i get error for buiding this module

**Comment by arn354** [comment]
which error?

**Comment by Schimmelreiter** [comment]
Simple:
CONFIG_BLOCK2MTD=y
not 
CONFIG_BLOCK2MTD=m

So there is no module kernel-module-block2mtd, but the feature is built into the kernel.

**Comment by oostende** [comment]
@schimmelreiter yes is with y in defconfig 
But I get error 
Kernel module .... not found

**Comment by Schimmelreiter** [comment]
```
10 PRINT "Same question"
20 PRINT "Answer from https://github.com/oe-alliance/oe-alliance-core/issues/229#issuecomment-337818562"
30 GOTO 10
```
