### ISSUE TITLE
buildcrash nextp3 branch

### ISSUE THREAD

**Issue by schleichdi2** [oe-alliance/oe-alliance-core#233]
In wpasupplicant ist der patch key-replay-cve-multiple.patch doppelt in openembeddet-core und meta-oe-alliance
In python fehlt python-constantly python-hyperlink python-incremental ohne die bootet box nicht
In davfs2,dvdbackup fehlt ein gettext

In wpasupplicant, the patch key-replay-cve-multiple.patch is double in openembeddet-core and meta-oe-alliance
In python, python-constant python-hyperlink python-incremental is missing box not booting
In davfs2, dvdbackup is missing a gettext

samba 4.6.7 fails to install

chmod: cannot access '/home/harry/OPENNFR6.3/Buildumgebung/oe-alliance/builds/opennfr/release/g300/tmp/work/mips32el-oe-linux/samba/4.6.7-r3/image/etc/sudoers.d': No such file or directory

**Comment by atvcaptain** [comment]
yes we working now to fix all issue in nextp4 branch need 2-3 month use oe-a 4.1 this is now the current
