### ISSUE TITLE
Zgemma i55 update drivers (commit c6367f301428fb2a82e77290c9970bedc3f10d88)

### ISSUE THREAD

**Issue by graterlia** [oe-alliance/oe-alliance-core#238]
On my i55, the drivers from 2017.10.27 do not load properly.
modprobe when loading file i55_5.ko displays the message:
"modprobe: ERROR: could not insert 'i55_4': Unknown symbol in module, or unknown parameter"
The problem is not with the drivers of 2017.10.09.

**Comment by atvcaptain** [comment]
ok we check this, thx for feedback

**Comment by atvcaptain** [comment]
we rollback the driver to 2017.10.09, and wait for a new update
