### ISSUE TITLE
When copying others work please don't remove information

### ISSUE THREAD

**Issue by athoik** [oe-alliance/oe-alliance-core#24]
Dear OE-Alliance,

Please when copying patches, at least give credits to it's author. 

https://github.com/oe-alliance/oe-alliance-core/commit/74da23c1fde82f646894d24f4b62177364842684

This is not how Open Source works..

**Comment by atvcaptain** [comment]
i dont unterstand: https://github.com/oe-alliance/oe-alliance-core/commit/ed59e81e2fd3c31bb4b467e4cc630f121fff09b6

infos include

**Comment by athoik** [comment]
That's not the same commit.

There some people spending their free time to workaround CLOSED SOURCE issues. 

So at least its ethic to retain patch information. 

We are hobbyst and we are giving to Open Source community unlike others.

**Comment by atvcaptain** [comment]
i have spend many time and have found the same info at 19.12 ask andy i have send andy a patch and the info we need gst-ffmeg , i have get the info from bh image

**Comment by athoik** [comment]
Look here: https://github.com/oe-alliance/oe-alliance-core/commit/1ddb7f9efcd7aec3e789332f618fd9eee316baa5#commitcomment-4884704

I comment about first attempt solving wma on VU.

But i gave credits to people involved in order to create that patch, and that credits gone.

It is sure that we conclude to the same results. You can add additional information in the commit message (append or prepend)

**Comment by atvcaptain** [comment]
i have say its a merge issue not more your name is in the commit  i think  is now good

**Comment by athoik** [comment]
Anyway, you can't keep everyone happy.

I don't want to argue, at least Open Source Community has benefit from patches and VU users (that use open images OpenPLi or OA-E) will be happier.

Until next time,
Athoik

**Comment by athoik** [comment]
Thanks for clearing this out @atvcaptain
