### ISSUE TITLE
dinoboot-emmc_image.bbclass

### ISSUE THREAD

**Issue by tromoto** [oe-alliance/oe-alliance-core#255]
It seems that in order to make a more compact IMG file some nasty problems were introduced. At least 3 of them of which 2 are not that benign.

sfdisk --verify /dev/mmcblk1

will report bad stuff:

GPT PMBR size mismatch (7634943 != 15661055) will be corrected by w(rite).
The backup GPT table is corrupt, but the primary appears OK, so that will be used.
/dev/mmcblk1:
MyLBA mismatch with real position at backup header.

besides, in the ...image recipe there is an useless (?) 'storage' partition of 2.9 GB that actually does not work. I do not think that faking GPT partitions in OE makes sense, but ok. 
If there is a special reason to make a GPT uSD/partition for some security boot reasons, fine, but a plain MBR seems to work just as fine. 

Perhaps a wic wks could be of some use.

u5sdimage.wks

part / --source rootfs --size 1024 --ondisk mmcblk --fstype=ext4 --label rootfs1 --align 4
#bootloader  --ptable gpt

to really make a GPT image (why ?), uncomment bootloader stuff.

**Comment by atvcaptain** [comment]
you know we not use this image, it was only for test, we use the kernel and rootfs.tar file, i remove the sdcard.img soon and all fine
