### ISSUE TITLE
[dinobot 4k] SCI0 Error Reading ATR on Irdeto Card

### ISSUE THREAD

**Issue by linuxstv** [oe-alliance/oe-alliance-core#269]
I've tried Irdeto card on my dinobot 4k internal reader with OSCam, and the result is always like this:
`ERROR: no characters found in ATR!`

To make sure that this is driver related error, I also tried Tongfang card. It detected the card correctly. So, no problem with Tongfang. Only Irdeto is the problem for me.

**Comment by atvcaptain** [comment]
we send bug report to driver team, we must now wait

**Comment by linuxstv** [comment]
I'm so sorry, I forgot to close this. It works now for the CAID 604, my card has been detected normally. Thank you very much.
![screenshot from 2018-05-11 00-29-43](https://user-images.githubusercontent.com/15664372/39884006-a98104ee-54b2-11e8-9b4f-d3c70ff9d960.png)
