### ISSUE TITLE
[dinobot 4k] Can anyone confirm SNRdB and Bitrate are working?

### ISSUE THREAD

**Issue by linuxstv** [oe-alliance/oe-alliance-core#277]
Hi guys.

Can any one confirm wether SNRdB and Bitrate (with BitrateCalc converter) are just working on Dinobot 4K? I've tried the same widget on my skin, but those two don't work as on other box (for example on Spark Box). Here's my skin screenshot:

![1_0_1_1_1_1_3120eb4_0_0_0 4](https://user-images.githubusercontent.com/15664372/37453431-34e3dc20-286a-11e8-902d-7a64d3ab83b7.jpg)

Signal Quality is always showing "percentage", but not "dB".
Video Bitrate and Audio Bitrate are always showing "0 kbit/s".

**Comment by atvcaptain** [comment]
issue allready report to driver team, you must wait

**Comment by linuxstv** [comment]
Thank you, it works now on Dinobot4K. Just needed to rework FrontendInfo converter.

**Comment by atvcaptain** [comment]
you have rework any info for this ?

**Comment by linuxstv** [comment]
I've only edited my FrontendInfo.py on my local receiver. Haven't pushed the changes to any Enigma2 github sources at the moment.
