### ISSUE TITLE
OpenWebif new Design 

### ISSUE THREAD

**Issue by rubix86** [oe-alliance/oe-alliance-core#300]
Does OpenWebif new design work perfectly with OE-Alliance images or not? because it's does not work with me
![screenshot](https://user-images.githubusercontent.com/17280907/39727502-3a63a8ac-5253-11e8-9827-cba5b1459e23.PNG)

**Comment by arn354** [comment]
![13-05-_2018_11-02-39](https://user-images.githubusercontent.com/4148122/39965641-511a65d8-569d-11e8-91b3-53e0bb0bb9ba.png)

**Comment by rubix86** [comment]
I use latest OpenBlackHole 4.1.028 image
Is openbh source from same source of OE-Alliance or not? 
when i use new desgin I got this
![owf](https://user-images.githubusercontent.com/17280907/39971733-a3620f22-5700-11e8-9be6-9c98812bcb27.PNG)
other images like OpenATV are ok and even VTi is ok so problem not from browser

**Comment by arn354** [comment]
you should ask the image team to check and fix in their forums, not sure if they respond here.

**Comment by rubix86** [comment]
okay thanks I will try that

**Comment by AbuBaniaz** [comment]
You have to install the extra themes and then restart

Menu > Plugins > Extensions > Openwebif-themes
