### ISSUE TITLE
[Dinobot 4K] Remote Control Does Not Respond 

### ISSUE THREAD

**Issue by linuxstv** [oe-alliance/oe-alliance-core#305]
Hi guys.

Am I the only one whose remote control doesn't work after upgrading to dinobot-showiframe-u5 dated 20180509 on Dinobot 4K box? It occured after I applied this update:
https://github.com/oe-alliance/oe-alliance-core/commit/3db8ca0b63eaabbcecf39604fe2bd2fbce96a73e#diff-4fda3f3e0b6446f01d150026d6ee96ff

Thank you.

**Comment by atvcaptain** [comment]
np here rcu works with my dinobot 4k , do you use openatv or the pli homebuild image ?

**Comment by linuxstv** [comment]
I use openpli homebuild image by now.

Thank you for the confirmation. I'll dig into OpenPLi codes then.
