### ISSUE TITLE
Error compiling vu zero 4k openatv ubuntu 18.04

### ISSUE THREAD

**Issue by frankviana** [oe-alliance/oe-alliance-core#308]
Build Configuration:
BB_VERSION        = "1.33.3"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "ubuntu-18.04"
TARGET_SYS        = "arm-oe-linux-gnueabi"
MACHINE           = "vuzero4k"
DISTRO            = "openatv"
DISTRO_VERSION    = "6.1"
TUNE_FEATURES     = "arm armv7ve vfp neon vfpv4 callconvention-hard cortexa15"
TARGET_FPU        = "hard"
meta              = "HEAD:901659a51cd53625a93f57a9c5865e90a07ec09d"
meta-oe           
meta-multimedia   
meta-networking   
meta-filesystems  
meta-python       
meta-webserver    = "HEAD:cdb428e7c49899675ee7b7a43f6cecdb5b4c2546"
meta-oe           = "HEAD:cc688d4d71015a0242f99179ff39621d3525d7a6"
meta-qt5          = "HEAD:817fc2a19b63908f0628f29c2940a1dc44563ef9"
meta-airdigital   
meta-azbox        
meta-ax           
meta-blackbox     
meta-ceryon       
meta-cube         
meta-dags         
meta-dinobot      
meta-dream        
meta-ebox         
meta-edision      
meta-entwopia     
meta-formuler     
meta-fulan        
meta-gfutures     
meta-gigablue     
meta-ini          
meta-ixuss        
meta-linkdroid    
meta-broadmedia   
meta-odin         
meta-odroid       
meta-octagon      
meta-protek       
meta-skylake      
meta-tiviar       
meta-tripledot    
meta-ultramini    
meta-vuplus       
meta-wetek        
meta-xp           
meta-xtrend       
meta-xcore        = "HEAD:cc688d4d71015a0242f99179ff39621d3525d7a6"
meta-local        = "4.1:e1cc92bd21415342f54f024ac06db6a5c3a5617b"

Initialising tasks: 100% |######################################################################################################| Time: 0:07:25
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: gnu-config-native-20150728+gitAUTOINC+b576fa87c1-r0 do_unpack: Fetcher failure: Fetch command export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/frank/oealliance/build-enviroment/openembedded-core/scripts/native-intercept:/home/frank/oealliance/build-enviroment/openembedded-core/scripts:/home/frank/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/usr/bin/x86_64-linux:/home/frank/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/usr/bin:/home/frank/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/usr/sbin:/home/frank/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/usr/bin:/home/frank/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/sbin:/home/frank/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/recipe-sysroot-native/bin:/home/frank/oealliance/build-enviroment/bitbake/bin:/home/frank/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/hosttools"; export HOME="/home/frank"; git -c core.fsyncobjectfiles=0 branch --set-upstream master origin/master failed with exit code 128, output:
fatal: the '--set-upstream' option is no longer supported. Please use '--track' or '--set-upstream-to' instead.

ERROR: gnu-config-native-20150728+gitAUTOINC+b576fa87c1-r0 do_unpack: Function failed: base_do_unpack
ERROR: Logfile of failure stored in: /home/frank/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/x86_64-linux/gnu-config-native/20150728+gitAUTOINC+b576fa87c1-r0/temp/log.do_unpack.15210
ERROR: Task (virtual:native:/home/frank/oealliance/build-enviroment/openembedded-core/meta/recipes-devtools/gnu-config/gnu-config_git.bb:do_unpack) failed with exit code '1'
NOTE: Tasks Summary: Attempted 37 tasks of which 11 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  virtual:native:/home/frank/oealliance/build-enviroment/openembedded-core/meta/recipes-devtools/gnu-config/gnu-config_git.bb:do_unpack
Summary: There were 35 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
Makefile:875: recipe for target 'image' failed
make: *** [image] Error 1

**Comment by nickersk** [comment]
18.04 comes with git 2.17.0. for 6.1 build u'll need to use older git version (2.14 and below). see https://patchwork.openembedded.org/patch/145072/

**Comment by frankviana** [comment]
thank you... I just installed ubuntu 16:04 yesterday... I did the question to see the problem, only.
