### ISSUE TITLE
New twinplus drivers?

### ISSUE THREAD

**Issue by joakim-tjernlund** [oe-alliance/oe-alliance-core#325]
I can see that sf4008, sf128,sf138 and sf3038 has its drivers updated:
https://github.com/oe-alliance/oe-alliance-core/commits/4.1/meta-brands/meta-broadmedia/recipes-drivers
but not twinplus for a while. I think sf3038 and twinplus are the same machines so there should be
a drivers update waiting.

**Comment by atvcaptain** [comment]
yes but company dont send us the update

**Comment by joakim-tjernlund** [comment]
hmm, and sf3038 and twinplus is not the same as I thought?
