### ISSUE TITLE
nextp3 - ERROR: enigma2.bb:do_configure

### ISSUE THREAD

**Issue by nickersk** [oe-alliance/oe-alliance-core#326]
getting this:
config.status: error: Something went wrong bootstrapping makefile fragments
     for automatic dependency tracking.  Try re-running configure with the
     '--disable-dependency-tracking' option to at least be able to build
     the package (albeit without support for automatic dependency tracking).

in config.log:
config.status:1930: executing depfiles commands
config.status:2007: cd lib       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
/tmp/GmqTB95z:3140: .deps/python/enigma_python.Pcpp: No such file or directory
make: *** No rule to make target '.deps/python/enigma_python.Pcpp'.  Stop

**Comment by atvcaptain** [comment]
looks autotools broken, autotools.class use '--disable-dependency-tracking , but looks the option was ignored

**Comment by nickersk** [comment]
there is --enable-dependency-tracking in extra_oeconf in enigma2.bb will try to switch it and see.

**Comment by nickersk** [comment]
with --disable-dependecy-tracking fail too .deps/python/enigma_python.Tpo: No such file or directory

**Comment by atvcaptain** [comment]
i check first rollback automake to 1.15.1

**Comment by atvcaptain** [comment]
test with rollback to 1.15.1 all ok

**Comment by atvcaptain** [comment]
i test now revert this commit : http://git.savannah.gnu.org/cgit/automake.git/commit/?id=333b98f2d108111e9a99e7ede17de7f0a1adba03

**Comment by nickersk** [comment]
confirmed, no errors with 1.15.1.

**Comment by atvcaptain** [comment]
after revert 4 commits no success
0001-Revert-automake-Depend-on-LIBOBJDIR-for-LIBOBJS-and-.patch
0002-Revert-Revert-automake-Handle-LTLIBOBJS-more-specifi.patch
0003-Revert-automake-Handle-LTLIBOBJS-more-specifically.patch
0004-Revert-automake-Ensure-that-LIBOBJ_DIR-builddir-is-c.patch

i rollback now to 1.15.1 or your find a better solution

**Comment by nickersk** [comment]
i suggest to get 1.15.1 and set preferred version to it in layer.conf for now, because it will need more time to investigate, but leave this issue open, i'll try to find solution later. trying 1.16 now if that will work, only few commit left to 1.16.1 which can cause this strange issue. this is real pain as they used seq ... trying next commit.

**Comment by nickersk** [comment]
same error between 1.16 and 1.16.1

**Comment by nickersk** [comment]
issue comes from depout.m4 macro
see https://github.com/oe-alliance/oe-alliance-core/pull/327
