### ISSUE TITLE
nextp3 No manifest generated from: enigma2-3rdparty-plugins

### ISSUE THREAD

**Issue by christophecvr** [oe-alliance/oe-alliance-core#382]
It's a similar issue like the No manifest generated cortexa15hf-neon-vfpv4 allarch x86_64_x86...
Unfortunately not solvable in same way. Somehow looks that last bitbake revision used does look for ghost recipes never created even not existing. error output
"WARNING: Manifest /media/buildb/openatv-63b/build-enviroment/builds/openatv/DEV/gb7356/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-enigma2-3rdparty-plugins.package_write_ipk not found in gb7356 gbquadplus mips32el allarch x86_64_x86_64-nativesdk (variant '')?
ERROR: No manifest generated from: enigma2-3rdparty-plugins in /media/buildb/openatv-63b/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-3rdparty-plugins.bb
DEBUG: Python function do_rootfs finished
ERROR: Function failed: do_rootfs"
The sstate-control/manifest-x86_64_x86_64-nativesdk-enigma2-3rdparty-plugins.package_write_ipk  does not exist warning at first is right. The nativesdk-enigma2-3rdparty-plugins is also not existent.

Looks that the last bitbake does create a ghost package somewhere and due to that rootfs task tries to look for it i tried to find where but really could not. perhaps patching the rootfs.class task to ignore for example all lookups containing x86_64_x86_64 since that never can be right the double x86_64_x86_64 but i'm dunno how.

**Comment by christophecvr** [comment]
rootfs task is not a bbclass task on it anymore . It well a rootfs.py now curious

**Comment by christophecvr** [comment]
I well already could trace where the base triggered ERROR: No manifest generated from is located:
openembedded-core/meta/lib/oe/package_manager.py line 686 .
and the first WARNING Manifest <xxx> not found in comes from : 
openembedded-core/meta/lib/oe/sstatesig.py line 414

**Comment by nickersk** [comment]
this can be solved by replacing package write ipk noexec with deltask, but there is other problem with opkg command line (unable to remove packages) at do_rootfs. i will try build from scratch first. untill ended i found erroro comming from http://git.openembedded.org/openembedded-core/tree/meta/lib/oe/package_manager.py#n1350

**Comment by christophecvr** [comment]
I now just started build off Mutant HD51 4k see how that runs.

this can be solved by replacing package write ipk noexec with deltask
Where can we do that ?

**Comment by christophecvr** [comment]
is that the line :  1150
"create_packages_dir(self.d, self.deploy_dir, d.getVar("DEPLOY_DIR_IPK"), "package_write_ipk", filterbydependencies)"

to be replcade by : 
"create_packages_dir(self.d, self.deploy_dir, d.getVar("DEPLOY_DIR_IPK"), "deltask", filterbydependencies)  ?

**Comment by nickersk** [comment]
in enigma2-3rdparty-plugins.bb under meta-oe/recipes-oe-alliance/enigma2-plugins

replace line with noexec with deltask package_write_ipk

**Comment by christophecvr** [comment]
or in enigma2-3rdparty-plugins.bb 
replacing line 149
do_package_write_ipk[noexec] = "1"
with 
a certain deltask ?

**Comment by nickersk** [comment]
however, it might be the incorrect resolution, because deltask deletes other task dependencies noexec do not ... thats why i am testing it further now

**Comment by christophecvr** [comment]
I now also just traced the exact patch which brakes the rootfs phase and looks for a really not existent manifest manifest-x86_64_x86_64-nativesdk-  really I checked all the plugins and none of them has such a things as sdk in it. There is for sure a bug in that new procedure and starting to find other ways in our bb receipt to fetch and build the package would only be work arounds and end up with problems in future. somehow the check on nativesdk does not work and say it is a nativesdk while it's not and then it fails. commit with that bug : 
"http://git.openembedded.org/openembedded-core/commit/?id=c7c5f4065c102fde4e11d138fb0b6e25bffe0379"  package_manager/sdk: Use filtered copies of the deploy ipk/deb directories 

Somehow a lot of plugins packages are regognized as a sdk package and they are not sdk.
when using package_manager.py out of commit "http://git.openembedded.org/openembedded-core/commit/?id=dba876639b1fb8ea3ccb182c91e19966c4052115"
all runs fine again. I do have then a perfect build nextp3 image on mutant51

**Comment by christophecvr** [comment]
oeps even with the previous it does not work anymore. guess I screwed it self somewhere.
 image still not build now on other error during rootfs with remove

**Comment by nickersk** [comment]
this is the commit that causes all those errors: http://git.openembedded.org/openembedded-core/commit/meta/lib/oe/package_manager.py?id=8ffd93bdb09b0a4a84b27dafcd684c6abba392ed it tries to create locale archive but fails on something, maybe some locale? Or typo? "locale" should be "localedir"?

**Comment by christophecvr** [comment]
Well I just did build first I cloned the nextp like it is. Then I just replaced the rootfs.py,package_manager.py and sdk.py and package_manager.py out of openembedded-core/tree/meta/lib/oeqa/utils and also openembedded-core/tree/meta/classes/package.bbclass (to be shure avoid the -S option) by the one out of commit http://git.openembedded.org/openembedded-core/commit/?id=0a4e6974b49bf68c4a4098d339b5d655e202a3fd the one just before it breaks. Build in one go mutant51 ok
By the ones on commit

**Comment by nickersk** [comment]
this is where i ended up: https://github.com/oe-alliance/oe-alliance-core/pull/384
