### ISSUE TITLE
recent oe-core updates

### ISSUE THREAD

**Issue by nickersk** [oe-alliance/oe-alliance-core#391]
so, oe-core switched to openssl 1.1, we have problem with ffmpeg_3 at least, because it will fail in fact librtmp and rtmpdump are uncompilable with openssl 1.1 and therefore are conflicting openssl files installed during do_prepare_recipe_sysroot , extend_recipe_sysroot. is anybody able to patch rtmpdump and librtmp to compile against openssl 1.1 ?

**Comment by arn354** [comment]
http://git.ffmpeg.org/gitweb/rtmpdump.git/shortlog/refs/heads/master
there are a few more commits on the original repo i could merge, but i doubt that something changes related to openssl.
the original rtmpdump_2.4.bb recipe in meta-openembedded\meta-multimedia\recipes-multimedia\rtmpdump does not contain the RDEPENDS_${PN} = "librtmp" like we do in our rtmpdump.bb - does it compile if you remove the librtmp RDEPEND locally in oe-alliance rtmpdump.bb ?

**Comment by nickersk** [comment]
will try

**Comment by atvcaptain** [comment]
problem with 1.1 was all close binarys use 1.02  when this not abi stable we must rollback to 1,02, or all cams, ci+ broken

**Comment by arn354** [comment]
right, forgot about the closed binary blobs relying on openssl 1.02

**Comment by nickersk** [comment]
so we should stick with openssl10 for now. right ?

**Comment by christophecvr** [comment]
Yes I watched this issue also, Tried to change all oe-metalliance to openssl10  which is then openssl version 1.02. But problem is conflicts since the packages off openembedded are all openssl-1.1 now as a default . Guess both will need to be installed and then like they did with the still openssl-0.79 required for some softcams some compat links patches for libcrypto and libssl.

**Comment by christophecvr** [comment]
about librtmp, does someone know for what we need it. There was something about that it was required with the old version of rtmpdump, but not with the new one anymore. 
Seems it is still required.

https://github.com/GStreamer/gst-plugins-bad/tree/master/ext/rtmp

**Comment by christophecvr** [comment]
ffmpeg also does need librtmp. As far I know it is required to play iptv rtmp channels.

**Comment by christophecvr** [comment]
but source rtmpdump is avbl on oe-alliance. Not sure but could be that librtmp is present in openembedded rtmpdump.

**Comment by nickersk** [comment]
rtmpdump in meta-oe is broken with openssl 1.1. maybe it is be possible to split ffmpeg into two packages... make separate bb from bbappend.

**Comment by nickersk** [comment]
guys at oe forgot to resolve ssl headers files conflicts. thats why we are facing this...

**Comment by atvcaptain** [comment]
at the moment we build again 1.02, for oe-a 4.3 its better we dont switch to 1.1.1, we can open a new branch for test openssl 1.1.1 this need many more time, and we must request new close binary blobs, and mutant und co never send this when pli not use 1.1.1 too

**Comment by nickersk** [comment]
i agree, we need no-errors build for ssl10 at first. i wonder how can this mixing versions of recipe-sysroot ssl conflicting files be solved... after updating oe-core and build from scratch those errors disappeared by me.
