### ISSUE TITLE
Audio Problems Dinobot 4K

### ISSUE THREAD

**Issue by DennyCoy** [oe-alliance/oe-alliance-core#411]
Hello, all...

I have a problem in the Dinobot 4K box on the SD channel on the Videocon Provider ( Satelite ST2 ku-band ) with the cccam server ...
The problem is that SD videocon channels do not come out Audio when HD Audio channels are not a problem ... as a consideration I tried using the  Formuler F4 Turbo box with openATV6.2 SD channel audio and HD audio channels have no problems .... I have set oscam Dinobot 4K and equates the parameters with the Formuler F4 Turbo but it doesn't work
I use the OpenATV 6.2 image on the Dinobot 4K box ...
please give a solution ... thank you

**Comment by atvcaptain** [comment]
send record file 100 mb with https://wetransfer.com/

**Comment by DennyCoy** [comment]
Please sir ... the file record link
https://we.tl/t-Dwisu2RLSh

**Comment by atvcaptain** [comment]
ok i send the infos to dev team

**Comment by DennyCoy** [comment]
ok sir ... thank you very much for the time

**Comment by atvcaptain** [comment]
play with vlc player no audio, have you other e2 box can can make a record and check audio works and send this file too

**Comment by DennyCoy** [comment]
Ok Sir....
This is an example of a file record from the Formuler F4 Turbo box .... Audio Channel SD doesn't matter...
https://we.tl/t-bXbftlYfwM

**Comment by atvcaptain** [comment]
ok thx audio with vlc works, looks issue decrypt audio with dino
