### ISSUE TITLE
Problem PowerVu DES Zgemma H9S Asiasat 7

### ISSUE THREAD

**Issue by kenziera** [oe-alliance/oe-alliance-core#412]
hello, I have a Zgemma H9S
but there are a few problems with Powervu on some  Asiasat 7 channels like Cartoon Network, Boomerang, TNZ .

indicated the channel uses the Powervu DES type, please added to the next update to be able to support PowerVu DES for Zgemma H9S, I use the OpenATV Image

thank you for the attention

**Comment by kenziera** [comment]
Hello, ?

**Comment by atvcaptain** [comment]
info from zgemma it works

**Comment by atvcaptain** [comment]
read the info: https://mega.nz/#!ojJmWC6a!TKzxuTR1CnsxbxJX50kqVmzUDeWsADXCpD8RKcLKOZ0
