### ISSUE TITLE
Zgemma H2 does not  Support Full HD Skin

### ISSUE THREAD

**Issue by kenziera** [oe-alliance/oe-alliance-core#418]
Hello everyone, I have Zgemma H2 with the OpenATV image, but my STB doesn't support FullHD Skin

thank you

**Comment by kenziera** [comment]
Hello everyone, I have Zgemma H2 with the OpenATV image, but my STB doesn't support FullHD Skin

thank you

**Comment by BliNeR-KeY** [comment]
hello H2 is old box .  (old issue in FHD skin)
and is not OE-A issue..
more info you can ask https://github.com/zgemma-star

**Comment by kenziera** [comment]
Thanks Bro...

**Comment by atvcaptain** [comment]
box to slow for fhd skin , not enable in the drivers no issue
