### ISSUE TITLE
sf4008 openatv image can not save video setting

### ISSUE THREAD

**Issue by opfans** [oe-alliance/oe-alliance-core#419]
My receiver is Octagon SF4008,and i use the image of openatv for months.i find a question on the openatv image. i watch  4:3 aspect ratio program ,and  set the video stretch then press green key to  save the setting ,it makes picture expand to fit my screen ,but the video setting can not really save.when i reboot my receiver,4:3 aspect ratio programs have black horizontal bars.what should i do  to fix the problem.

**Comment by arn354** [comment]
ask in forum
