### ISSUE TITLE
 Zgemma H9S Cannot Open Encryption Of Powervu DES

### ISSUE THREAD

**Issue by DennyCoy** [oe-alliance/oe-alliance-core#420]
Dear All....

Please help with the zgemma H9S Enigma2 box, which cannot open powervu DES encryption.
Error Example:
(dvbapi) ERROR: ioctl(CA_SET_DESCR): Invalid argument. 

Maybe it needs an update DRIVER. I use the openATV 6.2 image
for reference I include attachments
thank you
![report powervu des](https://user-images.githubusercontent.com/38503683/48558507-02cac780-e91c-11e8-8feb-44e3f4b882b2.png)
![report des 1](https://user-images.githubusercontent.com/38503683/48558518-09593f00-e91c-11e8-8c77-95fa182e48fd.png)

![1_0_1_51_1_1_3941018_0_0_0_20181115204832](https://user-images.githubusercontent.com/38503683/48559073-6e616480-e91d-11e8-9695-1337877b7cff.jpg)
![1_0_1_51_1_1_3941018_0_0_0_20181115204946](https://user-images.githubusercontent.com/38503683/48559092-76b99f80-e91d-11e8-8320-c1df5fa5070d.jpg)
![1_0_19_2_7_3a_3700000_0_0_0_20181115212610](https://user-images.githubusercontent.com/38503683/48559106-7f11da80-e91d-11e8-964c-5c11b917fb04.jpg)

**Comment by GigaBlue-STB** [comment]
See #412

**Comment by DennyCoy** [comment]
Not Work Sir....
I tried a few oscam parameters but the channel is still dark...
for channels with powervu CSA encryption it doesn't have a problem ... but some channels with powervu DES encryption don't work...
I used to have the same problem with the Formuler F4 Turbo box, it can't open PowerVu DES ... the problem is solved by updating the driver ...
could a case like this be the same...
thank you..
![screenshot_1](https://user-images.githubusercontent.com/38503683/48638464-4d733f00-ea03-11e8-8fda-636df38a5916.png)
![screenshot_2](https://user-images.githubusercontent.com/38503683/48638474-519f5c80-ea03-11e8-941c-d70c2d6cd11f.png)
![screenshot_3](https://user-images.githubusercontent.com/38503683/48638479-5532e380-ea03-11e8-8778-019abea5b742.png)
