### ISSUE TITLE
Zgemma H9S Cannot Open Encryption Of Powervu DES 

### ISSUE THREAD

**Issue by DennyCoy** [oe-alliance/oe-alliance-core#421]
Referring to issue #420 powervu DES encryption still does not work... 
I tried a few oscam parameters but the channel is still dark...
for channels with powervu CSA encryption it doesn't have a problem ... but some channels with powervu DES encryption don't work...
I used to have the same problem with the Formuler F4 Turbo box, it can't open PowerVu DES ... the problem is solved by updating the driver ...
could a case like this be the same...
thank you..

**Comment by DennyCoy** [comment]
Hello...

**Comment by arn354** [comment]
We can't update a driver if a manufacturer does not deliver it. Please ask the manufacturer.

**Comment by DennyCoy** [comment]
Ok sir ... thank you ... I tried asking the manufacturer

**Comment by nautilus7** [comment]
@arn354 wouldn't be easier for you as image developers (than each independent user) to put pressure to the manufacturer and ask for new drivers??? The manufacturer provides you with the divers after all...

And maybe you could explain them why delivering such features like the one asked here, is good for their sales numbers.

**Comment by arn354** [comment]
I only have contact to GigaBlue.

**Comment by atvcaptain** [comment]
we have allready send this info to driver team, driver team say all ok

**Comment by DennyCoy** [comment]
thanks for the attention sir ... for powervu des while i use stream relay ...
