### ISSUE TITLE
Xtrend blindscan sources have gone away...

### ISSUE THREAD

**Issue by original-birdman** [oe-alliance/oe-alliance-core#423]
The `*.bb` recipes under `oe-alliance/meta-oe-alliance/meta-brands/meta-xtrend/recipes-blindscan` all have `SRC_URI`s located at http://www.et-view.com/.

However, if you go to that web-site it reports, "This domain name expired on 2018-11-12 06:32:32" and any attempt to download the zip files just produces an HTML page reporting an error.

So you can't run a fresh build at the moment.

**Comment by xtrendmaster** [comment]
I have no more contacts with Xtrend team but I have a backup of the files.
I will try to sort this out asap

**Comment by Huevos** [comment]
Birdman, what is the name of the file you are searching for?

**Comment by atvcaptain** [comment]
fixed
