### ISSUE TITLE
Merge openPLi it913x patch for vuplus 3.3.8 images

### ISSUE THREAD

**Issue by macnuts** [oe-alliance/oe-alliance-core#43]
Hello,

Please merge the commit http://sourceforge.net/p/openpli/openpli-oe-core/ci/8edb4dca48b0246b87b515d6014df9006bce0413/

This one is needed by some it913x usb tuners. Otherwise, they stop to work after a few minutes / seconds.

BR/macnuts

**Comment by andyblac** [comment]
thanks

**Comment by a4tech** [comment]
Andy, please merge it as well for INI-HDp kernel, it is same.

Thanks

**Comment by andyblac** [comment]
done

**Comment by macnuts** [comment]
Thank you. That was quick!
