### ISSUE TITLE
vu duo 4k  s2x do not supppot multistream and kodi17 crash .

### ISSUE THREAD

**Issue by opfans** [oe-alliance/oe-alliance-core#437]
I have vu duo 4k box and use openatv 6.3 image.I show the issus that the FBC S2X tuner can not support multistream,so can not input PLS code.I wonder when  this box  will support  multistream.Another issus that       when start kodi app  ,this app crash.Kodi app can not run openatv 6.3 image.will it fix?

**Comment by opfans** [comment]
I know octagon sf4008 have S2X tuner ,it can support multistream.But ,vu duo 4k can not.

**Comment by atvcaptain** [comment]
vu dont support multistream with fbc tuner, only vu zero 4k support it no other vu box
and kodi with atv 6.3 we cant fixit vu stop kodi support

**Comment by opfans** [comment]
> vu dont support multistream with fbc tuner, only vu zero 4k support it no other vu box
> and kodi with atv 6.3 we cant fixit vu stop kodi support

thanks for your reply
