### ISSUE TITLE
dm900,dm920 can not support AVS stream

### ISSUE THREAD

**Issue by opfans** [oe-alliance/oe-alliance-core#439]
Dreambox receivers,the model dm900,dm920 with openatv 6.3 image  can not support AVS stream.  THE stream of services on 125E SAT used AVS (AVS is a video compression standard in china).I wonder about  whether DM900 DM920 would support avs stream in future.I know that vu uno 4k box has the same cpu  chip bcm7252s  as dm920.vu uno 4k box can support avs stream,but dm920 cant.I dont know why .Can openatv team ask for new driver from dreambox manufacture to fix this issues.if fixed ,it will make a lot of people much happy.

**Comment by atvcaptain** [comment]
we have ask for very long time, infos was dream not sales boxes in china so the features not enable
buy other boxes with support
