### ISSUE TITLE
[vuplus] linux 3.15.5 dvb support broken please revert latest patches

### ISSUE THREAD

**Issue by p1ngb4ck** [oe-alliance/oe-alliance-core#454]
Please do not easily merge significant kernel config changes like this.
The analog tv support removal leads to em28xx not being built, rendering multiple adapters non-working.
Please revert the patches to defconfig and defconfig_proxy (no sense in rendering multiple adapters broken, to make 1 work). thanks

**Comment by dpeddi** [comment]
I've in my to-do... Will check

it seems that em28xx-dvb was missing in vuzero4k and vuuno4kse... added...

**Comment by p1ngb4ck** [comment]
no. the problem was NOT em28xx-dvb. Problem ist : EM28xx is an analog/digital combo-chip. It will not build generally if ANALOG_TV_SUPPORT is completely disabled. Which it is since the last contributed patch - the provider of that file probably was just unaware of that. So, to have em28xx at all, ANALOG_TV_SUPPORT *must not* be disabled

**Comment by p1ngb4ck** [comment]
also, maybe s.o. could take a look at the delock69959 ebuild that I provided once ? Based on EM28xx, works out of the box by adding correct tuner and firmware as well as a simple module config file. Should be easy to merge & activate, I could then finally remove my private own custom image builder on my server. I actually use that device, and it is my only dvb-c adapter..
