### ISSUE TITLE
wget and opkg install issues Nextp3 branch

### ISSUE THREAD

**Issue by davesayers2014** [oe-alliance/oe-alliance-core#458]
Hi I have been having certificate issues with OpenATV 6.3 as reported here https://www.opena.tv/english-section/45237-wget-changes-openatv-6-3-a.html

To get around this I have used --no-check-certificate to download files.

Sadly this doesn't get around opkg install from websites ie  opkg install --force-reinstall "https://github.com/su1s/e2m3u2bouquet/releases/download/v0.8.2/enigma2-plugin-extensions-e2m3u2bouquet_0.8.2_all.ipk"

I tried adding --no-check-certificate to opkg install but it complains that command doesnt exist.

**Comment by davesayers2014** [comment]
Ok only way ive got round this is via downloading a .wgetrc within this I have check_certificate = off https://raw.githubusercontent.com/davesayers2014/e2m3ubouquet/master/files/.wgetrc

So I can use --no-check-certificate to download .wgetrc then I can install ipk,s without issues.

`wget -O /home/root/.wgetrc --no-check-certificate "https://raw.githubusercontent.com/davesayers2014/e2m3ubouquet/master/files/.wgetrc" && chmod +x .wgetrc && opkg install --force-reinstall "https://github.com/su1s/e2m3u2bouquet/releases/download/v0.8.2/enigma2-plugin-extensions-e2m3u2bouquet_0.8.2_all.ipk`

Or just use curl

It would be better if these wget changes was sorted though.

**Comment by davesayers2014** [comment]
I'll close this issue as it's not been looked at, I have the above solution other users will need to work it out. Thanks for the help

**Comment by davesayers2014** [comment]
New log reported by s3n0

https://www.opena.tv/english-section/45237-wget-changes-openatv-6-3-a-post388987.html#post388987

**Comment by nickersk** [comment]
i will take a look @ this

**Comment by nickersk** [comment]
i think we are dealing with update-ca-certificates script problem, because since openssl 1.1 it is using 'openssl rehash' command, which is not available in openssl 1.0. so it fails to rehash certs during do_rootfs ....

**Comment by Schimmelreiter** [comment]
Sounds plausible to me.

**Comment by nickersk** [comment]
please see and test https://github.com/oe-alliance/oe-alliance-core/commit/c2ed92a72dd1097b655309e6d4061de21e7015b3
 p.s. this issue should not appear in nextp3-ssl111 because it is complete openssl 1.1.1 positive :-)

**Comment by davesayers2014** [comment]
Thanks I'll test on next nightly OpenATV 6.3 release or is there a way to add this to current image?

**Comment by nickersk** [comment]
you can try to build and reinstall openssl and ca-certificates pkgs

**Comment by nickersk** [comment]
6.3 beta images are built from 4.3 branch afaik, so this solution has to be tested in nextp3 and backported to  4.3 branch later if needed.

**Comment by davesayers2014** [comment]
Sorry I dont know how to buiild image and I thought OpenATV 6.3 was build fro oe core Nextp3 branch. It must have changed from Nextp3 to 4.3 at some point.

If someone wants to test this they can try by opkg install any plugin from third party feeds github and wget tmp any file on github.

**Comment by nickersk** [comment]
no more error reports, so closing this issue.

**Comment by davesayers2014** [comment]
So has this been implemented to oe 4.3 branch? https://github.com/oe-alliance/oe-alliance-core/pull/472

I opened this issue report thinking OpenATV 6.3 was built on Nextp3 branch as I'm sure it originally was but it might have changed at some point. Thanks.

**Comment by nickersk** [comment]
yes, 4 days ago.
pls see https://github.com/oe-alliance/oe-alliance-core/commit/7806bd74cf8932dadc3b1bf549d43421e62f096f

**Comment by davesayers2014** [comment]
Thanks I've just tested by flashing latest OpenATV 6.3 using openmultiboot and used opkg install and wget from github and had no certificate issues. Thank you for the fix.
