### ISSUE TITLE
branch for testing with openssl 1.1.1

### ISSUE THREAD

**Issue by nickersk** [oe-alliance/oe-alliance-core#469]
would it be possible to create nextp3 branch for testing openssl-1.1.1 ? 
for example nexpt3-ssl111 or so ?
thx ...

**Comment by atvcaptain** [comment]
sure np we can create a new branch for this big change

**Comment by nickersk** [comment]
ok, so pls create it 👍

**Comment by nickersk** [comment]
thx for invite, pushed it already...
