### ISSUE TITLE
Zgemma H7s CPU temperature

### ISSUE THREAD

**Issue by Marchella1983** [oe-alliance/oe-alliance-core#487]
hi, please if possible add the ability to output the CPU temperature
`root@h7:~# cat /sys/devices/virtual/thermal/thermal_zone0/temp
cat: read error: Invalid argument
root@h7:~#`

on ET 11000 this works with Broadcom BCM7251S
`root@et1x000:~# cat /sys/devices/virtual/thermal/thermal_zone0/temp
55017
root@et1x000:~#`

**Comment by atvcaptain** [comment]
driver team have remove on request from sales shops , user read box to hot  and send box back

**Comment by Marchella1983** [comment]
Captain I don't understand You very well... Does that mean it won't happen?

**Comment by koivo** [comment]
This was a request from shops. They want to have this feature.
Too many users has send back the boxes to shops.

**Comment by Marchella1983** [comment]
Yes but why remove when the Broadcom chip BCM7251S is able to do, I also heated the chip but I made myself so
![1554615583658803448624](https://user-images.githubusercontent.com/28537448/55692705-e4955f00-59c3-11e9-82ea-c3abcb65f8ee.jpg)


and I want to have a temperature output room `cat /sys/devices/virtual/thermal/thermal_zone0/temp`

this is complete nonsense, I also heated the CPU and now also to give your box to the seller?  
**Captain** I beg you talk with the producer let return this feature...

**Comment by jenseneverest** [comment]
am i correct that it would be possible if i were to edit the defconfig ?? For a home build.....

**Comment by atvcaptain** [comment]
bcm driver must enable this, without we get no infos from the sensor, and driver team have removed this on request from sales

**Comment by Marchella1983** [comment]
**atvcaptain** can then please give the contact details of the driver team?

**Comment by atvcaptain** [comment]
send mail to zgemma

**Comment by Marchella1983** [comment]
thanks, I tried to do that, but they're not answering...

**Comment by opfans** [comment]
i have the  H7S box .it works very OK in the ari-condition room.

**Comment by Marchella1983** [comment]
I just ask you to add output with the command

I have now at room temperature 24 degrees Zgemma H7s is gaining almost 60 degrees ...

and what will happen when we have summer heat in Uzbekistan reaches 60 degrees of heat ...

write again just add a conclusion
`cat /sys/devices/virtual/thermal/thermal_zone0/temp`
what can Broadcom chip BCM7251S

**Comment by opfans** [comment]
> I just ask you to add output with the command
> 
> I have now at room temperature 24 degrees Zgemma H7s is gaining almost 60 degrees ...
> 
> and what will happen when we have summer heat in Uzbekistan reaches 60 degrees of heat ...
> 
> write again just add a conclusion
> `cat /sys/devices/virtual/thermal/thermal_zone0/temp`
> what can Broadcom chip BCM7251S

Can people  live with 60 degrees?do not worry ,i have tested h7s worked OK in the room with temperature 60 degrees for 2 months.if you care the high temperature ,install air conditioning equipment.i feel very hot with 38 degrees in china.

**Comment by Marchella1983** [comment]
> Can people live with 60 degrees?do not worry ,i have tested h7s worked OK in the room with temperature 60 degrees for 2 months.if you care the high temperature ,install air conditioning equipment.i feel very hot with 38 degrees in china.

You misunderstand me!!!  I only ask to add that Broadcom chip BCM7251S CAN, and it is a conclusion cat /sys/devices/virtual/thermal/thermal_zone0/temp...  here on Zgemma H9 Combo it displays...
![1_0_1_5DF_15_56_3520000_0_0_0_20190416203017](https://user-images.githubusercontent.com/28537448/56223147-a6b0ce80-6086-11e9-86e2-9d65fa7cb4df.jpg)
