### ISSUE TITLE
add-gstplayer-support not work !

### ISSUE THREAD

**Issue by thawtes** [oe-alliance/oe-alliance-core#491]
hello,
kodi add-gstplayer-support.patch work openATV 6.2 but not work openATV 6.3
 pls fix thanks...
device: VU+ DUO2

**Comment by thawtes** [comment]
init 4
kodi

explore videos on kodi and select video press long OK button > select Play using.. >GstPlayer
result
exit kodi back to pluginlist screen

**Comment by atvcaptain** [comment]
ok we remove the patch thx for the info

**Comment by thawtes** [comment]
> 
> 
> ok we remove the patch thx for the info

this is a very nice feature and works very nicely with 4.2 branch build.
can't you make it work with 4.3 branch build instead of removing this patch?

**Comment by 68foxboris** [comment]
Not work gstplayer on kodi,what can be done?
root@et1x000:~# init 4
root@et1x000:~# kodi
Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.
Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.
ERROR: Exception caught on main loop. Exiting
CGstPlayerVideo::handleMessage: Message STATE_CHANGED
CGstPlayerVideo::handleMessage: Element streamsynchronizer0 changed state from NULL to READY.
CGstPlayerVideo::handleMessage: Message STATE_CHANGED
CGstPlayerVideo::handleMessage: Element playsink changed state from NULL to READY.
CGstPlayerVideo::handleMessage: Message STATE_CHANGED
CGstPlayerVideo::handleMessage: Element playbin changed state from NULL to READY.
CGstPlayerVideo::handleMessage: Message STATE_CHANGED
CGstPlayerVideo::handleMessage: Element streamsynchronizer0 changed state from READY to PAUSED.
CGstPlayerVideo::handleMessage: Message STATE_CHANGED
CGstPlayerVideo::handleMessage: Element uridecodebin0 changed state from NULL to READY.
CGstPlayerVideo::handleMessage: Message STATE_CHANGED
CGstPlayerVideo::handleMessage: Element typefindelement0 changed state from NULL to READY.
CGstPlayerVideo::handleMessage: Message STATE_CHANGED
CGstPlayerVideo::handleMessage: Element typefindelement0 changed state from READY to PAUSED.
CGstPlayerVideo::handleMessage: Message STATE_CHANGED
CGstPlayerVideo::handleMessage: Element source changed state from NULL to READY.
CGstPlayerVideo::handleMessage: 0x92579b88A
/usr/bin/kodi: line 195: 29554 Segmentation fault      "$LIBDIR/${bin_name}/${bin_name}.bin" $SAVED_ARGS
[kodi.zip](https://github.com/oe-alliance/oe-alliance-core/files/3356143/kodi.zip)

**Comment by thawtes** [comment]
> 
> 
> Not work gstplayer on kodi,what can be done?
> root@et1x000:~# init 4 root@et1x000:~# kodi
> Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.
> Warning: MHD_USE_THREAD_PER_CONNECTION must be used only with MHD_USE_INTERNAL_POLLING_THREAD. Flag MHD_USE_INTERNAL_POLLING_THREAD was added. Consider setting MHD_USE_INTERNAL_POLLING_THREAD explicitly.
> ERROR: Exception caught on main loop. Exiting
> CGstPlayerVideo::handleMessage: Message STATE_CHANGED
> CGstPlayerVideo::handleMessage: Element streamsynchronizer0 changed state from NULL to READY.
> CGstPlayerVideo::handleMessage: Message STATE_CHANGED
> CGstPlayerVideo::handleMessage: Element playsink changed state from NULL to READY.
> CGstPlayerVideo::handleMessage: Message STATE_CHANGED
> CGstPlayerVideo::handleMessage: Element playbin changed state from NULL to READY.
> CGstPlayerVideo::handleMessage: Message STATE_CHANGED
> CGstPlayerVideo::handleMessage: Element streamsynchronizer0 changed state from READY to PAUSED.
> CGstPlayerVideo::handleMessage: Message STATE_CHANGED
> CGstPlayerVideo::handleMessage: Element uridecodebin0 changed state from NULL to READY.
> CGstPlayerVideo::handleMessage: Message STATE_CHANGED
> CGstPlayerVideo::handleMessage: Element typefindelement0 changed state from NULL to READY.
> CGstPlayerVideo::handleMessage: Message STATE_CHANGED
> CGstPlayerVideo::handleMessage: Element typefindelement0 changed state from READY to PAUSED.
> CGstPlayerVideo::handleMessage: Message STATE_CHANGED
> CGstPlayerVideo::handleMessage: Element source changed state from NULL to READY.
> CGstPlayerVideo::handleMessage: 0x92579b88�A
> /usr/bin/kodi: line 195: 29554 Segmentation fault "$LIBDIR/${bin_name}/${bin_name}.bin" $SAVED_ARGS
> [kodi.zip](https://github.com/oe-alliance/oe-alliance-core/files/3356143/kodi.zip)

work on openATV 6.2

**Comment by 68foxboris** [comment]
This and I know but how to make it work on 6.3?
