### ISSUE TITLE
Zgemma H9 Combo and Ci info

### ISSUE THREAD

**Issue by Marchella1983** [oe-alliance/oe-alliance-core#496]
Please tell me where does CommonInterfaceAssignment draw this information, image or driver?
```
no module found
init modules
```

**Comment by atvcaptain** [comment]
we have report this, its driver

**Comment by Marchella1983** [comment]
Hi @Captain I have already reported this, but the manufacturer writes the opposite
https://github.com/zgemma-star/meta-zgemma/issues/46

**Comment by atvcaptain** [comment]
i speak when insert one modul  in the box and not working

**Comment by Marchella1983** [comment]
now I haven’t inserted a module, and in CommonInterfaceAssignment the initialization is constantly going on
![1_0_1_57A_14_1_3522E18_0_0_0_20190501184053](https://user-images.githubusercontent.com/28537448/57019748-ccba9f00-6c40-11e9-915f-ad868123cba6.jpg)
and why he shows two slots and not one

**Comment by atvcaptain** [comment]
the comes from driver report two ci slots, but possible add e2 hack to hite one

**Comment by Marchella1983** [comment]
there is one Ci slot on the H9 Combo and it will be correct if it outputs one slot and not two, please check this error

**Comment by Marchella1983** [comment]
one more request, it can somehow be fixed
root@zgemmah9combo:~# cat /proc/bus/nim_sockets
NIM Socket 0:
        Type: DVB-T2
        Name: Si2168
        Has_Outputs: no
        Frontend_Device: 0
        I2C_Device: 0
        Supports_Blind_Scan: yes
NIM Socket 1:
        Type: DVB-S2X
        Name: Si2166D
        Has_Outputs: no
        Frontend_Device: 1
        I2C_Device: 0
        Supports_Blind_Scan: yes
root@zgemmah9combo:~# 

I wanted to see it like that
NIM Socket 0:
        Type: DVB-S2X
        Name: Si2166D
        Has_Outputs: no
        Frontend_Device: 1
        I2C_Device: 0
        Supports_Blind_Scan: yes
NIM Socket 1:
        Type: DVB-T2
        Name: Si2168
        Has_Outputs: no
        Frontend_Device: 0
        I2C_Device: 0
        Supports_Blind_Scan: yes

**Comment by atvcaptain** [comment]
![Unbenannt](https://user-images.githubusercontent.com/974786/57020854-f10b8100-6c2a-11e9-9665-d08c23415517.PNG)

better :)

**Comment by Marchella1983** [comment]
@atvcaptain fine, super ...

**Comment by atvcaptain** [comment]
tuner sort order is not a issue, you like dvb-s first other user like dvb-c first  and so on, the output comes from the hardware and internel i2c bus slot, we dont add a e2 hack

**Comment by Marchella1983** [comment]
hello, if you can then edit here
![1_0_16_DCB9_235_70_2300000_0_0_0_20190502070746](https://user-images.githubusercontent.com/28537448/57053750-6c137c80-6ca9-11e9-9add-25f3acccf8d5.jpg)
![1_0_16_DCB9_235_70_2300000_0_0_0_20190502070809](https://user-images.githubusercontent.com/28537448/57053758-733a8a80-6ca9-11e9-951a-bf8526ce6423.jpg)

**Comment by atvcaptain** [comment]
ok fix include

**Comment by Marchella1983** [comment]
> we have report this, its driver

**Captain** Hello, please tell me what has been fixed in the new version of the H9 Combo driver?

I do not see that this problem is fixed with the constant initialization of the module even if it is not inserted in the Ci slot ...
![1_0_1_15_19_1_EEEE0000_0_0_0_20190516165415](https://user-images.githubusercontent.com/28537448/57851860-125b9800-77fb-11e9-9560-6046e4206f43.jpg)

**Comment by atvcaptain** [comment]
no problem here now works with german moduls

**Comment by Marchella1983** [comment]
If there is no module> no module found

and here always> init module

**Comment by atvcaptain** [comment]
old driver working ?

**Comment by Marchella1983** [comment]
not

**Comment by Marchella1983** [comment]
inserted a module
![1_0_1_13_19_1_EEEE0000_0_0_0_20190517152706](https://user-images.githubusercontent.com/28537448/57921952-041f8180-78b8-11e9-81b6-aa5811d7cdb0.jpg)

removed the module
![1_0_1_13_19_1_EEEE0000_0_0_0_20190517152757](https://user-images.githubusercontent.com/28537448/57921995-20bbb980-78b8-11e9-854a-9d624690e947.jpg)

create restart gui and again module init
![1_0_1_13_19_1_EEEE0000_0_0_0_20190517153005](https://user-images.githubusercontent.com/28537448/57922116-6c6e6300-78b8-11e9-9fee-c40cb1d48007.jpg)

**Comment by Marchella1983** [comment]
set Open Pli 7.1 rc and everything works correctly there
![1_0_1_261_C_1_3522F80_0_0_0_20190517174140](https://user-images.githubusercontent.com/28537448/57928825-28d12480-78cb-11e9-8add-d1cb3d9cf721.jpg)
![1_0_1_261_C_1_3522F80_0_0_0_20190517174156](https://user-images.githubusercontent.com/28537448/57928842-2ec70580-78cb-11e9-9483-119243d25ebb.jpg)

**Comment by atvcaptain** [comment]
use pli

**Comment by Marchella1983** [comment]
an excellent approach will get rid of the problem that exists and must be corrected...

for me, better atv I don't see a better image ...

**Comment by atvcaptain** [comment]
![ci-ok](https://user-images.githubusercontent.com/974786/57936035-5c0fb580-78c3-11e9-86dd-3bf897a6b7a1.PNG)

ci+ 1.3 all fine

**Comment by atvcaptain** [comment]
ac modul too

![ac-ok](https://user-images.githubusercontent.com/974786/57936257-d2acb300-78c3-11e9-94ab-40d4a17e52c7.PNG)

**Comment by Marchella1983** [comment]
Why do you insert the module?

I'm talking about the fact that even without a module in CommonInterfaceAssignment constantly writes the **init module** instead of **no module found**

https://github.com/oe-alliance/oe-alliance-core/issues/496#issuecomment-493406048

**Comment by atvcaptain** [comment]
i understand no modul found

**Comment by atvcaptain** [comment]
i start box without modul

![no](https://user-images.githubusercontent.com/974786/57936874-0f2cde80-78c5-11e9-8ee6-793cf20583dd.PNG)

for me looks all ok

**Comment by Marchella1983** [comment]
Captain look, this is a screen without a module on the ATV
![1_0_1_13_19_1_EEEE0000_0_0_0_20190517153005](https://user-images.githubusercontent.com/28537448/57937162-d26de100-78de-11e9-85c3-a1be0511b704.jpg)




and this with openpli
![1_0_1_261_C_1_3522F80_0_0_0_20190517174140](https://user-images.githubusercontent.com/28537448/57936957-62f7f180-78de-11e9-8236-b54c4a5c8118.jpg)

**Comment by Marchella1983** [comment]
> for me looks all ok

Now do a restart of the gui and see what the information will be?

**Comment by atvcaptain** [comment]
i see no problem here, i dont understand you what you mean

**Comment by Marchella1983** [comment]
> i start box without modul
> 
> ![no](https://user-images.githubusercontent.com/974786/57936874-0f2cde80-78c5-11e9-8ee6-793cf20583dd.PNG)
> 
> for me looks all ok

make a rectart Gui H9 Combo without a module and show the screen

**Comment by atvcaptain** [comment]
for me ci works  https://youtu.be/5wy4wqeK0O0

**Comment by Marchella1983** [comment]
yes you have no problems but you have ATV_6.3 I have 6.2
![1_0_1_580_14_1_3522E18_0_0_0_20190517201917](https://user-images.githubusercontent.com/28537448/57938304-5f199e80-78e1-11e9-9623-83bb5352f4a5.jpg)

**Comment by arn354** [comment]
then install 6.3 and check again - clean install, default skin.
there are no more changes to 6.2 enigma2 foreseen.

**Comment by Marchella1983** [comment]
thanks, now everything has become clear, installed 6.3 and there are no more problems ...

once again, please apologize for your perseverance and your time spent on me ...

**Comment by atvcaptain** [comment]
6.2 goes soon not for all to eol

**Comment by Marchella1983** [comment]
Hello, Captain, again problems after yesterday's update
![1_0_1_57A_14_1_3522E18_0_0_0_20190526062656](https://user-images.githubusercontent.com/28537448/58376229-5c711600-7f7f-11e9-92e9-ac87fcca22db.jpg)

**Comment by zgemma-star** [comment]
> 
> 
> ok fix include

The H9Twin has two CI and the reports from customers it seems Openatv only one shown one CI.

**Comment by Marchella1983** [comment]
**@zgemma-star** Can I ask them to show a screenshot with two modules inserted in the Ci slot?
