### ISSUE TITLE
OpenSPA 7.4 missing plugin ?

### ISSUE THREAD

**Issue by Ormiwhite** [oe-alliance/oe-alliance-core#513]
with last build of openSPA 7.4 there is no OPENSPA CAMD Manager.  ?
no with image and no in feed
no way to get EMU working ...

**Comment by arn354** [comment]
you should check and ask in their forums https://openspa.info

**Comment by Ormiwhite** [comment]
i don't get solution,
 the issue has been solved with this : https://github.com/Taapat/enigma2-plugin-alternativesoftcammanager
