### ISSUE TITLE
libbluray git url changed

### ISSUE THREAD

**Issue by ei4kn** [oe-alliance/oe-alliance-core#514]
The videolan git url has changed for libbluray. Can this be updated please?

**Comment by AbuBaniaz** [comment]
Yes it can. If you have it, can you post the new one please?

**Comment by nickersk** [comment]
looks like it was temp issue. fetching ok here, now

**Comment by ei4kn** [comment]
Yes the problem seems to be gone now.  Image is almost built. Thanks guys.
