### ISSUE TITLE
[security] Insecure system defaults: root has empty password

### ISSUE THREAD

**Issue by drwetter** [oe-alliance/oe-alliance-core#517]
An attacker can own (=take over) the machine from the local network. ssh root@<IPADDRESS> or telnet` as root`` gives one complete access. 

This is IMO a huge security problem either in the LAN or if somewhere else exposed. 

Also at least telnet and vsftp are affected.

See also  https://github.com/openatv/enigma2/issues/1361

**Comment by opfans** [comment]
you can set a root password youself.

**Comment by drwetter** [comment]
Please read again the title and then consult https://en.wikipedia.org/wiki/Secure_by_default.

**Comment by drwetter** [comment]
You guys may also want to read https://en.wikipedia.org/wiki/Mirai_(malware)

**Comment by Schimmelreiter** [comment]
https://github.com/oe-alliance/oe-alliance-core/commit/2408e713a25a0b4b43890af5d29a47939c4bfb7d

**Comment by atvcaptain** [comment]
yes we know about this, but less helping hands, so all need very long
in the next image user must set a password to have access remote to the box its on the todo list

**Comment by TwolDE2** [comment]
Is there any way of reverting to a null (blank) password as in previous versions?

**Comment by AbuBaniaz** [comment]
4.4 branch requires a password for FTP. This can be set by telnet/SSH or in the Network/Password menu.

 Is it OK to close this issue now?
