### ISSUE TITLE
[security]: Insecure system defaults: too many ports open per default

### ISSUE THREAD

**Issue by drwetter** [oe-alliance/oe-alliance-core#518]
Just got my new piece of hardware which I upgraded to openatv 6.3.

Just as usual with new devices I scanned the machine on my network, and I was scared by the utterly relaxed default network: configuration:

![63106794-28503480-bf73-11e9-95ed-1cb84af59aca](https://user-images.githubusercontent.com/8036727/63415239-f44e9680-c3ec-11e9-8b2c-9d3addda32c3.png)

Ports >30k seem to to RPC / NFS related.

See also #517 and https://github.com/openatv/enigma2/issues/1361

**Comment by nickersk** [comment]
are you planning to give it public ip ? lol

**Comment by atvcaptain** [comment]
check new branch 5.0 or 5.1 images
