### ISSUE TITLE
Crash selecting any language other than German or English on receivers with small flash

### ISSUE THREAD

**Issue by ViX-Sicilian** [oe-alliance/oe-alliance-core#530]
Why have Languages been removed for small flash receivers? Leaving only English US, UK and German?

This causes a crash with OpenViX due to the languages now missing. How can this be corrected?

OpenATV have removed languages, but there are many users that use other languages.

**Comment by TwolDE2** [comment]
More difficult, but it would be better to pick up the "small flash" situation in Language.py (BoxBranding??) and as an option, delete languages after selection

**Comment by arn354** [comment]
Q: Why have Languages been removed for small flash receivers? 
A: 
1 Because the image is no longer flashable, if the image size is not reduced. (CFE issue)
2 Because the image is no longer usable, if rootfs is full 99%. (Box Flashsize issue)
3 Over the years with every update of openembedded etc. imagesize grows and grows. A lot of additional tools, drivers etc. already got removed from default installation. So there are not much choices anymore to reduce image size.

So you could either prevent the crash in Enigma2 adapting Language-Selection or you could exclude openvix for the change in meta-local - but then you have to fix the image size for the boxes in question - one by one or no longer build them.

**Comment by arn354** [comment]
In short - time will come to drop support for smallflash boxes and boxes with CFE issue in future OE-A versions.

**Comment by RobvanderDoes** [comment]
But surely a 0.5GB flash box like the ET8000 isn't a 'small flash' box.

**Comment by arn354** [comment]
but thats a box with CFE limit - try to flash a image with rootfs size of 120MB for example..... so hen and egg...

**Comment by RobvanderDoes** [comment]
I don't have an image that big.
But I do have a crash thanks to missing system files.

**Comment by atvcaptain** [comment]
add for vix only all, or fix the e2 crash atv dont crash

**Comment by arn354** [comment]
then correct it - the way you prefer it, for every box you build.
Simply create a backup on a et8000  - you are not able to flash it via usb - only via Flashonline. At least the downloadable images need to be flashable via usb to recover your box.

**Comment by original-birdman** [comment]
> So you could either prevent the crash in Enigma2 adapting Language-Selection or you could exclude openvix for the change in meta-local - but then you have to fix the image size for the boxes in question - one by one or no longer build them.

Or you could make the additional languages installable packages.

**Comment by TwolDE2** [comment]
Guys this is a user issue - people have paid money for the hardware and expect to be able to install their local language - the change is a good idea thats trying to fix a real issue, but you cannot deliver an image where a user cannot install their language - if you really don‘t agree then delete German language from the list and see how you handle that situation.

**Comment by atvcaptain** [comment]
??  the change is old   https://github.com/oe-alliance/oe-alliance-core/commit/f7e7f8dcb878b0e9e0fbfc12ee7d13edeaaa6e8f#diff-eb5dd480e1d22d5068c09c2b273803f2

i have change it for  12 months , user can load missing language from feed not big problem,

**Comment by TwolDE2** [comment]
Great! Where in feeds do you download this?

**Comment by TwolDE2** [comment]
....... and obviously I can do this in the initial setup?

**Comment by arn354** [comment]
just look into enigma2 of openatv - yes.
e.g. one part : https://github.com/openatv/enigma2/commit/0978f6475050a02714d05d00f4bf8b611ceee292#diff-95ad66c1e9f7cd7c5f4da100d617c264

**Comment by TwolDE2** [comment]
OK - thanks - appreciate the feedback
