### ISSUE TITLE
[Alien 5] Problems

### ISSUE THREAD

**Issue by freelancers19** [oe-alliance/oe-alliance-core#532]
- OpenATV 6.3 does not start. It blocks on "Amiko" 
- Sometimes on 4k channels, the decoder with openatv 6.2, crashes.
- in deepstanby the LED is blue and does not turn red.

**Comment by nickersk** [comment]
any boot logs?

**Comment by freelancers19** [comment]
With OpenATV 6.3; No logs. The "/home/root" folder is empty.
How can I enable the log at startup? can I activate the log in aml_autoscript?

**Comment by nickersk** [comment]
if there is nothing usable in /var/log , then we will need to see boot log from console ...

**Comment by freelancers19** [comment]
how can I see the log from the console?

**Comment by nickersk** [comment]
seems like console port is somewhere on mainboard ...

**Comment by nickersk** [comment]
as i can see no more possibilities to fix this for now i will close this  thread. you can try to ask manufacturer for support (so we can integrate needed changes to image). thank you
