### ISSUE TITLE
FFMPEG zip Error !

### ISSUE THREAD

**Issue by thawtes** [oe-alliance/oe-alliance-core#536]
hi,
ffmpeg error message 
[http @ 0x4463b0] Compressed (gzip) content, need zlib with gzip support
http://sampledomain.com/playlist.m3u8: Function not implemented

image: openatv-6.3-vuduo2-20190927_usb.zip
device: vu+ duo2
pls fix @atvcaptain @nickersk

**Comment by nickersk** [comment]
looks like zlib is compiled with gz support... ok, this comes from http.c will try to find why ...

**Comment by thawtes** [comment]
> 
> 
> looks like zlib is compiled with gz support... ok, this comes from http.c will try to find why ...
thanks...

dear @nickersk 
I found the problem !

problem caused by **libavformat58** package
I installed the previous version of this package and the problem is solved!

so what are we supposed to do now?
I leave it to you to fix it from now on...

note: there are other problems with other dependent packages.
(eg. sound distortion in playback of some streams)

**Comment by nickersk** [comment]
there is check for compile flags 16,17 of zlib, from manual: 16: NO_GZCOMPRESS — gz* functions cannot compress (to avoid linking deflate code when not needed)17: NO_GZIP — deflate can't write gzipstreams, and inflate can't detect and decode gzip streams (to avoid linking crc code)
this change wil affect whole built system...

**Comment by nickersk** [comment]
since 4.2 there are more issues discovered - https://github.com/oe-alliance/oe-alliance-core/commit/34a4e18ecfcb516d53b1b398bc18d39e36f32ec7#commitcomment-35281486 i will rollback to 4.1.4. thank you

**Comment by thawtes** [comment]
thanks, everything is working normally
