### ISSUE TITLE
nfs-utils 2.4.1

### ISSUE THREAD

**Issue by atvcaptain** [oe-alliance/oe-alliance-core#537]
have you fix this issue before i start to search

BB_VERSION           = "1.43.1"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "aarch64-oe-linux"
MACHINE              = "osmio4kplus"
DISTRO               = "openatv"
DISTRO_VERSION       = "6.4"
TUNE_FEATURES        = "aarch64"

| gcc  -DHAVE_CONFIG_H -I. -I../../support/include  -isystem/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/nfs-utils/2.4.1-r0/recipe-sysroot-native/usr/include -D_GNU_SOURCE -D_GNU_SOURCE -isystem/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/nfs-utils/2.4.1-r0/recipe-sysroot-native/usr/include -march=native -O2 -pipe -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/nfs-utils/2.4.1-r0=/usr/src/debug/nfs-utils/2.4.1-r0                      -fdebug-prefix-map=/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/nfs-utils/2.4.1-r0=/usr/src/debug/nfs-utils/2.4.1-r0                      -fdebug-prefix-map=/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/nfs-utils/2.4.1-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/nfs-utils/2.4.1-r0/recipe-sysroot-native=  -Wno-error=format-overflow -c -o testlk-testlk.o `test -f 'testlk.c' || echo './'`testlk.c
| gcc: error: unrecognized command line option ‘-fmacro-prefix-map=/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/nfs-utils/2.4.1-r0=/usr/src/debug/nfs-utils/2.4.1-r0’
| Makefile:455: recipe for target 'testlk-testlk.o' failed
| make[2]: *** [testlk-testlk.o] Error 1

**Comment by nickersk** [comment]
i havent got this error, will try to build ... which gcc version is on build host? which os version?

**Comment by atvcaptain** [comment]
get next issue
 cc1: error: unknown value 'native' for '-march'
| cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a
| Assembler messages:
| Error: unknown architecture `native'
| 
| Error: unrecognized option -march=native

i have remove temp the -march option in the site.conf

**Comment by nickersk** [comment]
this is strange ... i have no errors like this

**Comment by atvcaptain** [comment]
host ubunto 18_04 lts 64 bit

**Comment by nickersk** [comment]
1st issue i think appears because of gcc7 second maybe too ... build just finished by me without any errors ubuntu 19.10/gcc9.2.1

**Comment by atvcaptain** [comment]
same machine ?
so fast and all ready wow

**Comment by nickersk** [comment]
its laptop in fact. dell g3 .. and i did bitbake nfs-utils not whole image it would take bit longer :-)
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 16GB RAM, 512GB SSD, 2nd drive is sata 1TB, GeForce GTX 1060 Mobile

**Comment by atvcaptain** [comment]
about -march  https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html

**Comment by nickersk** [comment]
my site.conf: SCONF_VERSION = "1"
BB_NUMBER_THREADS = "14"
PARALLEL_MAKE = "-j 12"
BUILD_OPTIMIZATION = "-march=native -O2 -pipe"
DL_DIR = "/home/sources"
INHERIT += "rm_work"

**Comment by nickersk** [comment]
and it works without any problems ...

**Comment by atvcaptain** [comment]
good for you :)  in 1 h i have more infos

**Comment by nickersk** [comment]
stupid question, but have you installed all prereqs installed as stated here: https://www.yoctoproject.org/docs/2.7.1/ref-manual/ref-manual.html#required-packages-for-the-build-host

**Comment by atvcaptain** [comment]
now ok
1) i remove  SRC_URI_remove = "file://0001-Don-t-build-tools-with-CC_FOR_BUILD.patch"
2) remove -march=native

**Comment by nickersk** [comment]
ahh now i remember... exactly this caused error on newer oses. doing rebuild... if issue will appear i got problem :-) and yes, build broken with gcc 8+ ... @atvcaptain host gcc 8+ is critical

**Comment by nickersk** [comment]
that patch (0001-Don-t-build-tools-with-CC_FOR_BUILD.patch) however is completly wrong imho. i test another approach, will commit later if success. when i build whole package with same envvars. why the h*ll remove them from two failing cases? especially when assembler error is clearly mentioned in build log?

**Comment by atvcaptain** [comment]
at the moment next build issue i seach i open a new case

**Comment by nickersk** [comment]
https://github.com/oe-alliance/oe-alliance-core/commit/6b9e0ddf3f8bc9e89eb875f5a780967197ef8c3c this is what i meant above.
