### ISSUE TITLE
astra-sm 0.2

### ISSUE THREAD

**Issue by atvcaptain** [oe-alliance/oe-alliance-core#538]
| gcc  -Wall -Wextra -I../lua -Os -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/astra-sm/0.2-r0=/usr/src/debug/astra-sm/0.2-r0                      -fdebug-prefix-map=/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/astra-sm/0.2-r0=/usr/src/debug/astra-sm/0.2-r0                      -fdebug-prefix-map=/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/astra-sm/0.2-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/astra-sm/0.2-r0/recipe-sysroot-native=  -std=c99 -pthread -fomit-frame-pointer -funsafe-loop-optimizations -ffast-math -fwrapv -fstrict-aliasing \
|     -o mkscript ./mkscript.c
| gcc: error: unrecognized command line option ‘-fmacro-prefix-map=/home/oe1/atv64arm/build-enviroment/builds/openatv/release/osmio4kplus/tmp/work/aarch64-oe-linux/astra-sm/0.2-r0=/usr/src/debug/astra-sm/0.2-r0’
| Makefile:488: recipe for target 'mkscript' failed
| make[1]: *** [mkscript] Error 1

**Comment by nickersk** [comment]
same thing i think :-) have you tried to upgrade host gcc to version 8+? -fmacro-prefix-map is problem for gcc 7-

**Comment by atvcaptain** [comment]
i have now install gcc 8,x and check again

**Comment by atvcaptain** [comment]
ok with gcc-8 works

**Comment by Huevos** [comment]
What version of Ubuntu are you running. Is this not available in 16.04

**Comment by Huevos** [comment]
Ok, I figured it out now.
