### ISSUE TITLE
[sh4] missing support for sh4 based spark71xx boxes

### ISSUE THREAD

**Issue by christianege** [oe-alliance/oe-alliance-core#54]
There is no support for the sh4 based spark71xx boxes.

Are there any interest to get those boxes supported?

**Comment by atvcaptain** [comment]
we dont have any sh4 hardware , so no sh4 support in oe-a

**Comment by christianege** [comment]
I can provide [sh4 support](https://github.com/project-magpie/meta-stlinux/tree/denzil-next) and Testing as-well.
