### ISSUE TITLE
CCcam not working

### ISSUE THREAD

**Issue by atvcaptain** [oe-alliance/oe-alliance-core#541]
CCcam: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
root@mutant51:/usr/lib# ln -s /usr/lib/libcrypto.so.1.0.2 /usr/lib/libcrypt.so.1
root@mutant51:/usr/lib# CCcam
CCcam: /usr/lib/libcrypt.so.1: version `GLIBC_2.4' not found (required by CCcam)
root@mutant51:/usr/lib#

**Comment by nickersk** [comment]
2.3.2 version?

**Comment by atvcaptain** [comment]
yes

**Comment by nickersk** [comment]
try to install openssl compat and ln -s to older libcrypto

**Comment by atvcaptain** [comment]
install libxcrypt-compat  fix it

**Comment by nickersk** [comment]
RDEPENDS_${PN} = "libxcrypt-compat" is there so it should work from first install (if in feed is this version)
