### ISSUE TITLE
Samba build 4.4

### ISSUE THREAD

**Issue by betacentauri** [oe-alliance/oe-alliance-core#542]
With latest change build fails.
OE don't expects to remove cluster support (ctdb) as install_append needs the files:
https://git.openembedded.org/meta-openembedded/tree/meta-networking/recipes-connectivity/samba/samba_4.10.8.bb#n179

Special install_append in bbappend is needed.

**Comment by nickersk** [comment]
i'll take a look on this.

**Comment by betacentauri** [comment]
My proposal would be to re enable cluster support.
In OE-A 4.3 was the problem that cluster support delivered several test files. It seems new samba receipt in 4.4 don't do it.

**Comment by betacentauri** [comment]
But only cluster support and let the rest as it is.

**Comment by nickersk** [comment]
reenabling cluster support and removing profiling only from configure causes this install error: /image/usr/sbin/samba_upgradedns: No such file or directory .one way would be to create dummy file before install. i have to try some other things ... there is sed playing with python it meta-oe recipe. now trying to disable profiling and reenable python ... i thing i found where problem is, working on it now

**Comment by betacentauri** [comment]
Strange

**Comment by atvcaptain** [comment]
i see no python-samba in the 4.4 image !

**Comment by nickersk** [comment]
https://github.com/oe-alliance/oe-alliance-core/commit/e1a528415e6e243a2a6e9af17edc211b3b859b48 build ok for hd51

**Comment by betacentauri** [comment]
So we can close?

**Comment by atvcaptain** [comment]
i check now build too

**Comment by nickersk** [comment]
@betacentauri 4.3 is ok? i cant check it right now ...

**Comment by atvcaptain** [comment]
4.3 is ok

**Comment by atvcaptain** [comment]
4.4 is fixed  image 3 mb smaller (zipped)
