### ISSUE TITLE
oe-alliance-branding,remotes

### ISSUE THREAD

**Issue by nickersk** [oe-alliance/oe-alliance-core#553]
is there any reason why this is getting rebuild always (PR[vardepsexclude] += "DATE"
do_configure[nostamp] = "1") if it is autorev? wouldnt be enough to rebuild on upstream change only?

**Comment by atvcaptain** [comment]
yes branding have no info when we change any in machine.conf or drivers

after every run we need update version

sure the old (PR[vardepsexclude] += "DATE"  was test and have not work correct can remove

**Comment by nickersk** [comment]
thx https://github.com/oe-alliance/oe-alliance-core/commit/9a48ccc6c12dc3d1c6cf6dad1472234dc2690ba2
