### ISSUE TITLE
gst1.0 - meson

### ISSUE THREAD

**Issue by nickersk** [oe-alliance/oe-alliance-core#555]
@atvcaptain https://github.com/oe-alliance/oe-alliance-core/commit/640bc390f6437618cce49688a6a8a0054477dff2 can you test it on 4.4 outside official images pls? i created it and tested for nextp3 branches (mipsel, arm, aarch64, hisi, sh4). if all ok can be cherrypicked to 4.4. thx

**Comment by nickersk** [comment]
p3 meta-OE is broken currently (guys are playing with licenses) will wait for them to fix it.

**Comment by atvcaptain** [comment]
yes i can test it  offline, need some time we test a new box at the moment dev server are busy :)

**Comment by 68foxboris** [comment]
Tell me please:
Log data follows:
| DEBUG: Executing shell function do_configure
| NOTE: Executing meson -Ddoc=disabled -Dexamples=disabled -Dqt5=disabled -Ddecklink=enabled -Ddvb=enabled -Dfbdev=enabled -Dnetsim=enabled -Dshm=enabled -Ddts=enabled -Dmpegdemux=enabled -Dandroidmedia=disabled -Dapplemedia=disabled -Dbs2b=disabled -Dchromaprint=disabled -Ddirectsound=disabled -Dfdkaac=disabled -Dgme=disabled -Dgsm=disabled -Diqa=disabled -Dladspa=disabled -Dlv2=disabled -Dmpeg2enc=disabled -Dmplex=disabled -Dmsdk=disabled -Dmusepack=disabled -Dnvcodec=disabled -Dofa=disabled -Dopenexr=disabled -Dopenni2=disabled -Dopensles=disabled -Dsoundtouch=disabled -Dspandsp=disabled -Dteletext=disabled -Dtinyalsa=disabled -Dwasapi=disabled -Dwebrtcdsp=disabled -Dwildmidi=disabled -Dwinks=disabled -Dwinscreencap=disabled -Dzbar=disabled -Dassrender=disabled -Dbluez=disabled -Dbz2=enabled -Dcurl=enabled -Dcurl-ssh2=disabled -Ddash=enabled -Ddc1394=disabled -Ddebug=false -Ddirectfb=disabled -Ddtls=enabled -Dfaac=enabled -Dfaad=enabled -Dflite=disabled -Dfluidsynth=disabled -Dgl=disabled -Dhls=enabled -Dhls-crypto=openssl -Dkms=disabled -Dlibde265=enabled -Dlibmms=enabled -Dmodplug=disabled -Dmsdk=disabled -Dneon=enabled -Dopenal=disabled -Dopencv=disabled -Dopenh264=disabled -Dopenjpeg=disabled -Dopenmpt=disabled -Dopus=enabled -Dorc=enabled --disable-qt -Dresindvd=disabled -Drsvg=enabled -Drtmp=enabled -Dsbc=enabled -Dsmoothstreaming=enabled -Dsndfile=enabled -Dsrtp=disabled -Dtinyalsa=disabled -Dttml=enabled -Duvch264=enabled -Dvoaacenc=disabled -Dvoamrwbenc=disabled -Dwayland=disabled -Dwebp=enabled -Dwebrtc=disabled -Dwebrtcdsp=disabled -Dx265=enabled...
| usage: meson [-h]
|              {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite}
|              ...
| meson: error: unrecognized arguments: --disable-qt
| ERROR: meson failed
| WARNING: /home/foxbob/hd51/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/gstreamer1.0-plugins-bad/1.17.0.1+gitAUTOINC+b55f380b20-r0/temp/run.do_configure.28635:1 exit 1 from 'exit 1'
| ERROR: Execution of '/home/foxbob/hd51/build/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/gstreamer1.0-plugins-bad/1.17.0.1+gitAUTOINC+b55f380b20-r0/temp/run.do_configure.28635' failed with exit code 1:
| usage: meson [-h]
|              {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite}
|              ...
| meson: error: unrecognized arguments: --disable-qt

**Comment by nickersk** [comment]
update meta-qt5 submodule and try again

**Comment by 68foxboris** [comment]
Thanks!

**Comment by 68foxboris** [comment]
Good evening. How can I fix this error?
[
![1_0_1F_CB_2_70_1680000_0_0_0_20191124202739](https://user-images.githubusercontent.com/17230642/69499761-5cd27580-0efe-11ea-87f6-bd2dc774716b.jpg)
![1_0_1F_CB_2_70_1680000_0_0_0_20191124202748](https://user-images.githubusercontent.com/17230642/69499763-6065fc80-0efe-11ea-84d9-a914e9b2f3c3.jpg)
![1_0_1F_CB_2_70_1680000_0_0_0_20191124202758](https://user-images.githubusercontent.com/17230642/69499765-62c85680-0efe-11ea-9e0a-42e1d8c67656.jpg)
](url)

**Comment by 68foxboris** [comment]
Good evening. How can I fix this error?
![1_0_1F_CB_2_70_1680000_0_0_0_20191124202739](https://user-images.githubusercontent.com/17230642/69499803-afac2d00-0efe-11ea-9a98-c2e32d936637.jpg)
![1_0_1F_CB_2_70_1680000_0_0_0_20191124202748](https://user-images.githubusercontent.com/17230642/69499806-b20e8700-0efe-11ea-8a77-904c8fe550de.jpg)
![1_0_1F_CB_2_70_1680000_0_0_0_20191124202758](https://user-images.githubusercontent.com/17230642/69499807-b5097780-0efe-11ea-9bfa-9934b0bfc040.jpg)

**Comment by nickersk** [comment]
its ok, ffmpeg 4.2.1 wants to install its own libav files, but they are provided by gstreamer1.0-libav already - and are diferrent version (4.1.4). only way to fix this would be to remove gst-libav and then install ffmpeg ...

**Comment by 68foxboris** [comment]
And if you do so during assembly,so that there is one version ffmpeg.Or so wrong?
DEPENDS = "gstreamer1.0 gstreamer1.0-plugins-base ffmpeg"

**Comment by nickersk** [comment]
well, gstreamer meson uses ffpmeg 4.1.4 . if u will try to depend on ffmpeg 4.2.1 it wil use 4.2.1 which is not recomended. thanks for reporting this, i will research it tomorrow. till now i can say there really is install conflict, but question is how to solve it...

**Comment by nickersk** [comment]
mesonbuild is causing libav libs to be installed by every build of ffmpeg meson port... using ffmpeg in DEPENDS too.

**Comment by 68foxboris** [comment]
It turns out that you need to leave it as it is.

**Comment by nickersk** [comment]
btw. using ffmpeg 4.2.1 image grows by ~5Mb

**Comment by 68foxboris** [comment]
WARNING: gstreamer1.0-libav-1.17.0.1+gitAUTOINC+77f63c2457-r0 do_package: libpostproc-4.2.1 was registered as shlib provider for libpostproc.so.55, changing it to gstreamer1.0-libav-1.17.0.1+git2254+77f63c2 because it was built later
WARNING: gstreamer1.0-libav-1.17.0.1+gitAUTOINC+77f63c2457-r0 do_package: libswresample-4.2.1 was registered as shlib provider for libswresample.so.3, changing it to gstreamer1.0-libav-1.17.0.1+git2254+77f63c2 because it was built later
WARNING: gstreamer1.0-libav-1.17.0.1+gitAUTOINC+77f63c2457-r0 do_package: libavutil-4.2.1 was registered as shlib provider for libavutil.so.56, changing it to gstreamer1.0-libav-1.17.0.1+git2254+77f63c2 because it was built later
WARNING: gstreamer1.0-libav-1.17.0.1+gitAUTOINC+77f63c2457-r0 do_package: libavformat-4.2.1 was registered as shlib provider for libavformat.so.58, changing it to gstreamer1.0-libav-1.17.0.1+git2254+77f63c2 because it was built later
WARNING: gstreamer1.0-libav-1.17.0.1+gitAUTOINC+77f63c2457-r0 do_package: libavcodec-4.2.1 was registered as shlib provider for libavcodec.so.58, changing it to gstreamer1.0-libav-1.17.0.1+git2254+77f63c2 because it was built later
WARNING: gstreamer1.0-libav-1.17.0.1+gitAUTOINC+77f63c2457-r0 do_package: libswscale-4.2.1 was registered as shlib provider for libswscale.so.5, changing it to gstreamer1.0-libav-1.17.0.1+git2254+77f63c2 because it was built later
WARNING: gstreamer1.0-libav-1.17.0.1+gitAUTOINC+77f63c2457-r0 do_package: libavdevice-4.2.1 was registered as shlib provider for libavdevice.so.58, changing it to gstreamer1.0-libav-1.17.0.1+git2254+77f63c2 because it was built later
WARNING: gstreamer1.0-libav-1.17.0.1+gitAUTOINC+77f63c2457-r0 do_package: libavresample-4.2.1 was registered as shlib provider for libavresample.so.4, changing it to gstreamer1.0-libav-1.17.0.1+git2254+77f63c2 because it was built later
WARNING: gstreamer1.0-libav-1.17.0.1+gitAUTOINC+77f63c2457-r0 do_package: libavfilter-4.2.1 was registered as shlib provider for libavfilter.so.7, changing it to gstreamer1.0-libav-1.17.0.1+git2254+77f63c2 because it was built later

**Comment by nickersk** [comment]
so gst replaced ffmpeg libs. i will modify gst libav to live its own life under lib/gstreamer1.0 since meson port of ff had not been updated for over 2 months.

**Comment by 68foxboris** [comment]
Ok.

**Comment by 68foxboris** [comment]
After last commit not work ffmpeg and and everything connected with it.

root@et1x000:~# exteplayer3
exteplayer3: error while loading shared libraries: libswscale.so.5: cannot open shared object file: No such file or directory
root@et1x000:~# ffmpeg
ffmpeg: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory
root@et1x000:~#

**Comment by nickersk** [comment]
have you tried clean image flash? and install ffmpeg after? if you did just update, new gst removed libs from libdir, thats why ffmpeg stoped working i think. pls, let me know after clean image install.

**Comment by 68foxboris** [comment]
Clean image flash.Install e2iplayer.Not work hlsdl and exteplayer3.
2019-12-11 18:46:36+0200 [-] STS: /usr/bin/exteplayer3: error while loading shared libraries: libswscale.so.5: cannot open shared object file: No such file or directory
2019-12-11 18:46:36+0200 [-] 
2019-12-11 18:46:36+0200 [-] КОД ОШИБКИ: 127)
'Screens.MessageBox.MessageBox'>(Видимо, видео-плеер "Внешний eplayer3" не работает должным образом.
2019-12-11 18:46:36+0200 [-] 
2019-12-11 18:46:36+0200 [-] STS: /usr/bin/exteplayer3: error while loading shared libraries: libswscale.so.5: cannot open shared object file: No such file or directory
2019-12-11 18:46:36+0200 [-] 
2019-12-11 18:46:36+0200 [-] КОД ОШИБКИ: 127)

root@et1x000:~# ffmpeg
ffmpeg: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory
root@et1x000:~# exteplayer3
exteplayer3: error while loading shared libraries: libswscale.so.5: cannot open shared object file: No such file or directory
root@et1x000:~# hlsdl
hlsdl: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory
root@et1x000:~#

**Comment by nickersk** [comment]
have you noticed exteplayer3 project is closed? https://github.com/e2iplayer/exteplayer3 ... reverting for now, but in future i will dont care about exteplayer3 if it will stay so.

**Comment by 68foxboris** [comment]
I know this. I have version 68 and it works well.

**Comment by nickersk** [comment]
please try now, if all ok, i will close this.

**Comment by 68foxboris** [comment]
Ok.

**Comment by 68foxboris** [comment]
Clean image flash.Install serviceapp-exteplayer3 not install and not work.

**Comment by nickersk** [comment]
nothing else changed, how is it possible it worked before? what is the error?

**Comment by 68foxboris** [comment]
This is at the previous commit.

**Comment by nickersk** [comment]
which ? please paste link here...

**Comment by 68foxboris** [comment]
This
https://github.com/oe-alliance/oe-alliance-core/commit/17e2498a5f0e26bf6d6df506b7e0e5c83718c3ff
Committing what you changed will work anyway.

**Comment by nickersk** [comment]
ahm ok, thx for feedback. may we close this for now?

**Comment by 68foxboris** [comment]
Yes.

**Comment by 68foxboris** [comment]
Only I can’t watch DVD video through MovieSelection?
libdvdread: Couldn't find device name.
libdvdnav: Can't read name block. Probably not a DVD-ROM device.
libdvdnav: vm: dvd_read_name failed
libdvdnav: DVD disk reports itself with Region mask 0x00c00000. Regions: 1 2 3 4 5 6
[eServiceDVD] DDVD_SHOWOSD_TITLESTRING: 
[eServiceDVD] loadCuesheet trying /media/hdd/bluray/Masha i Medved'_22_DVD-5//dvd.cuts
libdreamdvd: soft ac3 decoding is available, liba52.so.0 loaded !
enigma2: ../git/mpegaudio_enc.c:347: ddvd_mpa_compute_scale_factors: Assertion `index >=0 && index <= 63' failed.
Backtrace:
