### ISSUE TITLE
[Plugin] SubsSupport - Crash in some areas (openATV 6.4)

### ISSUE THREAD

**Issue by thawtes** [oe-alliance/oe-alliance-core#556]
no problem

**Comment by thawtes** [comment]
NOTE:
i back to **python-twisted-web_18.4.0-r1** (manual install)
result : no crash

**Comment by thawtes** [comment]
> 
> 
> NOTE:
> i back to **python-twisted-web_18.4.0-r1** (manual install)
> result : no crash

of course this is not the solution

**Comment by nickersk** [comment]
just a suggestion: wouldnt it be better to ask there: https://github.com/mx3L/subssupport ?

**Comment by thawtes** [comment]
> just a suggestion: wouldnt it be better to ask there:

of course! I asked there too.
but many plugins have similar problems.
I wanted to ask if a backward compatibility patch can be done.

thanks @nickersk

**Comment by nickersk** [comment]
well imho problem can be how json.loads is directly used by return. as far as i read the docs it should be stored to some var and after take action with that var...not just return json.loads...

**Comment by thawtes** [comment]
> 
> 
> well imho problem can be how json.loads is directly used by return

i'll try to find a way to fix it
thank you for your interest

**Comment by arn354** [comment]
https://github.com/mx3L/subssupport/blob/f4a0c6f13748252ca1547bd47bfa46dda589fa00/plugin/searchsubs.py#L29

?

def recieve():
    jsonreceive = json.loads(sys.stdin.read(int(sys.stdin.read(7))))
    return jsonreceive

**Comment by thawtes** [comment]
> 
> 
> https://github.com/mx3L/subssupport/blob/f4a0c6f13748252ca1547bd47bfa46dda589fa00/plugin/searchsubs.py#L29
> 
> ?
> 
> def recieve():
> jsonreceive = json.loads(sys.stdin.read(int(sys.stdin.read(7))))
> return jsonreceive

code needs to be edited this way?
