### ISSUE TITLE
Error compile webkit-classic.

### ISSUE THREAD

**Issue by 68foxboris** [oe-alliance/oe-alliance-core#559]
Good evening.Build 4.4.Webkit-classic does not compile.Log file 400Mb.On master branch also a compilation error.

**Comment by nickersk** [comment]
machine?

**Comment by atvcaptain** [comment]
4.4 webkit Classic Build fine here i have test all Machines

**Comment by nickersk** [comment]
so looks like a local problem ... probably host os issue.

**Comment by atvcaptain** [comment]
yes not build issue

**Comment by 68foxboris** [comment]
gi et11000 4k

**Comment by atvcaptain** [comment]
np here

webkit-classic-bin_1.1+git10+bcb6573-r0_et1x000.ipk

**Comment by 68foxboris** [comment]
Thanks I will understand.

**Comment by 68foxboris** [comment]
I had a problem. Now it collects without errors.
