### ISSUE TITLE
Incorrect Device Info for HDD

### ISSUE THREAD

**Issue by t5k6** [oe-alliance/oe-alliance-core#570]
![OpenNFR](https://user-images.githubusercontent.com/12563212/70239348-31f8e480-177c-11ea-930f-31de661bea41.png)
![image](https://user-images.githubusercontent.com/12563212/70239423-52c13a00-177c-11ea-8dc6-8a11ebf062f9.png)
I have 2 storage devices attached to my enigma2 machine (Formuler1), one to use as an hdd (and for being able to boot to multiple distros), and another one to record videos/movies.
Despite having correct info on fstab and those two devices get mixed up, preventing me to use multiboot option.
I am not sure if this is the right place to report this.

**Comment by atvcaptain** [comment]
looks the linux kernel make trouble, please check new images again
