### ISSUE TITLE
libudfread wrong source URL

### ISSUE THREAD

**Issue by lincsat** [oe-alliance/oe-alliance-core#573]
meta-oe/recipes-support/libudfread/libudfread_git.bb

VLC has changed their source URL, looks like it needs this change at line 7

-  SRC_URI = "git://git.videolan.org/libudfread.git;branch=master;protocol=git"

+  SRC_URI = "git://code.videolan.org/videolan/libudfread.git;branch=master;protocol=git"

**Comment by nickersk** [comment]
thx for reporting ... https://github.com/oe-alliance/oe-alliance-core/commit/0a95d9c8d35ad1f0316bbef530db244dd61c4bfb
