### ISSUE TITLE
gst1.0 - meson

### ISSUE THREAD

**Issue by 68foxboris** [oe-alliance/oe-alliance-core#574]
Only I can not watch DVD video through MovieSelection?
`libdvdnav: Using dvdnav version 6.0.1
[eServiceDVD] DVD_SIZE_CHANGED 0: 720x576 2
[eServiceDVD] DVD_FRAMERATE_CHANGED 0: 29970
[eServiceDVD] DVD_PROGRESSIVE_CHANGED 0: 0
libdvdread: Couldn't find device name.
libdvdnav: Can't read name block. Probably not a DVD-ROM device.
libdvdnav: vm: dvd_read_name failed
libdvdnav: DVD disk reports itself with Region mask 0x00c00000. Regions: 1 2 3 4 5 6
[eServiceDVD] DDVD_SHOWOSD_TITLESTRING: 
[eServiceDVD] loadCuesheet trying /media/hdd/bluray/Masha i Medved'_22_DVD-5//dvd.cuts
.....
enigma2: ../git/mpegaudio_enc.c:347: ddvd_mpa_compute_scale_factors: Assertion `index >=0 && index <= 63' failed.
Backtrace:
`

**Comment by nickersk** [comment]
have you tried EMC?

**Comment by 68foxboris** [comment]
No, but it should reproduce here.Prior to changing the assembly of the gstreamer everything worked.

**Comment by nickersk** [comment]
you mean non-meson gst version? or some of previous meson ported version?

**Comment by 68foxboris** [comment]
non-meson

**Comment by nickersk** [comment]
well this transition is bit complicated, will need much more time ...

**Comment by 68foxboris** [comment]
Ok.

**Comment by nickersk** [comment]
done, now uses ff 4.2.2 (hisi 3.4.2)
