### ISSUE TITLE
platforms

### ISSUE THREAD

**Issue by Power535** [oe-alliance/oe-alliance-core#578]
What list platforms mips32el supported in user mode ?

**Comment by nickersk** [comment]
i am sorry i dont understand your question. you mean what mips32el platform is? mips32el = mips 32bit little endian

**Comment by Power535** [comment]
mipsel for bchip

**Comment by Power535** [comment]
mips 32 little endian for bchip

**Comment by nickersk** [comment]
you can find SOC models in meta-brands layer under meta-machine/conf/machine/machine.conf

**Comment by Power535** [comment]
There is no information
kernel or user mode

**Comment by nickersk** [comment]
its not that easy,you have to search for this: https://github.com/oe-alliance/oe-alliance-core/blob/8b6580eb6aca8bc3a50b6b2fb2e2e4908fe03516/meta-brands/meta-airdigital/conf/machine/include/airdigital-arm.inc#L14 then you can find kernel recipe and defconfig in recipes-linux directory. for more info refer to openembedded manuals. can we close this?

**Comment by Power535** [comment]
Meant bchip modules in user mode

**Comment by nickersk** [comment]
it is part of manufacturers drivers - closed source.

**Comment by Power535** [comment]
Meant bchip modules in user mode
I tried to search for a long time, but I fall into kernel mode
I have modules only in user mode i want adding platform for compile

**Comment by nickersk** [comment]
maybe you can write recipe for kernel-module-abc and then install it to image IMAGE_INSTALL_append += " \ 
kernel-module-abc\
"

**Comment by Power535** [comment]
I am not a programmer
Possible i send for you tomorrow modules ?
To see how to add
I do not know as configure
I have night here now

**Comment by nickersk** [comment]
i am really busy these days, maybe you can try it yourself ..look at some other recipes to find the logic ...
this is good start maybe: http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta-skeleton/recipes-kernel/hello-mod

**Comment by Power535** [comment]
I tried fews year and no results
Will wait any time
Any help from any users

**Comment by nickersk** [comment]
ok, so i will let this thread open for some time, maybe someone with more time will take look at this.

**Comment by atvcaptain** [comment]
e2 drivers use kernel mode, user mode drivers not support with e2 code

**Comment by atvcaptain** [comment]
i read you "I am not a programmer" i think forget your bcm 7231 meta
