### ISSUE TITLE
qtwebkit 

### ISSUE THREAD

**Issue by kueken** [oe-alliance/oe-alliance-core#579]
It seems that in some cases the qtwebkit makes construction mistakes because of 'historical' cflags.
'-mieee'
Is it possible to deactivate it, or to remove it ?
Will probably no longer be interesting for sh4 ;-)

You can find these lines
git

/source/WTF/WTF.pro
/source/JavaScriptCore/Target.pri
/source/autotools/SetupCompilerFlags.m4

**Comment by nickersk** [comment]
which recipe (we have more qt versions)?

**Comment by kueken** [comment]
https://github.com/qt/qtwebkit/blob/5.9/Source/WTF/WTF.pro#L272-L275
https://github.com/qt/qtwebkit/blob/5.9/Source/autotools/SetupCompilerFlags.m4#L18-L21
https://github.com/qt/qtwebkit/blob/5.9/Source/JavaScriptCore/Target.pri#L361-L364

Just as an example, but that's not the git source from here.
Do not know if the other two git have these 'historical' flags.
However, they lead to possible construction errors even though one does not build for sh4, but for arm / hisi.

**Comment by nickersk** [comment]
thx, will take a look @ these

**Comment by 68foxboris** [comment]
Ubuntu 18.04 LTS.Good evening. Please tell me how to solve this problem during compilation.At 5.8 the same error.

`In file included from /home/foxbob/zeus/build/tmp/work/et1x000-oe-linux-gnueabi/qtwebkit/5.14.1+gitAUTOINC+ab1bd15209-r0/recipe-sysroot/usr/include/EGL/egl.h:39,
                 from /home/foxbob/zeus/build/tmp/work/et1x000-oe-linux-gnueabi/qtwebkit/5.14.1+gitAUTOINC+ab1bd15209-r0/git/Source/WebCore/platform/graphics/opengl/Extensions3DOpenGLES.cpp:36:
/home/foxbob/zeus/build/tmp/work/et1x000-oe-linux-gnueabi/qtwebkit/5.14.1+gitAUTOINC+ab1bd15209-r0/recipe-sysroot/usr/include/EGL/eglplatform.h:113:10: fatal error: X11/Xlib.h: No such file or directory
  113 | #include <X11/Xlib.h>
      |          ^~~~~~~~~~~~
compilation terminated.`


apt-file search /X.h
emscripten: /usr/share/emscripten/system/include/X11/X.h
gmt-doc: /usr/share/doc/gmt/html/X.html
libboost1.62-doc: /usr/share/doc/libboost1.62-doc/examples/libs/coroutine/example/asymmetric/X.h
libboost1.65-doc: /usr/share/doc/libboost1.65-doc/examples/libs/coroutine/example/asymmetric/X.h
libclhep-dev: /usr/include/CLHEP/GenericFunctions/X.hh
nx-x11proto-core-dev: /usr/include/x86_64-linux-gnu/nx-X11/X.h
pike7.8-reference: /usr/share/doc/pike7.8-doc/html/reference/ex/predef_3A_3A/Image/X.html
pike7.8-reference: /usr/share/doc/pike7.8-doc/html/reference/ex/predef_3A_3A/Protocols/X.html
pike8.0-doc: /usr/share/doc/pike8.0-doc/html/reference/ex/predef_3A_3A/Image/X.html
pike8.0-doc: /usr/share/doc/pike8.0-doc/html/reference/ex/predef_3A_3A/Protocols/X.html
x11proto-dev: /usr/include/X11/X.h

**Comment by nickersk** [comment]
there is include requesting x11 feature in EGL which afaik is part of drivers ... try to enable opengl in distro features

**Comment by 68foxboris** [comment]
I add DISTRO_FEATURES_EXTRA = "opengl",but there is a mistake.

**Comment by nickersk** [comment]
search for Xlib.h

**Comment by 68foxboris** [comment]
foxbob@foxbob-System:~$ find /usr/include/X11 -name Xlib.h
/usr/include/X11/Xlib.h

**Comment by nickersk** [comment]
it must be in work tree, not host root

**Comment by nickersk** [comment]
u can try to add x11 to or libx11 to depends and try, but imho it is just waste of time

**Comment by 68foxboris** [comment]
And how to add it or do you need to make a symlink?

**Comment by nickersk** [comment]
start with studying openembedded manuals, thats the correct way, like all of us do...

**Comment by 68foxboris** [comment]
Ok.

**Comment by nickersk** [comment]
@68foxboris any progress ?

**Comment by 68foxboris** [comment]
It doesn’t work with me. And most likely that there is no support for gles.

**Comment by 68foxboris** [comment]
There is webkit-classic,hbbtv works.And I wanted to add something else.Compilation is not received with kodi 18.

**Comment by nickersk** [comment]
@kueken pls see https://github.com/oe-alliance/build-enviroment/commit/27c54e3e202bb902a2614cfd38dcea0c92d78f44

**Comment by 68foxboris** [comment]
I managed to collect qtwebkit_5.14.0+git0+ab1bd15209-r0_et1x000.ipk,zeus branch,so wrong,but i just added a folder X11 system in usr/include.After start qtstalker dark screen and throws it into the channel view.
