### ISSUE TITLE
beyowiz compile error

### ISSUE THREAD

**Issue by ahmedmoselhi** [oe-alliance/oe-alliance-core#582]
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/openspabuilder/openspa/build-enviroment/builds/beyonwiz/release/spark/tmp/work/sh4-oe-linux/perl/5.24.4-r0/sstate-install-packagedata/pkgdata' -> '/home/openspabuilder/openspa/build-enviroment/builds/beyonwiz/release/spark/tmp/work/sh4-oe-linux/perl/5.24.4-r0/pkgdata'

WARNING: Logfile for failed setscene task is /home/openspabuilder/openspa/build-enviroment/builds/beyonwiz/release/spark/tmp/work/sh4-oe-linux/perl/5.24.4-r0/temp/log.do_packagedata_setscene.7054
WARNING: Setscene task (/home/openspabuilder/openspa/build-enviroment/openembedded-core/meta/recipes-devtools/perl/perl_5.24.4.bb:do_packagedata_setscene) failed with exit code '1' - real task will be run instead
NOTE: Executing RunQueue Tasks
ERROR: perl-5.24.4-r0 do_packagedata: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:sstate_task_postfunc(d)
     0003:
File: '/home/openspabuilder/openspa/build-enviroment/openembedded-core/meta/classes/sstate.bbclass', lineno: 713, function: sstate_task_postfunc
     0709:
     0710:    sstateinst = d.getVar("SSTATE_INSTDIR")
     0711:    d.setVar('SSTATE_FIXMEDIR', shared_state['fixmedir'])
     0712:
 *** 0713:    sstate_installpkgdir(shared_state, d)
     0714:
     0715:    bb.utils.remove(d.getVar("SSTATE_BUILDDIR"), recurse=True)
     0716:}
     0717:sstate_task_postfunc[dirs] = "${WORKDIR}"
File: '/home/openspabuilder/openspa/build-enviroment/openembedded-core/meta/classes/sstate.bbclass', lineno: 360, function: sstate_installpkgdir
     0356:        oe.path.remove(dir)
     0357:
     0358:    for state in ss['dirs']:
     0359:        prepdir(state[1])
 *** 0360:        os.rename(sstateinst + state[0], state[1])
     0361:    sstate_install(ss, d)
     0362:
     0363:    for plain in ss['plaindirs']:
     0364:        workdir = d.getVar('WORKDIR')
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/home/openspabuilder/openspa/build-enviroment/builds/beyonwiz/release/spark/tmp/work/sh4-oe-linux/perl/5.24.4-r0/sstate-build-packagedata/pkgdata' -> '/home/openspabuilder/openspa/build-enviroment/builds/beyonwiz/release/spark/tmp/work/sh4-oe-linux/perl/5.24.4-r0/pkgdata'

ERROR: perl-5.24.4-r0 do_packagedata: Function failed: sstate_task_postfunc
ERROR: Logfile of failure stored in: /home/openspabuilder/openspa/build-enviroment/builds/beyonwiz/release/spark/tmp/work/sh4-oe-linux/perl/5.24.4-r0/temp/log.do_packagedata.7060
ERROR: Task (/home/openspabuilder/openspa/build-enviroment/openembedded-core/meta/recipes-devtools/perl/perl_5.24.4.bb:do_packagedata) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5367 tasks of which 5366 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/openspabuilder/openspa/build-enviroment/openembedded-core/meta/recipes-devtools/perl/perl_5.24.4.bb:do_packagedata
Summary: There was 1 WARNING message shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
Makefile:1026: recipe for target 'image' failed
make: *** [image] Error 1
openspabuilder@ip-172-31-28-90:~/openspa/build-enviroment$

**Comment by nickersk** [comment]
this is nothing we can help with (check free space on hdd), you can try to remove whole builds dir and start from scratch.
