### ISSUE TITLE
egami enigma2 building error

### ISSUE THREAD

**Issue by ahmedmoselhi** [oe-alliance/oe-alliance-core#583]
| checking for the pthreads library -lpthreads... no
| checking whether pthreads work without any flags... no
| checking whether pthreads work with -Kthread... no
| checking whether pthreads work with -kthread... no
| checking for the pthreads library -llthread... no
| checking whether pthreads work with -pthread... yes
| checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
| checking if more special flags are required for pthreads... no
| checking ost/dmx.h usability... no
| checking ost/dmx.h presence... no
| checking for ost/dmx.h... no
| checking linux/dvb/version.h usability... yes
| checking linux/dvb/version.h presence... yes
| checking for linux/dvb/version.h... yes
| configure: found dvb version 5
| checking for sh4-oe-linux-pkg-config... no
| checking for pkg-config... /home/openspabuilder/openspa/build-enviroment/builds/egami/release/spark/tmp/work/amiko8900-oe-linux/enigma2/8.1+gitAUTOINC+2764bde281-r0/recipe-sysroot-native/usr/bin/pkg-config
| configure: WARNING: using cross tools not prefixed with host triplet
| checking pkg-config is at least version 0.9.0... yes
| checking for freetype2 fribidi gstreamer-1.0 gstreamer-pbutils-1.0 libdvbsi++ libpng libxml-2.0 sigc++-1.2 libssl libcrypto... no
| configure: error: Package requirements (freetype2 fribidi gstreamer-1.0 gstreamer-pbutils-1.0 libdvbsi++ libpng libxml-2.0 sigc++-1.2 libssl libcrypto) were not met:
|
| No package 'sigc++-1.2' found
|
| Consider adjusting the PKG_CONFIG_PATH environment variable if you
| installed software in a non-standard prefix.
|
| Alternatively, you may set the environment variables BASE_CFLAGS
| and BASE_LIBS to avoid the need to call pkg-config.
| See the pkg-config man page for more details.
| NOTE: The following config.log files may provide further information.
| NOTE: /home/openspabuilder/openspa/build-enviroment/builds/egami/release/spark/tmp/work/amiko8900-oe-linux/enigma2/8.1+gitAUTOINC+2764bde281-r0/git/config.log
| ERROR: configure failed
| WARNING: /home/openspabuilder/openspa/build-enviroment/builds/egami/release/spark/tmp/work/amiko8900-oe-linux/enigma2/8.1+gitAUTOINC+2764bde281-r0/temp/run.do_configure.9729:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_configure (log file is located at /home/openspabuilder/openspa/build-enviroment/builds/egami/release/spark/tmp/work/amiko8900-oe-linux/enigma2/8.1+gitAUTOINC+2764bde281-r0/temp/log.do_configure.9729)
ERROR: Task (/home/openspabuilder/openspa/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2/enigma2.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3690 tasks of which 3304 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/openspabuilder/openspa/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2/enigma2.bb:do_configure
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
Makefile:1026: recipe for target 'image' failed
make: *** [image] Error 1

**Comment by nickersk** [comment]
egami isnt maintained for a long time.
