### ISSUE TITLE
Error compile dvdbackup.

### ISSUE THREAD

**Issue by 68foxboris** [oe-alliance/oe-alliance-core#588]
Error compile dvdbackup after this https://code.videolan.org/videolan/libdvdread/-/commits/master

`
| ../../dvdbackup-0.4.2/src/dvdbackup.c: In function 'DVDWriteCells':
| ../../dvdbackup-0.4.2/src/dvdbackup.c:172:22: warning: unused parameter 'title_set_info' [-Wunused-parameter]
|   172 |   title_set_info_t * title_set_info, titles_info_t * titles_info,
|       |   ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
| ../../dvdbackup-0.4.2/src/dvdbackup.c: In function 'DVDCopyIfoBup':
| ../../dvdbackup-0.4.2/src/dvdbackup.c:1212:29: error: 'ifo_handle_t' {aka 'struct <anonymous>'} has no member named 'file'
|  1212 |  size = DVDFileSize(ifo_file->file) * DVD_VIDEO_LB_LEN;
|       |                             ^~
| ../../dvdbackup-0.4.2/src/dvdbackup.c:1223:22: error: 'ifo_handle_t' {aka 'struct <anonymous>'} has no member named 'file'
|  1223 |  DVDFileSeek(ifo_file->file, 0);
|       |                      ^~
| ../../dvdbackup-0.4.2/src/dvdbackup.c:1225:27: error: 'ifo_handle_t' {aka 'struct <anonymous>'} has no member named 'file'
|  1225 |  if (DVDReadBytes(ifo_file->file,buffer,size) != size) {
|       |                           ^~
| make[2]: *** [Makefile:387: dvdbackup.o] Error 1
| make[2]: *** Waiting for unfinished jobs....
`

**Comment by nickersk** [comment]
branch, machine?

**Comment by nickersk** [comment]
branch/machine/distro?

**Comment by 68foxboris** [comment]
4.4,et11000.It seems to me it does not depend on it.On 4.3 the same error.

**Comment by 68foxboris** [comment]
Latest stable release 0.4.2 (2012-06-24)-Maybe it also depends on this?

**Comment by nickersk** [comment]
no git is used in meta-oe-alliance layer dvdbackup recipe, just latest available stable release. build without any problems.i cant reproduce your error.. and libdvdread is built from github.com/xbmc/libdvdread.git according to its recipe not from https://code.videolan.org/videolan/libdvdread/-/commits/master .

**Comment by 68foxboris** [comment]
Ok.
