### ISSUE TITLE
kodi-addon-inputstream-adaptive

### ISSUE THREAD

**Issue by 68foxboris** [oe-alliance/oe-alliance-core#590]
This message appears after the assembly is completed. It must be put in usr/lib,but install /et11000/usr/share/kodi/addons/inputstream.adaptive/

WARNING: kodi-addon-inputstream-adaptive-2.4.3+gitrAUTOINC+b5e57ca13f-r0 do_package_qa: QA Issue: kodi-addon-inputstream-adaptive: found library in wrong location: /usr/share/kodi/addons/inputstream.adaptive/libssd_wv.so [libdir]

**Comment by atvcaptain** [comment]
you can ignore all fine ,kodi libs are save under kodi folder not linux default
