### ISSUE TITLE
samba build error branch 4.4??????

### ISSUE THREAD

**Issue by ahmedmoselhi** [oe-alliance/oe-alliance-core#592]
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "sh4-oe-linux"
MACHINE              = "spark"
DISTRO               = "openvix"
DISTRO_VERSION       = "5.4"
TUNE_FEATURES        = "sh4"
meta                 = "HEAD:b6abf7c201f7c9668bdf3c6e87c7dbc70c6427f9"
meta-oe
meta-multimedia
meta-networking
meta-filesystems
meta-python
meta-webserver       = "HEAD:fd1a0c9210b162ccb147e933984c755d32899efc"
meta-oe              = "4.4:942b0abf3858a8766e54db0fd55d6fc99b49f869"
meta-qt5             = "HEAD:22f3362cfc08453a97a01eedeeac6b03eee1b71d"
meta-airdigital
meta-amiko
meta-ax
meta-blackbox
meta-beyonwiz
meta-ceryon
meta-cube
meta-dags
meta-dinobot
meta-dream
meta-edision
meta-entwopia
meta-formuler
meta-fulan
meta-gfutures
meta-gigablue
meta-ini
meta-ixuss
meta-maxytec
meta-broadmedia
meta-odin
meta-octagon
meta-protek
meta-skylake
meta-tiviar
meta-tripledot
meta-uclan
meta-ultramini
meta-vuplus
meta-xp
meta-xtrend
meta-xcore           = "4.4:942b0abf3858a8766e54db0fd55d6fc99b49f869"
meta-local           = "4.4:2f20f57004be4551c8e94961b6abe1e825772d84"
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/sbin/smbd contained in package samba requires libndr-samba-samba4.so, but no providers found in RDEPENDS_samba? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/sbin/smbd contained in package samba requires libauth-samba4.so, but no providers found in RDEPENDS_samba? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/sbin/smbd contained in package samba requires libsamba-cluster-support-samba4.so, but no providers found in RDEPENDS_samba? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr.so.0.1.0 contained in package libndr requires libgenrand-samba4.so(SAMBA_4.9.15), but no providers found in RDEPENDS_libndr? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr.so.0.1.0 contained in package libndr requires libsamba-debug-samba4.so(SAMBA_4.9.15), but no providers found in RDEPENDS_libndr? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr.so.0.1.0 contained in package libndr requires libsamba-debug-samba4.so, but no providers found in RDEPENDS_libndr? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr.so.0.1.0 contained in package libndr requires libgenrand-samba4.so, but no providers found in RDEPENDS_libndr? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /lib/security/pam_smbpass.so contained in package samba-common requires libiov-buf-samba4.so(SAMBA_4.9.15), but no providers found in RDEPENDS_samba-common? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /lib/security/pam_smbpass.so contained in package samba-common requires libcliauth-samba4.so(SAMBA_4.9.15), but no providers found in RDEPENDS_samba-common? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /lib/security/pam_smbpass.so contained in package samba-common requires libsecrets3-samba4.so(SAMBA_4.9.15), but no providers found in RDEPENDS_samba-common? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /lib/security/pam_smbpass.so contained in package samba-common requires libcliauth-samba4.so, but no providers found in RDEPENDS_samba-common? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /lib/security/pam_smbpass.so contained in package samba-common requires libsecrets3-samba4.so, but no providers found in RDEPENDS_samba-common? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /lib/security/pam_smbpass.so contained in package samba-common requires libiov-buf-samba4.so, but no providers found in RDEPENDS_samba-common? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr-standard.so.0.0.1 contained in package libndr-standard requires libsamba-debug-samba4.so(SAMBA_4.9.15), but no providers found in RDEPENDS_libndr-standard? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr-standard.so.0.0.1 contained in package libndr-standard requires libsamba-security-samba4.so(SAMBA_4.9.15), but no providers found in RDEPENDS_libndr-standard? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr-standard.so.0.0.1 contained in package libndr-standard requires libsamba-security-samba4.so, but no providers found in RDEPENDS_libndr-standard? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr-standard.so.0.0.1 contained in package libndr-standard requires libsamba-debug-samba4.so, but no providers found in RDEPENDS_libndr-standard? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr-krb5pac.so.0.0.1 contained in package libndr-krb5pac requires libsamba-debug-samba4.so(SAMBA_4.9.15), but no providers found in RDEPENDS_libndr-krb5pac? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr-krb5pac.so.0.0.1 contained in package libndr-krb5pac requires libsamba-security-samba4.so(SAMBA_4.9.15), but no providers found in RDEPENDS_libndr-krb5pac? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr-krb5pac.so.0.0.1 contained in package libndr-krb5pac requires libsamba-security-samba4.so, but no providers found in RDEPENDS_libndr-krb5pac? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA Issue: /usr/lib/libndr-krb5pac.so.0.0.1 contained in package libndr-krb5pac requires libsamba-debug-samba4.so, but no providers found in RDEPENDS_libndr-krb5pac? [file-rdeps]
ERROR: samba-4.9.15-r2 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: Logfile of failure stored in: /home/ubuntu/openvix/build-enviroment/builds/openvix/release/spark/tmp/work/sh4-oe-linux/samba/samba-4.9.15-r2/temp/log.do_package_qa.12921
ERROR: Task (/home/ubuntu/openvix/build-enviroment/meta-oe-alliance/meta-oe/recipes-connectivity/samba/samba.bb:do_package_qa) failed with exit code '1'

**Comment by nickersk** [comment]
use nextp branches for sh4 builds.or add insane skip file-rdeps to recipe.
