### ISSUE TITLE
nss postinst

### ISSUE THREAD

**Issue by 68foxboris** [oe-alliance/oe-alliance-core#593]
I built zeus branch.Kodi18 add the feed.Install and work But after installing any plugin this error appears nss postinst.Maybe you need to remove from RRECOMMENDS in DEPENDS?
![1_0_1_7923_1F_FD_1680000_0_0_0_20200308192436](https://user-images.githubusercontent.com/17230642/76169615-a0d24900-6182-11ea-928a-67b1ce5e724b.jpg)

**Comment by nickersk** [comment]
simply ignore it, thx for reporting.
