### ISSUE TITLE
assembly qtwebkit.

### ISSUE THREAD

**Issue by 68foxboris** [oe-alliance/oe-alliance-core#595]
![1_0_1_2144_3070_13E_820000_0_0_0_20200309225924](https://user-images.githubusercontent.com/17230642/76257294-1b21cc80-625a-11ea-8c9c-bddd44a3f79f.jpg)
I managed to collect qtwebkit_5.14.0+git0+ab1bd15209-r0_et1x000.ipk,zeus branch.So wrong but i just added a system folder X11 in usr/include.After start qtstalker dark screen and throws it into the channel view.
And stopped working webkit.
I want to add qtwebkit for work stalker portal.

**Comment by nickersk** [comment]
it wont be that easy ... avoid adding anything with x11 as it will not work probably since we dont use x11 image feature. there is a message on your picture clearly saying that useragent is not supported so you have to change it to something supported to continue.
