### ISSUE TITLE
kodi18 airdigital h9combo.

### ISSUE THREAD

**Issue by 68foxboris** [oe-alliance/oe-alliance-core#596]
Tell me please,what am I doing wrong.Kodi 17.6 is going without errors.I just added the necessary recipes for the assembly and the configuration error.For vu+,my et11000,hd51,sf8008 no errors.
`
CMake Error at /media/foxbob/c4339587-3917-41eb-9bc7-c71617cd24c1/h9combo/build/tmp/work/h9combo-oe-linux-gnueabi/stb-kodi-h9combo/18.6-gitrAUTOINC+8e967df921-r14/recipe-sysroot-native/usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGl (missing: OPENGL_gl_LIBRARY OPENGL_glu_LIBRARY)
Call Stack (most recent call first):
  /media/foxbob/c4339587-3917-41eb-9bc7-c71617cd24c1/h9combo/build/tmp/work/h9combo-oe-linux-gnueabi/stb-kodi-h9combo/18.6-gitrAUTOINC+8e967df921-r14/recipe-sysroot-native/usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindOpenGl.cmake:34 (find_package_handle_standard_args)
  cmake/scripts/common/Macros.cmake:366 (find_package)
  cmake/scripts/common/Macros.cmake:380 (find_package_with_ver)
  CMakeLists.txt:172 (core_require_dep)

-- Configuring incomplete, errors occurred!
`

**Comment by nickersk** [comment]
we test kodi18 on some machines only in first phase. there is a lot of todos. btw in this case cmake is unable to find opengl libs.
