### ISSUE TITLE
enigma2 error!!!

### ISSUE THREAD

**Issue by ahmedmoselhi** [oe-alliance/oe-alliance-core#610]
Initialising tasks: 100% |######################################################################################################| Time: 0:00:34
Sstate summary: Wanted 4049 Found 133 Missed 3916 Current 980 (3% match, 22% complete)
NOTE: Executing Tasks
WARNING: enigma2-8.1+gitAUTOINC+af5a4a0f3d-r0 do_configure: QA Issue: enigma2: configure was passed unrecognised options: --with-machinebuild [unknown-configure-option]
ERROR: enigma2-8.1+gitAUTOINC+af5a4a0f3d-r0 do_compile: oe_runmake failed
ERROR: enigma2-8.1+gitAUTOINC+af5a4a0f3d-r0 do_compile: Execution of '/home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/temp/run.do_compile.9858' failed with exit code 1:
make  all-recursive
make[1]: Entering directory '/home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/git'
Making all in include
make[2]: Entering directory '/home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/git/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/git/include'
Making all in lib
make[2]: Entering directory '/home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/git/lib'
/home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/recipe-sysroot-native/usr/bin/python-native/python ./actions/parseactions.py include ../lib/gui/*.h > actions/actionids.h
parsing ../lib/gui/ebutton.h
parsing ../lib/gui/ecanvas.h
parsing ../lib/gui/egauge.h
parsing ../lib/gui/einput.h
parsing ../lib/gui/einputnumber.h
parsing ../lib/gui/einputstring.h
parsing ../lib/gui/elabel.h
parsing ../lib/gui/elistboxcontent.h
parsing ../lib/gui/elistbox.h
parsing ../lib/gui/epixmap.h
parsing ../lib/gui/epositiongauge.h
parsing ../lib/gui/eslider.h
parsing ../lib/gui/esubtitle.h
parsing ../lib/gui/evideo.h
parsing ../lib/gui/ewidgetanimation.h
parsing ../lib/gui/ewidgetdesktop.h
parsing ../lib/gui/ewidget.h
parsing ../lib/gui/ewindow.h
parsing ../lib/gui/ewindowstyle.h
parsing ../lib/gui/ewindowstyleskinned.h
/home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/recipe-sysroot-native/usr/bin/python-native/python ./actions/parseactions.py parse ../lib/gui/*.h >> actions/actionids.h
parsing ../lib/gui/ebutton.h
parsing ../lib/gui/ecanvas.h
parsing ../lib/gui/egauge.h
parsing ../lib/gui/einput.h
parsing ../lib/gui/einputnumber.h
parsing ../lib/gui/einputstring.h
parsing ../lib/gui/elabel.h
parsing ../lib/gui/elistboxcontent.h
parsing ../lib/gui/elistbox.h
parsing ../lib/gui/epixmap.h
parsing ../lib/gui/epositiongauge.h
parsing ../lib/gui/eslider.h
parsing ../lib/gui/esubtitle.h
parsing ../lib/gui/evideo.h
parsing ../lib/gui/ewidgetanimation.h
parsing ../lib/gui/ewidgetdesktop.h
parsing ../lib/gui/ewidget.h
parsing ../lib/gui/ewindow.h
parsing ../lib/gui/ewindowstyle.h
parsing ../lib/gui/ewindowstyleskinned.h
gdi/region.cpp
/bin/bash: gdi/region.cpp: Permission denied
Makefile:3630: recipe for target 'actions/actionids.h' failed
make[2]: *** [actions/actionids.h] Error 126
make[2]: Leaving directory '/home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/git/lib'
Makefile:590: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/git'
Makefile:433: recipe for target 'all' failed
make: *** [all] Error 2
WARNING: /home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/temp/run.do_compile.9858:1 exit 1 from 'exit 1'

ERROR: Logfile of failure stored in: /home/ahmedmoselhi/build-enviroment/builds/egami/release/spark/tmp/work/sparkreloaded-oe-linux/enigma2/8.1+gitAUTOINC+af5a4a0f3d-r0/temp/log.do_compile.9858

**Comment by nickersk** [comment]
hi, this error comes from github.com/a4tech/dvbapp2-gui so ask there please. thanks
