### ISSUE TITLE
[dinobot] u533 no audio/video.

### ISSUE THREAD

**Issue by badproject** [oe-alliance/oe-alliance-core#620]
Last E2 images haven't audio and video at DVB channels. Search and tune without problem but cannot play.
Also, can not play any content from USB media stick.

STB Model: Ferguson Ariva ATV TT 
OEM Model: u533
Drivers: 12.12.2019

[dinobot] u533

**Comment by atvcaptain** [comment]
see you at boot the openatv bootlogo not the first splash image,

**Comment by badproject** [comment]
Show openatv bootlogo and GUI.
Also cannot take screenshot, it's seems have a driver problem.

`root@arivatwin:~# grab -o -p /tmp/grab.png`
write reg:119 [0]error! res:-1 No such device or address
`root@arivatwin:~# grab -d -p /tmp/grab.png`
write reg:119 [0]error! res:-1 No such device or address

**Comment by badproject** [comment]
All dinobot u53x models have same problem.

- u53
- u532
- u533

**Comment by atvcaptain** [comment]
u53 here all ok

![u53](https://user-images.githubusercontent.com/974786/89728988-cfa26300-da31-11ea-9338-3ac769269e2d.PNG)

**Comment by badproject** [comment]
Seems this part have problem

> 23:42:56.7287 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 37(17)
23:42:56.7288 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 40(17)
23:42:56.7289 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 43(17)
23:42:56.7289 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 46(17)
23:42:56.7289 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 47(16)
23:42:56.7290 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 49(17)
23:42:56.7290 [   ] base/ebase.cpp:280 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 52(17)

[Enigma2-debug-20201122_23-42-19.log](https://github.com/oe-alliance/oe-alliance-core/files/5580389/Enigma2-debug-20201122_23-42-19.log)

**Comment by badproject** [comment]
Problem not solved

**Comment by atvcaptain** [comment]
you must check serial log, old atv working ?

**Comment by badproject** [comment]
> you must check serial log, old atv working ?

This device haven't serial port.
Old ATV not working.
Android side working without problem.

**Comment by atvcaptain** [comment]
box have serial internal the 3 pin header

**Comment by badproject** [comment]
Do you know location at mainboard?
