### ISSUE TITLE
import error!!!

### ISSUE THREAD

**Issue by ahmedmoselhi** [oe-alliance/oe-alliance-core#621]
i have built enigma2 opennfr imae but igot this error after i start my image 
```
Traceback (most recent call last):
File "/usr/lib/enigma2/python/mytest.py", line 6, in <module>
from Tools.Profile import profile, profile_final
ImportError: No module named Tools.Profile
```

any help on this????

**Comment by atvcaptain** [comment]
its not a oe-a issue send issue request to github.com/carlo0815/openNFR-gui2.git

**Comment by ahmedmoselhi** [comment]
> its not a oe-a issue send issue request to github.com/carlo0815/openNFR-gui2.git

Solved BTW
