### ISSUE TITLE
[pycrypto] time.clock() no longer supported in python3.8

### ISSUE THREAD

**Issue by Billy2011** [oe-alliance/oe-alliance-core#626]
Please replace pycrypto by pycryptodome and don't provide that as two independent packages.

**Comment by nickersk** [comment]
now you can use ${PYTHON_PN}- pycryptodome
- see https://github.com/oe-alliance/oe-alliance-core/commit/5673bb09f8217e50af02d68cae09ca3248b1a00d

**Comment by Billy2011** [comment]
If it's possible, you should change that at least in the 4.4 branch too, because for Streamlink also the padding utility is needed, which does not exist with pycrypto.

**Comment by atvcaptain** [comment]
allready fixed
