### ISSUE TITLE
No transponders found on Hitube4k Combo Blindscan

### ISSUE THREAD

**Issue by linuxstv** [oe-alliance/oe-alliance-core#627]
Hi guys. Am I the only who are experiencing this issue?

Not even a tranponder can be found by the Blindscan on my Hitube4k Combo. I use OpenATV 6.4.

![vlcsnap-2020-08-23-12h10m55s580](https://user-images.githubusercontent.com/15664372/90971414-2a5fb280-e53a-11ea-9865-09adacb57e4d.png)

![vlcsnap-2020-08-23-12h10m44s637](https://user-images.githubusercontent.com/15664372/90971418-351a4780-e53a-11ea-822e-8878b174bc8e.png)

**Comment by Huevos** [comment]
Where are you located? What aerial are you using?

**Comment by linuxstv** [comment]
I'm in Indonesia (Asia). I can make sure that the signals are good at my location. Here's a screenshot of a channel which is locked using manual search.

![vlcsnap-2020-08-23-08h19m29s341](https://user-images.githubusercontent.com/15664372/90974295-1032ce00-e554-11ea-8f27-36203d683ff2.png)

**Comment by atvcaptain** [comment]
i send the issue to dinobot

**Comment by atvcaptain** [comment]
dinobot stop support, no new updates anymore
