### ISSUE TITLE
HDMI-CEC not working for sh4

### ISSUE THREAD

**Issue by ahmedmoselhi** [oe-alliance/oe-alliance-core#630]
i use oe-allience 4.4 to build sh4 images but every image i build (openatv , openvix , ....) hdmi-cec not working
it works well on openpli-based images though.\could this be a driver issue or hdmi-cec plugin issue???

**Comment by ahmedmoselhi** [comment]
no reply???

**Comment by linuxstv** [comment]
Have you tried official OpenATV image to compare with your own build?

**Comment by atvcaptain** [comment]
sorry sh4 support was end, have any a solution please send a fix
