### ISSUE TITLE
SourceForge mirror no longer at mirrorservice.org

### ISSUE THREAD

**Issue by original-birdman** [oe-alliance/oe-alliance-core#632]
The
```
SRC_URI = "http://sourceforge.mirrorservice.org/l/li/libcddb/libcddb/${PV}/${BP}.tar.bz2"
```
no longer works, as there is no longer a SourceForge mirror at mirrorservice.org.

This needs to be changed to (possibly):
```
SRC_URI = "http://prdownloads.sourceforge.net/libcddb/${BP}.tar.bz2"
```

**Comment by nickersk** [comment]
fixed here: https://github.com/oe-alliance/oe-alliance-core/commit/8527aba2bce6184750563980d1304c1188940c5d
