### ISSUE TITLE
uclan ustym4kpro kernel compile error

### ISSUE THREAD

**Issue by zKhadiri** [oe-alliance/oe-alliance-core#635]
`ERROR: linux-uclan-4.4.35-31 do_compile: oe_runmake failed
ERROR: linux-uclan-4.4.35-31 do_compile: Execution of '/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802' failed with exit code 1:
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work-shared/ustym4kpro/kernel-source as source for kernel
  HOSTLD  scripts/dtc/dtc
/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/hosttools/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[4]: *** [scripts/Makefile.host:100: scripts/dtc/dtc] Error 1
make[3]: *** [/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work-shared/ustym4kpro/kernel-source/scripts/Makefile.build:403: scripts/dtc] Error 2
make[2]: *** [/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work-shared/ustym4kpro/kernel-source/Makefile:556: scripts] Error 2
make[2]: *** Waiting for unfinished jobs....
  Generating include/generated/mach-types.h
make[1]: *** [Makefile:150: sub-make] Error 2
make: *** [Makefile:24: __sub-make] Error 2
WARNING: /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802:302 exit 1 from 'exit 1'
WARNING: Backtrace (BB generated script): 
	#1: bbfatal_log, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 302
	#2: die, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 292
	#3: oe_runmake, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 199
	#4: kernel_do_compile, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 188
	#5: do_compile, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 148
	#6: main, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 306

Backtrace (metadata-relative locations):
	#1: bbfatal_log, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/openembedded-core/meta/classes/logging.bbclass, line 72
	#2: die, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/openembedded-core/meta/classes/base.bbclass, line 56
	#3: oe_runmake, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/openembedded-core/meta/classes/base.bbclass, line 65
	#4: kernel_do_compile, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/openembedded-core/meta/classes/kernel.bbclass, line 349
	#5: do_compile, autogenerated, line 2
ERROR: Logfile of failure stored in: /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/log.do_compile.1027802
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 10 HOSTCC=gcc  -isystem/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/usr/include -O2 -pipe -L/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/usr/lib                         -L/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/lib                         -Wl,-rpath,/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/lib                         -Wl,-O1 HOSTCPP=gcc  -E HOSTCXX=g++  -isystem/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/usr/include -O2 -pipe -L/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/usr/lib                         -L/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/lib                         -Wl,--enable-new-dtags                         -Wl,-rpath-link,/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/usr/lib                         -Wl,-rpath-link,/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/lib                         -Wl,-rpath,/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/usr/lib                         -Wl,-rpath,/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native/lib                         -Wl,-O1 uImage CC=arm-oe-linux-gnueabi-gcc   -fuse-ld=bfd -fmacro-prefix-map=/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31=/usr/src/debug/linux-uclan/4.4.35-31                      -fdebug-prefix-map=/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31=/usr/src/debug/linux-uclan/4.4.35-31                      -fdebug-prefix-map=/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot=                      -fdebug-prefix-map=/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/recipe-sysroot-native=  -fdebug-prefix-map=/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work-shared/ustym4kpro/kernel-source=/usr/src/kernel   LD=arm-oe-linux-gnueabi-ld.bfd   EXTRA_CFLAGS=-Wno-attribute-alias
|   GEN     ./Makefile
| scripts/kconfig/conf  --silentoldconfig Kconfig
|   CHK     include/config/kernel.release
|   GEN     ./Makefile
|   CHK     include/generated/uapi/linux/version.h
|   CHK     include/generated/utsrelease.h
|   Using /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work-shared/ustym4kpro/kernel-source as source for kernel
|   HOSTLD  scripts/dtc/dtc
| /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/hosttools/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
| collect2: error: ld returned 1 exit status
| make[4]: *** [scripts/Makefile.host:100: scripts/dtc/dtc] Error 1
| make[3]: *** [/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work-shared/ustym4kpro/kernel-source/scripts/Makefile.build:403: scripts/dtc] Error 2
| make[2]: *** [/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work-shared/ustym4kpro/kernel-source/Makefile:556: scripts] Error 2
| make[2]: *** Waiting for unfinished jobs....
|   Generating include/generated/mach-types.h
| make[1]: *** [Makefile:150: sub-make] Error 2
| make: *** [Makefile:24: __sub-make] Error 2
| ERROR: oe_runmake failed
| WARNING: /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802:302 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 302
| 	#2: die, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 292
| 	#3: oe_runmake, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 199
| 	#4: kernel_do_compile, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 188
| 	#5: do_compile, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 148
| 	#6: main, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 306
| ERROR: Execution of '/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802' failed with exit code 1:
|   GEN     ./Makefile
| scripts/kconfig/conf  --silentoldconfig Kconfig
|   CHK     include/config/kernel.release
|   GEN     ./Makefile
|   CHK     include/generated/uapi/linux/version.h
|   CHK     include/generated/utsrelease.h
|   Using /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work-shared/ustym4kpro/kernel-source as source for kernel
|   HOSTLD  scripts/dtc/dtc
| /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/hosttools/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
| collect2: error: ld returned 1 exit status
| make[4]: *** [scripts/Makefile.host:100: scripts/dtc/dtc] Error 1
| make[3]: *** [/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work-shared/ustym4kpro/kernel-source/scripts/Makefile.build:403: scripts/dtc] Error 2
| make[2]: *** [/home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work-shared/ustym4kpro/kernel-source/Makefile:556: scripts] Error 2
| make[2]: *** Waiting for unfinished jobs....
|   Generating include/generated/mach-types.h
| make[1]: *** [Makefile:150: sub-make] Error 2
| make: *** [Makefile:24: __sub-make] Error 2
| WARNING: /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802:302 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 302
| 	#2: die, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 292
| 	#3: oe_runmake, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 199
| 	#4: kernel_do_compile, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 188
| 	#5: do_compile, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 148
| 	#6: main, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/builds/openatv/release/ustym4kpro/tmp/work/ustym4kpro-oe-linux-gnueabi/linux-uclan/4.4.35-31/temp/run.do_compile.1027802, line 306
| 
| Backtrace (metadata-relative locations):
| 	#1: bbfatal_log, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/openembedded-core/meta/classes/logging.bbclass, line 72
| 	#2: die, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/openembedded-core/meta/classes/base.bbclass, line 56
| 	#3: oe_runmake, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/openembedded-core/meta/classes/base.bbclass, line 65
| 	#4: kernel_do_compile, /home/zakaria/oe-alliance/new-nextp3/build-enviroment/openembedded-core/meta/classes/kernel.bbclass, line 349
| 	#5: do_compile, autogenerated, line 2
ERROR: Task (/home/zakaria/oe-alliance/new-nextp3/build-enviroment/meta-oe-alliance/meta-brands/meta-uclan/recipes-linux/linux-uclan_4.4.35.bb:do_compile) failed with exit code "1"`

**Comment by nickersk** [comment]
fixed here: https://github.com/oe-alliance/oe-alliance-core/commit/8966c993a3a53dfef66a7afa5b1f6ed137a5d0b9
thx for reporting.
