### ISSUE TITLE
Build OverlayHD skin from the git

### ISSUE THREAD

**Issue by persianpros** [oe-alliance/oe-alliance-core#643]
Hello,

Here's the new home of @IanSav skin: https://github.com/IanSav/OverlayHD

We have a ready bitbake recpie for it: https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/meta-openvision/recipes-openvision/enigma2-skins/enigma2-plugin-skins-overlayhd.bb

Which you can adapt for your OE.

Just to let you know :+1: 

Regards,
Persian Prince

**Comment by Huevos** [comment]
If Ian wants to add this he is welcome to make a pull request.

**Comment by persianpros** [comment]
You have it as a pre-compiled ipk in https://github.com/oe-alliance/3rdparty-plugins and I think Ian isn't so familiar with bitbake so better to add the recipe yourself as you have the build and could check what's needed in OE-A

**Comment by jbleyel** [comment]
https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/meta-openvision/recipes-openvision/enigma2-skins/enigma2-plugin-skins-overlayhd.bb -> Error 404
