### ISSUE TITLE
kodiext from OpenSPA team

### ISSUE THREAD

**Issue by rdcalle** [oe-alliance/oe-alliance-core#644]
How about using the https://github.com/OpenSPA/kodiext instead the one got from https://github.com/mx3L/kodiext?
The OpenSPA team is doing a great job with it.

**Comment by atvcaptain** [comment]
but openspa not share the infos and send back the updates to oe-a,

**Comment by rdcalle** [comment]
Well, they shared all about the Kodi stuff a few time ago. And kodiext is a
plugin to be used by Kodi.

Wouldn't that be a good idea if it's more updated that the other one?

**Comment by atvcaptain** [comment]
need kodi a update too for this change , openspa kodi git not public

**Comment by OpenSPA** [comment]
Hello, our kodiext git is public and everybody can use it. All kodi development is shared as well, but kodiext and kodi are not the same.

GIT for kodiext : https://github.com/OpenSPA/kodiext

and this converter is needed for kodiext: https://github.com/OpenSPA/dvbapp2/blob/master/lib/python/Components/Converter/TrackInfo.py

**Comment by ahmedmoselhi** [comment]
> Hello, our kodiext git is public and everybody can use it. All kodi development is shared as well, but kodiext and kodi are not the same.
> 
> GIT for kodiext : https://github.com/OpenSPA/kodiext
> 
> and this converter is needed for kodiext: https://github.com/OpenSPA/dvbapp2/blob/master/lib/python/Components/Converter/TrackInfo.py

why not sharing spaze menu and plugins too?? @OpenSPA

**Comment by ahmedmoselhi** [comment]
> Hello, our kodiext git is public and everybody can use it. All kodi development is shared as well, but kodiext and kodi are not the same.
> 
> GIT for kodiext : https://github.com/OpenSPA/kodiext
> 
> and this converter is needed for kodiext: https://github.com/OpenSPA/dvbapp2/blob/master/lib/python/Components/Converter/TrackInfo.py

why not sharing spaze menu and plugins too?? @OpenSPA

**Comment by atvcaptain** [comment]
now merge to oe-a thx for the info
