### ISSUE TITLE
libssl and libcrypto missing shortcuts

### ISSUE THREAD

**Issue by jeepcook** [oe-alliance/oe-alliance-core#652]
Hello,

On some programs, libssl.so.0.9.8 and libcrypto.so.0.9.8 are needed and unable to mod this value into the program.

1.0.2 versions for this 2 libraries are linked to 0.9.7 and 1.0.0 versions. So I think 0.9.8 is frequently used, so a shortcut to this version has to be added.

```
cd /usr/lib
ln -sf libssl.so.1.0.2 libssl.so.0.9.8
ln -sf libcrypto.so.1.0.2 libcrypto.so.0.9.8
```

Thanks.

Regards

**Comment by AbuBaniaz** [comment]
This was brought up a few years ago. There are a few odd occasions when the 0.98 itself is required, this is why the symlink was not added.

Ideally, the people who made the oscam-emu patched binary for tntsat can amend it so it does not depend on the old version of libssl existing or a symlink. It obviously works on newer versions anyway. Better still add the patch to the oscam-emu directly.

**Comment by jeepcook** [comment]
Thanks for the answer. I'm ok with you.

**Comment by AbuBaniaz** [comment]
Also, I think there is a libcrypto compat package defined which will add the 0.98 symlink.

**Comment by AbuBaniaz** [comment]
https://github.com/oe-alliance/oe-alliance-core/blob/4.4/meta-oe/recipes-connectivity/openssl/libcrypto-compat-0.9.8.bb

Not too sure if it is built.

**Comment by jeepcook** [comment]
Yes probably, I will look at the content of compat package and find the good version

**Comment by jeepcook** [comment]
No I's not build. Test with my own oatv 6.4 compilation and the official one, this link isn't build

**Comment by AbuBaniaz** [comment]
Try libxcrypt-compat

Otherwise 0.98 will need to be added here if it does not clash with anything
https://github.com/oe-alliance/oe-alliance-core/blob/4.4/meta-oe/recipes-oe-alliance/image/oe-alliance-base.bb#L43:L45

**Comment by jeepcook** [comment]
libxcrypt-compat is already installed (v4.4.8-r0), and the following too. Nothing for 0.9.8

libcrypto-compat-0.9.7 - 1.0-r0 - Compatibility for packages that link to libcrypto or libssl 0.9.7
libcrypto-compat-1.0.0 - 1.1-r0 - Compatibility for packages that link to libcrypto or libssl 1.0.0

**Comment by jeepcook** [comment]
Sorry made a mistake in my previous post, I edited it.

**Comment by jeepcook** [comment]
Hello, 
To implement this mod, I have to use nextp3 as dev 4.4 branch ?
Thanks

**Comment by atvcaptain** [comment]
openssl-old_0.9.8x  build correct  libs we cant add the link to default image, better add depends to cams ipk

**Comment by jeepcook** [comment]
OK with closure. It's an old demand.

Just a question, why not remove links to 0.9.7 too, older than 0.9.8?
libcrypto.so.0.9.7 -> libcrypto.so.1.0.2
libssl.so.0.9.7 -> libssl.so.1.0.2
