### ISSUE TITLE
TM Nano 3T Combo bootloop

### ISSUE THREAD

**Issue by AbuBaniaz** [oe-alliance/oe-alliance-core#653]
I am getting a bootloop when flashing 'openatv-6.4-tmnano3t-20210303_usb` or a homebuild Vix 5.4 image. Last 6.3 image I can find is  `openatv-6.3-tmnano3t-20210103_usb`, That also bootloops. Last official Vix image image works fine.

Is this the commit that caused it?
https://github.com/oe-alliance/oe-alliance-core/commits/4.3/meta-brands/meta-dags/recipes-linux/linux-dags-3.9.7/dags7356

```
UBIFS: background thread "ubifs_bgt0_0" stops
List of all partitions:
0800       244198584 sda  driver: sd
  0801       244197376 sda1 1b99615d-1c32-47c4-841a-da9fd9479cfc
1f00          250880 mtdblock0  (driver?)
1f01          250880 mtdblock1  (driver?)
1f02           10240 mtdblock2  (driver?)
1f03            8192 mtdblock3  (driver?)
No filesystem could mount root, tried:  ubifs
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(8,1)
Rebooting in 1 seconds..
------------[ cut here ]------------
WARNING: at /home/oe1/atv64/build-enviroment/builds/openatv/release/dags7356/tmp/work-shared/dags7356/kernel-source/kernel/smp.c:381 smp_call_function_many+0x114/0x3a0()
Modules linked in:
Call Trace:
[<80612b00>] dump_stack+0x8/0x34
[<80613ad4>] warn_slowpath_common+0x74/0xa0
[<80025188>] warn_slowpath_null+0x18/0x24
[<8007f7d8>] smp_call_function_many+0x114/0x3a0
[<8007fa88>] smp_call_function+0x24/0x34
[<8000225c>] brcm_machine_restart+0x10/0x44
[<806139f0>] panic+0x17c/0x1ec
[<807acfec>] mount_root+0x0/0x120

---[ end trace 377daf67049fc180 ]---
```
I have tried with HDD disconnected, still bootloops.

[atv 6.3_20210103_bootloop.log](https://github.com/oe-alliance/oe-alliance-core/files/6079421/atv.6.3_20210103_bootloop.log)
[atv 6.4_20210303_bootloop.log](https://github.com/oe-alliance/oe-alliance-core/files/6079422/atv.6.4_20210303_bootloop.log)
[flash atv 6.3_20210103_usb.log](https://github.com/oe-alliance/oe-alliance-core/files/6079423/flash.atv.6.3_20210103_usb.log)
[flash atv 6.4_20210303_usb.log](https://github.com/oe-alliance/oe-alliance-core/files/6079424/flash.atv.6.4_20210303_usb.log)
[ViX 5.4 homebuild bootloop.log](https://github.com/oe-alliance/oe-alliance-core/files/6079425/ViX.5.4.homebuild.bootloop.log)

**Comment by atvcaptain** [comment]
update to last cfe this fix your bootloop  https://www.opena.tv/bootloader/download-411-technomate-tm-nano-3t-combo-cfe-bootloader.html
