### ISSUE TITLE
VP9 decoding for Edision OS Mega?

### ISSUE THREAD

**Issue by oxydicer** [oe-alliance/oe-alliance-core#666]
Hello everybody,

would it be possible to add VP9 video decoding to the configuration of the Edision OS Mega?
That is, add an '--with-vb9' to meta-brands/meta-xcore/conf/machine/include/xcore-oem.inc to the 
osmega, line 111, which up to now reads
`    ${@bb.utils.contains('MACHINEBUILD', 'osmega', '--with-h265 --with-vb6 --with-vb8 --with-spark' , '', d)} \
`

Would that be technically feasible?

Kind regards,

oxydicer

**Comment by atvcaptain** [comment]
Unfortunately, 73565 of osmega can’t decode VP9. Please refer to the following capture of its decoding capability.

![image](https://user-images.githubusercontent.com/974786/116037739-ccefa880-a668-11eb-8772-fb5171fe4b7b.png)
