### ISSUE TITLE
Remove buggy dinobot player

### ISSUE THREAD

**Issue by technic** [oe-alliance/oe-alliance-core#676]
Hi,
this is a cross post from [openatv forum](
https://www.opena.tv/jamesdonkey-duo-hd/56204-remove-buggy-dinobot-player.html). I don't know where it is better to report such issues (?) 

The device jdhdduo has the u42 software revision. This revision includes dinobot player https://github.com/oe-alliance/oe-alliance-core/commit/a9cfc6f4a52ff621f7d1ebefd545b33ea0664546.

This player is quite buggy and does not work well on my device. However I can flash the u41 image from another box, which uses usual gstreamer based servicemp3 player. Then player works really good. However, the sat-tv does not work with this image, due to incompatible drivers I guess.

Why do you provide such buggy dinobot player? Can you remove it? Can you make it at least as an alternative service id? 

Thanks

**Comment by atvcaptain** [comment]
forget to close , player removed
