### ISSUE TITLE
minilocale: LC_TIME not working

### ISSUE THREAD

**Issue by mjfwalsh** [oe-alliance/oe-alliance-core#701]
This is hardly the most important bug, but when I log into the terminal of my enigma2 box I was getting the following error:

    -bash: warning: setlocale: LC_TIME: cannot change locale (C.UTF-8): No such file or directory
    -bash: warning: setlocale: LC_TIME: cannot change locale (en_GB.UTF-8): No such file or directory

And whatever I tried to set LC_TIME it returned either

    -bash: warning: setlocale: LC_TIME: cannot change locale (C.UTF-8)

or

    -bash: warning: setlocale: LC_TIME: cannot change locale (C.UTF-8): No such file or directory

I've traced the problem back the the LC_TIME files themselves. Minilocale was compiled using glibc 2.27 while my box uses glibc 2.23. I don't think it's any guarantee of compatibility between different versions. 

When I reverted to minilocale's original version (commit 455c945965), LC_TIME started working again.

**Comment by atvcaptain** [comment]
np here with branch 4.4, 5.0 and 5.1 images, old image support was stopped
