### ISSUE TITLE
openhbbtv

### ISSUE THREAD

**Issue by 68foxboris** [oe-alliance/oe-alliance-core#708]
Good afternoon.Please tell me where I could have gone wrong when assembling openhbbtv for ultimo4k.
Ubuntu 21.04.Error do_configure qtbase.There are several bugs.
`
> main.cpp:7:8: error: #error Intel CET not available
>     7 |     #  error Intel CET not available
>       |        ^~~~~
> make: *** [Makefile:174: main.o] Error 1
test config.qtbase.tests.intelcet FAILED
`

`
> main.cpp:3:4: error: #error Symbolic function binding on this architecture may be broken, disabling it (see QTBUG-36129).
>     3 | #  error Symbolic function binding on this architecture may be broken, disabling it (see QTBUG-36129).
>       |    ^~~~~
> make: *** [Makefile:194: main.o] Error 1
test config.qtbase.tests.reduce_relocations FAILED
`
`
> main.cpp:2:10: fatal error: zstd.h: No such file or directory
>     2 | #include <zstd.h>
>       |          ^~~~~~~~
> compilation terminated.
> make: *** [Makefile:174: main.o] Error 1
 => source failed verification.
test config.qtbase.libraries.zstd FAILED
`

`
> main.cpp:8:12: fatal error: gssapi/gssapi.h: No such file or directory
>     8 | #  include <gssapi/gssapi.h>
>       |            ^~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:176: main.o] Error 1
 => source failed verification.
test config.qtbase_network.libraries.gssapi FAILED
`

`
Checking for XLib... 
Trying source 0 (type makeSpec) of library xlib ...
X11/Xlib.h not found in [] and global paths.
  => source produced no result.
test config.qtbase_gui.libraries.xlib FAILED
`

`
Project ERROR: Test config.qtbase_gui.tests.egl-libvupl tries to use undeclared library 'vupl'
`

**Comment by atvcaptain** [comment]
openhbbtv not ready for vu, we wait for a driver fix but no response from vu, last patches not include in public git

**Comment by 68foxboris** [comment]
Thanks.
