### ISSUE TITLE
gcc-cross-initial_4.9.bb recipe fails on a Ubuntu 21.10 Build Server

### ISSUE THREAD

**Issue by nanotux1** [oe-alliance/oe-alliance-core#742]
gcc-cross-initial_4.9.bb recipe fails on a Ubuntu 21.10 Build Server with the following error message:

| ../../../../../../../work-shared/gcc-4.9.4-r0/gcc-4.9.4/gcc/reload1.c: In function ‘void init_reload()’:
| ../../../../../../../work-shared/gcc-4.9.4-r0/gcc-4.9.4/gcc/reload1.c:89:24: error: use of an operand of type ‘bool’ in ‘operator++’ is forbidden in C++17

Please fix it. I think the solution should be to set C Flags in the bb file.

**Comment by atvcaptain** [comment]
old issue we use now gcc 6.2.2
