### ISSUE TITLE
LNB controler A8304 add request please 

### ISSUE THREAD

**Issue by rebainoor** [oe-alliance/oe-alliance-core#743]
Can you add LNB CTRL A8304 please 
My config is :
Tuner : 2x RDA5815M
DEMODELATOR : HI3136
LNB CONTROLER : A8304
CAS SUPPORT + bluetooth+ wifi +SATA

**Comment by atvcaptain** [comment]
i cant see linux kernel support this have  you more infos

**Comment by rebainoor** [comment]
https://github.com/SiliconLabs/video_si21xx_superset/tree/master/SILABS_SUPERSET/SAT/LNB/A8304
Its possible to add it ?

https://github.com/zhe2lucifer/linux-kernel-zh/tree/8fb05a60b37d48a9f2f5b95d9452fd3f081e82a2/drivers/alidrivers/modules/alinim/lnb_a8304

**Comment by atvcaptain** [comment]
we cant support this sorry we close the request
