### ISSUE TITLE
oatv7 E2-image only build fail for boxes with flashsize 64/96

### ISSUE THREAD

**Issue by dazulrich** [oe-alliance/oe-alliance-core#744]
Hi, 
Since commit
https://github.com/oe-alliance/oe-alliance-core/commit/940d85e96118479cc5aed60d10feb6a2f7185f8b 
Some (all ??) boxes with flashsize 64 or 96 fail to build using "make enigma2-image". (unless feeds had been build separately first)

The change in  openatv-base.bb **wireless-tools** conditional on FLASHSIZE > 96 is dependent on the inclusion of **nowifi** in the MACHINE_FEATURES  for each box! 
Otherwise the build fails.

Can the conditional RDEPENDS of wireless-tool be reverted?  
Or otherwise nowifi should to get added to all the boxes that have small flashsize and no built in wifi. 

Either approach was working for my SF3038.

**Comment by atvcaptain** [comment]
yes i know, we fix it

**Comment by dazulrich** [comment]
thanks !
