### ISSUE TITLE
ntpdate-sync does not work on dm920 some thing missing in proc ...

### ISSUE THREAD

**Issue by fairbird** [oe-alliance/oe-alliance-core#760]
> Welcome to openATV for dm920
openatv 7.1 dm920
dm920 login: root
Password: 
root@dm920~# /sbin/stb-hwclock --systohc
/sbin/stb-hwclock: line 24: /proc/stb/fp/rtc: No such file or directory
root@dm920~# 
root@dm920~# /usr/bin/ntpdate-sync
/sbin/stb-hwclock: line 24: /proc/stb/fp/rtc: No such file or directory
root@dm920~#

**Comment by original-birdman** [comment]
This is surely a bug in `/sbin/stb-hwclock` rather than in `ntpdate-sync`?
