### ISSUE TITLE
EmbyDream plugin porting?

### ISSUE THREAD

**Issue by Thomas-O** [oe-alliance/oe-alliance-core#762]
Hello,

I hope you'll forgive me if this isn't the appropriate forum to ask this question.

Q. Is any work been done to port the EmbyDream (server) Enigma2 plugin to OE 5.0?

I have an Emby server on a Pi3. While the server connects without issue to my Roku client, the menu browsing and initiating playback is very slow and laggardly. I suspect that an EmbyDream plugin on a device like my Amiko viper 4k v40 would provide a better experience. Though I could be horribly wrong about this.
 
 Thanks for your time
 
 Thomas

**Comment by enigmawelt** [comment]
Can only give information for the OpenATV feed. Is there on the IPK feed as py3 version, because the developer does not version in Git! Can be closed
