### ISSUE TITLE
The rclone recipe creates a "go" directory of go modules into the builder's HOME directory.

### ISSUE THREAD

**Issue by original-birdman** [oe-alliance/oe-alliance-core#765]

**Comment by original-birdman** [comment]
Any build process should make _no_ change to the HOME of the running account.

A work around is top set a build-specific HOME before running `bitbake`, but it would be preferable if the `bitbake` recipe handled this itself.

**Comment by atvcaptain** [comment]
change this local , we use default

**Comment by original-birdman** [comment]
So, even when it's nonsensical, useless and incorrect - you'll stick with it.
Do you *really* make no changes at all from the default build in *any* \*.bb config files?

**Comment by original-birdman** [comment]
Do you intend to remove all patch files from `oe-alliance-core`, so that everything is the default build?
