### ISSUE TITLE
qtbase 5.15

### ISSUE THREAD

**Issue by amoldhamale1105** [oe-alliance/oe-alliance-core#767]
Building a qt image for raspberry pi 2 from the kirkstone poky release. Host machine is Ubuntu 20.04
[qtBuildErrorLog.txt](https://github.com/oe-alliance/oe-alliance-core/files/8793888/qtBuildErrorLog.txt)

**Comment by atvcaptain** [comment]
we are oe-a not qt, please send report to other git

**Comment by amoldhamale1105** [comment]
I saw another meta-qt layer related issue being discussed here hence asked
