### ISSUE TITLE
Optimuss OS3+ and drivers

### ISSUE THREAD

**Issue by DimitarCC** [oe-alliance/oe-alliance-core#77]
There is huge problems with optimuss OS3+ and BCM7356 drivers.....
first when tuner loop is enabled there is frequent kernel crash(and also CPU temp rise abnormally).
Also enigma2 UI is totally bugged and subtitles dont rendering correct. (see screen below)
![1_0_1_3eb_1_1_18630ec_0_0_0](https://cloud.githubusercontent.com/assets/1904901/5691255/a861e8e6-98c5-11e4-904b-4131f51bfdd6.jpg)

**Comment by arn354** [comment]
driver issue - ask manufacturer to fix drivers.
