### ISSUE TITLE
samba-4.15.6-r1

### ISSUE THREAD

**Issue by elhawaryna** [oe-alliance/oe-alliance-core#770]
ERROR: samba-4.15.6-r1 do_package_qa: QA Issue: /usr/bin/smbclient contained in package smbclient requires liblibsmb-samba4.so, but no providers found in RDEPENDS:smbclient? [file-rdeps]
ERROR: samba-4.15.6-r1 do_package_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/elhawary/build-enviroment/builds/openatv/release/dm820/tmp/work/mips32el-oe-linux/samba/4.15.6-r1/temp/log.do_package_qa.2695466
ERROR: Task (/home/elhawary/build-enviroment/meta-oe-alliance/meta-oe/recipes-connectivity/samba/samba.bb:do_package_qa) failed with exit code '1'

**Comment by nickersk** [comment]
https://github.com/oe-alliance/oe-alliance-core/issues/750
