### ISSUE TITLE
Strange colours on front panel LCD (GigaBlue Quad Plus)

### ISSUE THREAD

**Issue by outrageuk** [oe-alliance/oe-alliance-core#777]
I have the same issue on OpenVIX 6.2, as I had on OpenVIX 5.2 after driver update. Has this fix been removed for some reason? 

Blue tint on front LCD as here...

https://www.world-of-satellite.com/showthread.php?59392-Strange-colours-on-front-panel-after-latest-driver-update

Issue ... 
https://github.com/oe-alliance/oe-alliance-core/issues/301

**Comment by atvcaptain** [comment]
its not oe-a issue, send issue report to openvix e2
