### ISSUE TITLE
Skin 'PLi scale HD'

### ISSUE THREAD

**Issue by RobvanderDoes** [oe-alliance/oe-alliance-core#8]
I suggest to remove the enigma2-plugin-skins-pli-scale-hd completely. It was a never completed trial and developments stopped over 6 months ago.

**Comment by Schimmelreiter** [comment]
Closed with https://github.com/oe-alliance/oe-alliance-core/commit/31e32bf39d64edb5d1a7cfae3ffd6feee5073cbc
