### ISSUE TITLE
Disk Usage/Free Utility 'duf'

### ISSUE THREAD

**Issue by enigmawelt** [oe-alliance/oe-alliance-core#812]
Is it possible to offer the Disk Usage/Free Utility 'duf' via the feeds or directly in bash ... https://github.com/muesli/duf

**Comment by nickersk** [comment]
hi, have you tried ncdu?

**Comment by enigmawelt** [comment]
Nope. I will look.

**Comment by enigmawelt** [comment]
Does not know the bash of ATV7.2 and a package is also not found. it is ncurses?

**Comment by nickersk** [comment]
ah, bb recipe is there, just not building within feed ... i baked it locally... https://github.com/oe-alliance/oe-alliance-core/blob/5.2/meta-oe/recipes-extended/ncdu/ncdu_1.8.bb

**Comment by nickersk** [comment]
https://dev.yorhel.nl/ncdu

**Comment by jbleyel** [comment]
ncdu is on the feed
