### ISSUE TITLE
.bash_profile not working

### ISSUE THREAD

**Issue by jeepcook** [oe-alliance/oe-alliance-core#816]
Hello, 

With the 5.2 and openatv 7.2, the content of .bash_profile is not executed. Example, in mine there is just alias ll='ls -al' and the command ll doesn't work, I have to execute manually the alias command.
No problem in 7.1 EOL.

Thanks

**Comment by nickersk** [comment]
`login as: root`
`root@vusolose:~# ll`
`-sh: ll: command not found`

`root@vusolose:~# echo "alias ll='ls -la'" > .profile`
`root@vusolose:~# more .profile`
`alias ll='ls -la'`

**AFTER RELOGIN:**
`root@vusolose:~# ll`
`drwx------    8 root     root           904 Jan 25 11:28 .`
`drwxr-xr-x    3 root     root           224 Dec  1 06:22 ..`

**Comment by jeepcook** [comment]
Hell nickersk, 
it's ok now using .profile instead of .bash_profile.
Thanks for your help !!
