### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by elhawaryna** [oe-alliance/oe-alliance-core#824]
root@dm820:~# ENIGMA_DEBUG_LVL=4 enigma2
19:09:17.8105 [Enigma] Python path is '/usr/lib/enigma2/python'.
19:09:17.8110 [Enigma] DVB API version 5, DVB API version minor 11.
19:09:17.8111 [Enigma] Enigma debug level 4.
19:09:17.9849 [Avahi] avahi_watch_new(3 0x1)
19:09:17.9897 [Avahi] client state: 2
19:09:17.9914 [eInit] + (1) Background File Eraser
19:09:17.9918 [eInit] + (5) Tuxtxt
19:09:17.9919 [eInit] + (8) graphics acceleration manager
19:09:17.9928 [eInit] + (9) Font Render Class
19:09:17.9930 [Font] Initializing lib.
19:09:17.9934 [Font] Loading fonts.
19:09:17.9936 [Font] Intializing font cache, using max. 4MB.
19:09:17.9939 [eInit] + (9) gLCD
19:09:17.9940 [eFbLCD] /dev/fb1: Function not implemented
19:09:17.9942 [eFbLCD] framebuffer /dev/fb1 not available
19:09:17.9945 [eLCD] found OLED display!
19:09:17.9950 [eDboxLCD] xres=96, yres=64, bpp=16 lcd_type=3
19:09:17.9952 [eLCD] (96x64x16) buffer 0xbf2988 12288 bytes, stride 192, boxtype: dm820

19:09:17.9954 [gLCDDC] resolution: 96x64x16 stride=192
19:09:17.9955 [eInit] + (9) GFBDC
19:09:17.9957 [fb] /dev/fb0: 7200k video mem
19:09:17.9959 [fb] Using ION allocator
19:09:17.9964 [fb] 32768kB available for acceleration surfaces (via ION).
19:09:18.0160 [fb] double buffering available!
19:09:18.0162 [fb] 2 page(s) available!
19:09:18.1549 [gFBDC] resolution: 1280 x 720 x 32 (stride: 5120) pages: 2
19:09:18.1552 [eInit] + (10) gRC
19:09:18.1557 [gRC] Thread created successfully.
19:09:18.1559 [eInit] + (15) eWindowStyleManager
19:09:18.1560 [eInit] + (20) AVSwitch Driver
19:09:18.1562 [eAVSwitch] failed to open /dev/dbox/fp0 to monitor vcr scart slow blanking changed: Function not implemented
19:09:18.1563 [eInit] + (20) misc options
19:09:18.1565 [eInit] + (20) RC Input layer
19:09:18.1566 [eInit] + (20) UHF Modulator
19:09:18.1568 [eRFmod] couldnt open /dev/rfmod0: Function not implemented
19:09:18.1569 [eInit] + (20) DVB-CI UI
19:09:18.1570 [eInit] + (21) input device driver
19:09:18.1573 [eInputDeviceInit] adding device /dev/input/event0
19:09:18.1575 [eRCInputEventDriver] devicename=dreambox front panel
19:09:18.1577 [eRCInputEventDriver] devicename=dreambox front panel
19:09:18.1578 [eRCDeviceInputDev] device "dreambox front panel" is a remotecontrol
19:09:18.1580 [eInputDeviceInit] adding device /dev/input/event1
19:09:18.1582 [eRCDeviceInputDev] device "dreambox advanced remote control (native)" is a remotecontrol
19:09:18.1584 [eInputDeviceInit] adding device /dev/input/event2
19:09:18.1586 [eRCInputEventDriver] devicename=dreambox advanced remote control (native)
19:09:18.1587 [eRCInputEventDriver] devicename=dreambox advanced remote control (native)
19:09:18.1588 [eRCDeviceInputDev] device "dreambox advanced remote control (native)" is a remotecontrol
19:09:18.1590 [eInputDeviceInit] adding device /dev/input/event3
19:09:18.1591 [eRCInputEventDriver] devicename=dreambox ir keyboard
19:09:18.1592 [eRCInputEventDriver] devicename=dreambox ir keyboard
19:09:18.1594 [eRCDeviceInputDev] device "dreambox ir keyboard" is a keyboard
19:09:18.1595 [eInputDeviceInit] adding device /dev/input/event4
19:09:18.1597 [eRCInputEventDriver] devicename=dreambox ir mouse
19:09:18.1598 [eRCInputEventDriver] devicename=dreambox ir mouse
19:09:18.1599 [eRCDeviceInputDev] device "dreambox ir mouse" is a mouse
19:09:18.1601 [eInputDeviceInit] adding device /dev/input/event5
19:09:18.1602 [eRCInputEventDriver] devicename=dreambox remote control (bluetooth le)
19:09:18.1604 [eRCInputEventDriver] devicename=dreambox remote control (bluetooth le)
19:09:18.1605 [eRCDeviceInputDev] device "dreambox remote control (bluetooth le)" is a remotecontrol
19:09:18.1607 [eInputDeviceInit] Found 6 input devices.
19:09:18.1608 [eInit] + (22) Hdmi CEC driver
19:09:18.1629 [eHdmiCEC] detected physical address change: 1000 --> 3000
19:09:18.1630 [eHdmiCEC] send message 0F 84 30 00 03
19:09:18.1638 [eInit] + (30) eActionMap
19:09:18.1639 [eInit] + (35) CA handler
19:09:18.1643 [eInit] + (35) CI Slots
19:09:18.1645 [CI] scanning for common interfaces..
19:09:18.1649 [CI] done, found 0 common interface slots
19:09:18.1650 [eInit] + (40) eServiceCenter
19:09:18.1652 [eServiceCenter] settings instance.
19:09:18.1653 [eInit] + (41) Stream server
19:09:18.1655 [Avahi] AvahiServiceEntry (null) (_e2stream._tcp) 8001
19:09:18.1684 [Avahi] Will Register dm820 (_e2stream._tcp) on dm820:8001
19:09:18.1717 [Avahi] Registered dm820 (_e2stream._tcp) on dm820:8001
19:09:18.1719 [eInit] + (41) RTSP Stream server
19:09:18.1721 [eInit] + (41) Encoders
19:09:18.1724 [eInit] + (41) eServiceFactoryDVB
19:09:18.1727 [eInit] + (41) eServiceFactoryFS
19:09:18.1728 [eInit] + (41) eServiceFactoryMP3
19:09:18.1731 [eInit] + (41) eServiceFactoryM2TS
19:09:18.1732 [eInit] + (41) eServiceFactoryHDMI
19:09:18.1733 [eInit] + (41) eServiceFactoryTS
19:09:18.1735 [eInit] + (41) eServiceFactoryWebTS
19:09:18.1736 [eInit] + (41) eServiceFactoryDVD
19:09:18.1738 [eInit] reached rl 70
19:09:18.1739 [eDVBDB] ---- opening lame channel db
19:09:18.1742 [eDVBDB] reading services (version 4)
19:09:18.1743 [eDVBDB] loaded 0 channels/transponders and 0 services
19:09:18.1746 [eDVBSatelliteEquipmentControl] eDVBSatelliteEquipmentControl::clear()
19:09:18.1751 [eDVBResourceManager] scanning for frontends..
19:09:18.1757 [eDVBFrontend] opening frontend 0
19:09:18.1761 [eDVBFrontend] m_need_delivery_system_workaround = 0
19:09:18.1763 [eDVBFrontend] opening frontend 0
19:09:18.1803 [eDVBFrontend] frontend 0 setDeliverySystem 17
19:09:18.1805 [eDVBFrontend] frontend 0 setDeliverySystem 6
19:09:18.1807 [eDVBFrontend] frontend 0 setDeliverySystem 5
19:09:18.1836 [eDVBFrontend0] setVoltage FE_ENABLE_HIGH_LNB_VOLTAGE 0 FE_SET_VOLTAGE 2
19:09:18.1839 [eDVBFrontend] try to close frontend 0
19:09:18.1866 [eDVBFrontend0] setVoltage FE_ENABLE_HIGH_LNB_VOLTAGE 0 FE_SET_VOLTAGE 2
19:09:18.1873 [eDVBAdapterLinux] get demux 0
19:09:18.1875 [eDVBAdapterLinux] get demux 1
19:09:18.1877 [eDVBAdapterLinux] get demux 2
19:09:18.1879 [eDVBAdapterLinux] get demux 3
19:09:18.1880 [eDVBAdapterLinux] get demux 4
19:09:18.1882 [eDVBAdapterLinux] get demux 5
19:09:18.1883 [eDVBAdapterLinux] get demux 6
19:09:18.1885 [eDVBAdapterLinux] get demux 7
19:09:18.1891 [eDVBResourceManager] found 1 adapter, 1 frontends(1 sim) and 8 demux, boxtype 7
19:09:18.1895 [eDVBLocalTimeHandler] RTC not ready, wait for transponder time!
19:09:18.1897 [eEPGCache] Initialized EPGCache (wait for setCacheFile call now)
19:09:18.1900 [eEPGTransponderDataReader] Initialized
19:09:18.1907 [Enigma] Loading spinners.
19:09:18.2177 [Enigma] Found 50 spinners.
19:09:18.2180 [Enigma] Executing StartEnigma.py
19:09:18.2182 [setIoPrio] best-effort level 3 ok
[Profile] Error: No profile data available!
19:09:18.8095 [StartEnigma] Initializing Twisted.
19:09:20.1558 [gRC] Warning: Main thread is busy, displaying spinner!
19:09:22.2156 Log opened.
19:09:22.5229 [International] International is initializing.
19:09:22.7233 [MultiBoot] MultiBoot is initializing.
19:09:22.7293 [Console] Processing command '/bin/mount' with arguments ['/bin/mount', '/dev/mmcblk0p1', '/tmp/MultiBoot_d629rpc_'].
19:09:22.7295 [eConsoleAppContainer] Starting /bin/mount
19:09:22.7331 [Console] Processing command '/bin/umount' with arguments ['/bin/umount', '/tmp/MultiBoot_d629rpc_'].
19:09:22.7332 [eConsoleAppContainer] Starting /bin/umount
19:09:22.7377 [Console] Processing command '/bin/mount' with arguments ['/bin/mount', '/dev/mtdblock2', '/tmp/MultiBoot_w5gmhflg'].
19:09:22.7380 [eConsoleAppContainer] Starting /bin/mount
19:09:23.1327 [Console] Processing command '/bin/umount' with arguments ['/bin/umount', '/tmp/MultiBoot_w5gmhflg'].
19:09:23.1328 [eConsoleAppContainer] Starting /bin/umount
19:09:23.1382 [SystemInfo] Enigma information file checksum is correct.
19:09:23.1447 [SystemInfo] Enigma information file data loaded into BoxInfo.
19:09:23.1465 [Misc_Options] 12Vdetect cannot open /proc/stb/misc/12V_output: Function not implemented
19:09:23.1559 [StartEnigma] Receiver name = Dreambox DM820
19:09:23.1563 [StartEnigma] openDroid version = 7.3
19:09:23.1567 [StartEnigma] openDroid revision = 20230514
19:09:23.1570 [StartEnigma] Build Brand = dreambox
19:09:23.1572 [StartEnigma] Build Model = dm820
19:09:23.1574 [StartEnigma] Platform = dm820
19:09:23.1577 [StartEnigma] SoC family = bcm7435
19:09:23.1579 [StartEnigma] Enigma2 revision = 1564+94f911e
19:09:23.1937 [Harddisk] enumerating block devices...
19:09:23.2042 [Harddisk] new Harddisk sda -> /dev/sda -> /dev/sda
19:09:23.2048 [Console] Processing command 'sdparm' with arguments ('sdparm', '--set=SCT=0', '/dev/sda').
19:09:23.2050 [eConsoleAppContainer] Starting sdparm
19:09:23.2215 [Harddisk] new Harddisk sdb -> /dev/sdb -> /dev/sdb
19:09:23.2580 [Harddisk] enumerating network mounts...
19:09:23.2780 [International] Activating language 'it', locale 'it_IT'.
19:09:23.6146 [InputDevice] Warning: Unknown device type: 'dreambox front panel'!
19:09:23.6148 [InputDevice] Found device 'event0' with name 'dreambox front panel' of type 'Unknown'.
19:09:23.6207 [InputDevice] Found device 'event1' with name 'dreambox remote control (native)' of type 'Remote'.
19:09:23.6266 [InputDevice] Found device 'event2' with name 'dreambox advanced remote control (native)' of type 'Remote'.
19:09:23.6326 [InputDevice] Found device 'event3' with name 'dreambox ir keyboard' of type 'Keyboard'.
19:09:23.6377 [InputDevice] Found device 'event4' with name 'dreambox ir mouse' of type 'Mouse'.
19:09:23.6426 [InputDevice] Found device 'event5' with name 'dreambox remote control (bluetooth le)' of type 'Remote'.
19:09:23.7196 [InputDevice] Default remote control identified as 'Dream Multimedia 820'.  (model='dm820', rcName='dmm2', rcType='0')
19:09:23.7215 [InputDevice] Loading remote control '/usr/share/enigma2/hardware/dmm2.xml'.
19:09:23.7337 [Keyboard] Activating keymap: 'German keyboard'.
19:09:23.7344 [Console] Processing command line 'loadkmap < /usr/share/keymaps/de.kmap'.
19:09:23.7346 [eConsoleAppContainer] Starting /bin/sh
19:09:23.8672 [NimManager] Reading satellites.xml
19:09:24.3022 [eDVBSatelliteEquipmentControl] eDVBSatelliteEquipmentControl::clear()
19:09:24.3024 [NimManager] sec config cleared
19:09:24.3032 [eDVBFrontend] setSlotInfo for dvb frontend 0 to slotid 0, descr BCM4505, need rotorworkaround No, enabled Yes, DVB-S2 No
19:09:24.3038 [NimManager] slot: 0 configmode: simple
19:09:24.3040 [eDVBSatelliteEquipmentControl] eDVBSatelliteEquipmentControl::setSlotNotLinked(0)
19:09:24.3044 [NimManager] diseqcmode:  single
19:09:24.3049 [NimManager] sec config completed
19:09:24.3055 [NimManager] slotname = A, slotdescription = BCM4505, multitype = False, current type = DVB-S2
19:09:24.3281 [Picon] adding path: /media/hdd/picon/
19:09:24.3838 [AVSwitch] reading edid modes failed, using all modes
19:09:24.3847 [AVSwitch] reading _preferred modes:  ['480i', '576i', '1080i', '1080p', '720p', '480p', '1080i50', '1080p50', '720p50', '576p', '640x480', '800x600', '1024x768']
19:09:24.4409 [ePNG] couldn't open extensions/back.png
19:09:24.5413 [TagEditor] 0 tags read from '/etc/enigma2/movietags'.
19:09:24.8340 [InfoBarGenerics] Failed to load resumepoints: [Errno 2] No such file or directory: '/etc/enigma2/resumepoints.pkl'
19:09:24.8606 [eDVBDB] loading bouquet... /etc/enigma2//bouquets.tv
19:09:24.8610 [eDVBDB] loading bouquet... /etc/enigma2//userbouquet.favourites.tv
19:09:24.8611 [eDVBDB] 0 entries in Bouquet userbouquet.favourites.tv
19:09:24.8612 [eDVBDB] 1 entries in Bouquet bouquets.tv
19:09:24.8614 [eDVBDB] loading bouquet... /etc/enigma2//bouquets.radio
19:09:24.8616 [eDVBDB] loading bouquet... /etc/enigma2//userbouquet.favourites.radio
19:09:24.8617 [eDVBDB] 0 entries in Bouquet userbouquet.favourites.radio
19:09:24.8618 [eDVBDB] 1 entries in Bouquet bouquets.radio
19:09:24.8619 [eDVBDB] Renumbering...
19:09:24.8620 [eDVBDB] Renumber Bouquets (TV), starting at 1
19:09:24.8621 [eDVBDB] Renumber Favourites (TV), starting at 1
19:09:24.8621 [eDVBDB] Renumber Bouquets (Radio), starting at 1
19:09:24.8622 [eDVBDB] Renumber Favourites (Radio), starting at 1
19:09:24.9569 initializing StackTracePrinter
19:09:24.9591 [Skin] Loading skin file '/usr/share/enigma2/skin_default.xml'.
19:09:25.1094 [Font] Adding font '/usr/share/fonts/Roboto-Bold.ttf' -> 'Regular'.
19:09:25.1107 [Font] Adding font '/usr/share/fonts/Roboto-BoldItalic.ttf' -> 'Italic'.
19:09:25.1114 [Font] Adding font '/usr/share/fonts/Roboto-Black.ttf' -> 'Bold'.
19:09:25.1121 [Font] Adding font '/usr/share/fonts/Roboto-BlackItalic.ttf' -> 'Boldit'.
19:09:25.1129 [Font] Adding font '/usr/share/fonts/nmsbd.ttf' -> 'Subtitlefont'.
19:09:25.1137 [Font] Adding font '/usr/share/fonts/lcd.ttf' -> 'LCD'.
19:09:25.1144 [Font] Adding font '/usr/share/fonts/ae_AlMateen.ttf' -> 'Replacement'.
19:09:25.1153 [Font] Adding font '/usr/share/fonts/tuxtxt.ttf' -> 'Console'.
19:09:25.1160 [Font] Adding font '/usr/share/fonts/andale.ttf' -> 'Fixed'.
19:09:25.1199 [Skin] Skin resolution is 0x0 and color depth is 0 bits.
19:09:25.1507 [Skin] Loading skin file '/usr/share/enigma2/skin_default.xml' complete.
19:09:25.1528 [Skin] Loading skin file '/usr/share/enigma2/skin_subtitles.xml'.
19:09:25.1568 [Font] Adding font '/usr/share/fonts/LiberationSans-Regular.ttf' -> 'Subs'.
19:09:25.1597 [Font] Adding font '/usr/share/fonts/LiberationSans-Italic.ttf' -> 'Subsi'.
19:09:25.1626 [Font] Adding font '/usr/share/fonts/LiberationSans-Bold.ttf' -> 'Subsb'.
19:09:25.1654 [Font] Adding font '/usr/share/fonts/LiberationSans-BoldItalic.ttf' -> 'Subsz'.
19:09:25.1706 [Skin] Skin resolution is 0x0 and color depth is 0 bits.
19:09:25.1709 [Skin] Loading skin file '/usr/share/enigma2/skin_subtitles.xml' complete.
19:09:25.1727 [Skin] Loading skin file '/usr/share/enigma2/Steampunk/skin.xml'.
19:09:25.4390 [Skin] Loading skin file '/usr/share/enigma2/Steampunk/DEV/skin_opd_team.xml'.
19:09:25.5357 [Skin] Skin resolution is 1280x720 and color depth is 32 bits.
19:09:25.5545 [Skin] Loading skin file '/usr/share/enigma2/Steampunk/DEV/skin_opd_team.xml' complete.
19:09:25.5552 [Skin] Loading skin file '/usr/share/enigma2/Steampunk/DEV/skin_plugins.xml'.
19:09:25.7638 [Skin] Skin resolution is 1280x720 and color depth is 32 bits.
19:09:25.8020 [Skin] Loading skin file '/usr/share/enigma2/Steampunk/DEV/skin_plugins.xml' complete.
19:09:25.8027 [Skin] Loading skin file '/usr/share/enigma2/Steampunk/DEV/skin_templates.xml'.
19:09:25.8576 [Skin] Skin resolution is 1280x720 and color depth is 32 bits.
19:09:25.8693 [Skin] Loading skin file '/usr/share/enigma2/Steampunk/DEV/skin_templates.xml' complete.
19:09:25.8822 [Font] Adding font '/usr/share/fonts/lcd.ttf' -> 'LCD'.
19:09:25.8851 [Font] Adding font '/usr/share/fonts/tuxtxt.ttf' -> 'Console'.
19:09:25.8880 [Font] Adding font '/usr/share/fonts/ae_AlMateen.ttf' -> 'Replacement'.
19:09:25.8903 [Font] Adding font '/usr/share/enigma2/Steampunk/fonts/digi.ttf' -> 'DIGI'.
19:09:25.8927 [Font] Adding font '/usr/share/enigma2/Steampunk/fonts/Roboto-Regular.ttf' -> 'Regular'.
19:09:25.8952 [Font] Adding font '/usr/share/enigma2/Steampunk/fonts/ds-digital.ttf' -> 'Steampunk-digital'.
19:09:25.9331 [Skin] Skin resolution is 1280x720 and color depth is 32 bits.
19:09:25.9832 [Skin] Loading skin file '/usr/share/enigma2/Steampunk/skin.xml' complete.
19:09:25.9854 [Skin] Loading skin file '/usr/share/enigma2/display/skin_display.xml'.
19:09:25.9953 [Font] Adding font '/usr/share/fonts/nmsbd.ttf' -> 'FdLcD'.
19:09:26.0005 [Skin] Skin resolution is 0x0 and color depth is 0 bits.
19:09:26.0036 [Skin] Loading skin file '/usr/share/enigma2/display/skin_display.xml' complete.
19:09:26.0083 [Skin] Loading skin file 'skin_user.xml'.
19:09:26.0087 [Skin] Warning: File 'skin_user.xml' does not exist!
19:09:26.0094 [InputDevice] InitInputDevices DEBUG: Creating config entry for device: 'event0' -> 'dreambox front panel'.
19:09:26.0107 [InputDevice] InitInputDevices DEBUG: Creating config entry for device: 'event1' -> 'dreambox remote control (native)'.
19:09:26.0118 [InputDevice] InitInputDevices DEBUG: Creating config entry for device: 'event2' -> 'dreambox advanced remote control (native)'.
19:09:26.0130 [InputDevice] InitInputDevices DEBUG: Creating config entry for device: 'event3' -> 'dreambox ir keyboard'.
19:09:26.0142 [InputDevice] InitInputDevices DEBUG: Creating config entry for device: 'event4' -> 'dreambox ir mouse'.
19:09:26.0153 [InputDevice] InitInputDevices DEBUG: Creating config entry for device: 'event5' -> 'dreambox remote control (bluetooth le)'.
19:09:26.0329 [AVSwitch] setting aspect: 16:9
19:09:26.0351 [AVSwitch] setting policy: panscan
19:09:26.0372 [AVSwitch] setting policy2: letterbox
19:09:26.0430 [AVSwitch] reading edid modes failed, using all modes
19:09:26.0439 [AVSwitch] reading _preferred modes:  ['480i', '576i', '1080i', '1080p', '720p', '480p', '1080i50', '1080p50', '720p50', '576p', '640x480', '800x600', '1024x768']
19:09:26.0552 [eDVBVolumecontrol] Setvolume: raw: 100 100, -1db: 0 0
19:09:26.0668 [AVSwitch] setting scaler_sharpness to: 0000000D
19:09:26.0684 [AVSwitch] setMode - port: HDMI, mode: 720p, rate: 50Hz
19:09:26.1197 [UsageConfig] Checking/Creating current movie directory '/media/hdd/movie/'.
19:09:26.1347 [eTuxttxtApp] enable caching
19:09:26.1696 [EPGC Load] Poller disabled.
19:09:26.1701 [EPGC Save] Poller disabled.
19:09:26.1934 [eEPGCache] setCacheFile read/write epg data from/to '/etc/enigma2/epg.dat'
19:09:26.2169 activating StackTracePrinter
19:09:26.7173 [UsageConfig] Checking/Creating current time shift directory '/media/hdd/timeshift/'.
19:09:26.8334 [Timezones] Setting time zone to 'Europe/Rome'.
19:09:26.8370 [Timezones] Local time is 'dom 14-mag-2023 19:09:26'  -  UTC time is 'dom 14-mag-2023 17:09:26'.
19:09:27.1742 Traceback (most recent call last):
19:09:27.1744   File "/usr/lib/enigma2/python/StartEnigma.py", line 897, in <module>
19:09:27.1782     fileUpdateLine("/proc/stb/hdmi-rx/0/hdmi_rx_monitor", conditionValue="on", replacementValue="off", source=MODULE_NAME)
19:09:27.1791     ^^^^^^^^^^^^^^
19:09:27.1800 NameError: name 'fileUpdateLine' is not defined
19:09:27.2003 [eDVBDB] ---- saving lame channel db
19:09:27.2007 [eDVBDB] saved 0 channels and 0 services!
19:09:27.2080 [eDVBResourceManager] release cached channel (timer timeout)
19:09:27.2093 [Avahi] avahi_watch_free
19:09:27.2110 [eInit] - (41) Stream server
19:09:27.2112 [eInit] - (41) RTSP Stream server
19:09:27.2113 [eInit] - (41) Encoders
19:09:27.2114 [eInit] - (41) eServiceFactoryDVB
19:09:27.2115 [eInit] - (41) eServiceFactoryFS
19:09:27.2115 [eInit] - (41) eServiceFactoryMP3
19:09:27.2116 [eInit] - (41) eServiceFactoryM2TS
19:09:27.2117 [eInit] - (41) eServiceFactoryHDMI
19:09:27.2117 [eInit] - (41) eServiceFactoryTS
19:09:27.2118 [eInit] - (41) eServiceFactoryWebTS
19:09:27.2118 [eInit] - (41) eServiceFactoryDVD
19:09:27.2119 [eInit] - (40) eServiceCenter
19:09:27.2119 [eServiceCenter] clear instance
19:09:27.2120 [eInit] - (35) CA handler
19:09:27.2122 [eInit] - (35) CI Slots
19:09:27.2122 [eInit] - (30) eActionMap
19:09:27.2123 [eInit] - (22) Hdmi CEC driver
19:09:27.2124 [eInit] - (21) input device driver
19:09:27.3166 [eInit] - (20) AVSwitch Driver
19:09:27.3168 [eInit] - (20) misc options
19:09:27.3169 [eInit] - (20) RC Input layer
19:09:27.3170 [eInit] - (20) UHF Modulator
19:09:27.3171 [eInit] - (20) DVB-CI UI
19:09:27.3173 [eInit] - (15) eWindowStyleManager
19:09:27.3174 [eInit] - (10) gRC
19:09:27.3176 [gRC] Waiting for gRC thread shutdown.
19:09:27.3183 [gRC] Thread has finished.
19:09:27.3185 [eInit] - (9) Font Render Class
19:09:27.3187 [eInit] - (9) gLCD
19:09:27.3188 [eInit] - (9) GFBDC
19:09:27.3193 [eInit] - (8) graphics acceleration manager
19:09:27.3194 [eInit] - (5) Tuxtxt
19:09:27.3196 [eInit] - (1) Background File Eraser
19:09:27.3197 [eInit] reached rl -1
root@dm820:~#

**Comment by atvcaptain** [comment]
i have install latest openatv 7.3 dm820 and start no crash

**Comment by jbleyel** [comment]
Please provide this file /usr/lib/enigma2/python/StartEnigma.py from your Box

**Comment by atvcaptain** [comment]
dm820 works here without any issue, we close the issue report
