### ISSUE TITLE
Please fix (zerotier) not working

### ISSUE THREAD

**Issue by atefganm** [oe-alliance/oe-alliance-core#837]
| collect2: error: ld returned 1 exit status
| make: *** [make-linux.mk:375: zerotier-one] Error 1
| ERROR: oe_runmake failed
| WARNING: /home/atef/build-enviroment-5.3/build-enviroment/builds/openvix/release/dm820/tmp/work/mips32el-oe-linux/zerotier/zerotier-1.10.6+gitAUTOINC+0e5651f353-r0/temp/run.do_compile.147999:182 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /home/atef/build-enviroment-5.3/build-enviroment/builds/openvix/release/dm820/tmp/work/mips32el-oe-linux/zerotier/zerotier-1.10.6+gitAUTOINC+0e5651f353-r0/temp/run.do_compile.147999, line 182
| 	#2: die, /home/atef/build-enviroment-5.3/build-enviroment/builds/openvix/release/dm820/tmp/work/mips32el-oe-linux/zerotier/zerotier-1.10.6+gitAUTOINC+0e5651f353-r0/temp/run.do_compile.147999, line 166
| 	#3: oe_runmake, /home/atef/build-enviroment-5.3/build-enviroment/builds/openvix/release/dm820/tmp/work/mips32el-oe-linux/zerotier/zerotier-1.10.6+gitAUTOINC+0e5651f353-r0/temp/run.do_compile.147999, line 161
| 	#4: autotools_do_compile, /home/atef/build-enviroment-5.3/build-enviroment/builds/openvix/release/dm820/tmp/work/mips32el-oe-linux/zerotier/zerotier-1.10.6+gitAUTOINC+0e5651f353-r0/temp/run.do_compile.147999, line 156
| 	#5: do_compile, /home/atef/build-enviroment-5.3/build-enviroment/builds/openvix/release/dm820/tmp/work/mips32el-oe-linux/zerotier/zerotier-1.10.6+gitAUTOINC+0e5651f353-r0/temp/run.do_compile.147999, line 151
| 	#6: main, /home/atef/build-enviroment-5.3/build-enviroment/builds/openvix/release/dm820/tmp/work/mips32el-oe-linux/zerotier/zerotier-1.10.6+gitAUTOINC+0e5651f353-r0/temp/run.do_compile.147999, line 195
ERROR: Task (/home/atef/build-enviroment-5.3/build-enviroment/meta-oe-alliance/meta-oe/recipes-connectivity/zerotier/zerotier_1.10.2.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 14879 tasks of which 13731 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/build-enviroment-5.3/build-enviroment/meta-oe-alliance/meta-oe/recipes-connectivity/zerotier/zerotier_1.10.2.bb:do_compile
Summary: There were 2 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:1031: image] Error 1
atef@atef-ganm:~/build-enviroment-5.3/build-enviroment$

**Comment by nickersk** [comment]
should be fixed: https://github.com/oe-alliance/oe-alliance-core/commit/f38c60551d19f920fc367817816ba23a91a3afe4
