### ISSUE TITLE
Add default support for f2fs as alternative to ext4

### ISSUE THREAD

**Issue by fabi003** [oe-alliance/oe-alliance-core#848]
I tried to install a new external SSD, formatted with f2fs to my Octagon SF8008 box. Mount failed, due to most distributions seems not to support it now as it is only available as module here.

I wonder if no one seems to use SSDs for recording now, as this filesystem was developed for the characteristics of flash devices which have a flash translation layer, such as SATA SSDs, where e.g ext4 was optimized for HDD use. So f2fs is more suitable then ext4 for use with SSDs now.

For more information see https://f2fs.wiki.kernel.org/.

**Comment by atvcaptain** [comment]
have you install from feed
opkg install kernel-module-f2fs-4.4.35_4.4.35-33_sf8008.ipk

i add missing f2fs-tools to feed https://github.com/oe-alliance/oe-alliance-core/commit/40fce2fb5249b40bb8fa9904dedd23e4717908c4
