### ISSUE TITLE
Error compiling Kodi on dm900.

### ISSUE THREAD

**Issue by 68foxboris** [oe-alliance/oe-alliance-core#881]
Please tell me what is missing. There are no problems with compilation on other receivers, but here there is an error.
`
/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-g++ --sysroot=/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot -DCMS_NO_REGISTER_KEYWORD=1 -DFFMPEG_VER_SHA=undef -DHAS_AIRPLAY=1 -DHAS_AIRTUNES=1 -DHAS_ALSA=1 -DHAS_AVAHI=1 -DHAS_DBUS=1 -DHAS_EGL=1 -DHAS_FILESYSTEM_NFS -DHAS_GLES=3 -DHAS_NEON -DHAS_NFS_SET_TIMEOUT -DHAS_PULSEAUDIO=1 -DHAS_UDFREAD=1 -DHAS_ZEROCONF=1 -DHAVE_LCMS2=1 -DHAVE_LIBBLUETOOTH=1 -DHAVE_LIBCAP=1 -DHAVE_LIBCEC=1 -DHAVE_LIBUDEV=1 -DHAVE_LIBXSLT=1 -DHAVE_NEW_CROSSGUID -DSPDLOG_COMPILED_LIB -DSPDLOG_DEBUG_ON -DSPDLOG_FMT_EXTERNAL -DSPDLOG_NO_ATOMIC_LEVELS -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/lib -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/platform/linux -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/cores/VideoPlayer -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/build/build -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/build/build/include -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/platform/posix -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/python3.12 -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/samba-4.0 -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/fribidi -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/contrib -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/lzo -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/gstreamer-1.0 -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/glib-2.0 -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/lib/glib-2.0/include -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/dbus-1.0 -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/lib/dbus-1.0/include -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/libxml2 -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/harfbuzz -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/freetype2 -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot/usr/include/libpng16 -I/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/build/build/cores/RetroPlayer/messages -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a15 -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64  --sysroot=/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/recipe-sysroot  -fomit-frame-pointer -O3 -ffast-math -fvisibility-inlines-hidden -DTARGET_POSIX -DTARGET_LINUX -D_LINUX -DTARGET_STB -DTARGET_STB_EXTEND -DTARGET_V3D -DTARGET_DREAMBOX -DMESA_EGL_NO_X11_HEADERS -Wall -Wdouble-promotion -Wmissing-field-initializers -Wsign-compare -Wextra -Wno-unused-parameter -Wnon-virtual-dtor -O2 -g -DNDEBUG -std=c++17 -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -DHAS_POSIX_NETWORK -DHAS_LINUX_NETWORK -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAVE_INOTIFY=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIBBLURAY=1 -DHAVE_LIBBLURAY_BDJ=1 -DHAS_ISO9660PP=1 -DHAS_WEB_SERVER=1 -DHAS_WEB_INTERFACE=1 -DHAS_PYTHON=1 -DHAS_FILESYSTEM_SMB=1 -DHAVE_LIBGSTREAMER=1 -DHAS_UPNP=1 -DBIN_INSTALL_PATH=\"/usr/lib/kodi\" -DINSTALL_PATH=\"/usr/share/kodi\" -Werror=double-promotion -Werror=missing-field-initializers -Werror=sign-compare -MD -MT build/windowing/egl/CMakeFiles/windowing_egl.dir/EGLNativeTypeDreambox.cpp.o -MF build/windowing/egl/CMakeFiles/windowing_egl.dir/EGLNativeTypeDreambox.cpp.o.d -o build/windowing/egl/CMakeFiles/windowing_egl.dir/EGLNativeTypeDreambox.cpp.o -c /home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/windowing/egl/EGLNativeTypeDreambox.cpp
/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/windowing/egl/EGLNativeTypeDreambox.cpp: In member function 'virtual bool CEGLNativeTypeDreambox::CheckCompatibility()':
/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/windowing/egl/EGLNativeTypeDreambox.cpp:46:3: error: 'name' was not declared in this scope; did you mean 'tzname'?
   46 |   name = model.Get<std::string>();
      |   ^~~~
      |   tzname
/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/windowing/egl/EGLNativeTypeDreambox.cpp: In member function 'virtual bool CEGLNativeTypeDreambox::ShowWindow(bool)':
/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/windowing/egl/EGLNativeTypeDreambox.cpp:152:3: error: 'SysfsUtils' has not been declared
  152 |   SysfsUtils::SetInt("/proc/stb/video/alpha", show ? 255 : 0);
      |   ^~~~~~~~~~
/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/windowing/egl/EGLNativeTypeDreambox.cpp: In member function 'bool CEGLNativeTypeDreambox::SetDisplayResolution(const char*)':
/home/foxbob/test1/build/tmp/work/dm900-oe-linux-gnueabi/stb-kodi-dm900/21.0-Omega/git/xbmc/windowing/egl/EGLNativeTypeDreambox.cpp:160:47: error: cannot convert 'std::__cxx11::basic_string<char>' to 'const char*' in assignment
  160 |   mode = videomode.Get<std::string>().value_or("");
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
      |                                               |
      |                                               std::__cxx11::basic_string<char>

`

**Comment by atvcaptain** [comment]
we dont support kodi for dm models, you must find self a solution
