### ISSUE TITLE
ncam.bb:do_populate_lic

### ISSUE THREAD

**Issue by atefganm** [oe-alliance/oe-alliance-core#883]
ERROR: enigma2-plugin-softcams-ncam-1.20+git-r1 do_populate_lic: QA Issue: enigma2-plugin-softcams-ncam: LIC_FILES_CHKSUM points to an invalid file: /home/atef/build-enviroment-5.5/build-enviroment/builds/openvix/release/dm820/tmp/work/mips32el-oe-linux/enigma2-plugin-softcams-ncam/enigma2-plugin-softcams-ncam-1.20+git-r1/git/../NCAM-LICENSE [license-checksum]
ERROR: enigma2-plugin-softcams-ncam-1.20+git-r1 do_populate_lic: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /home/atef/build-enviroment-5.5/build-enviroment/builds/openvix/release/dm820/tmp/work/mips32el-oe-linux/enigma2-plugin-softcams-ncam/enigma2-plugin-softcams-ncam-1.20+git-r1/temp/log.do_populate_lic.3190004
ERROR: Task (/home/atef/build-enviroment-5.5/build-enviroment/meta-oe-alliance/meta-oe/recipes-distros/openvix/softcams/enigma2-plugin-softcams-ncam.bb:do_populate_lic) failed with exit code '1'
NOTE: Tasks Summary: Attempted 7645 tasks of which 34 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/atef/build-enviroment-5.5/build-enviroment/meta-oe-alliance/meta-oe/recipes-distros/openvix/softcams/enigma2-plugin-softcams-ncam.bb:do_populate_lic
Summary: There were 7 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
make: *** [Makefile:1031: image] Error 1
atef@atef-ganm:~/build-enviroment-5.5/build-enviroment$

**Comment by atvcaptain** [comment]
vix and bh not start porting to 5.5 you must wait some month, we have start now check all for openatv this is not ready too
