### ISSUE TITLE
vusolo2 build error

### ISSUE THREAD

**Issue by WanWizard** [oe-alliance/oe-alliance-core#899]
````
ERROR: vuplus-dvb-modules-vusolo2-3.13.5+20190429-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'https://source.mynonpublic.com/vuplus/release/vuplus-dvb-modules/vuplus-dvb-modules-vusolo2-3.13.5-20190429.tar.gz'))
````

**Comment by atvcaptain** [comment]
we build very long vuplus-dvb-proxy-vusolo2-3.13.5-20190429.r0.tar.gz

i dont have the non proxy driver, if you have i can upload too

**Comment by WanWizard** [comment]
So all these recipies in https://github.com/oe-alliance/oe-alliance-core/tree/5.4/meta-brands/meta-vuplus/recipes-drivers are no longer used?

**Comment by atvcaptain** [comment]
solo2 build proxy and the old not use yes

**Comment by WanWizard** [comment]
Ok, I'lve dig it out of the source cache, thanks.
