### ISSUE TITLE
wetek play image is not baking anymore

### ISSUE THREAD

**Issue by justason** [oe-alliance/oe-alliance-core#99]
crashes on enigma2 recipe.

**Comment by koivo** [comment]
Yes same here:
Collected errors:
- satisfy_dependencies_for: Cannot satisfy the following dependencies for openhdf-base:
-  libungif4 (>= 4.1.4) *

**Comment by atvcaptain** [comment]
hdf distro.conf is old

compare this

https://github.com/oe-alliance/oe-alliance-core/blob/3.2/meta-oe/conf/distro/openhdf.conf#L80

https://github.com/oe-alliance/oe-alliance-core/blob/3.2/meta-oe/conf/distro/openatv.conf#L82

**Comment by justason** [comment]
Im backing OpenAtv.
crashed on enigna2.bb do_configure stage.

**Comment by atvcaptain** [comment]
use wrong build atv you must use this: https://github.com/wetek-enigma/build-enviroment

**Comment by atvcaptain** [comment]
wetek not update in oe-a build

**Comment by henrylicious** [comment]
wetek is updated now...
